### ISSUE TITLE
[Question] Is it possible to force BackgroundImage to use webp format by default for supported browsers?

### ISSUE THREAD

**Issue by apaulau** [timhagn/gatsby-background-image#10]
I've tried suggested solution from `How to use` section with JPEG image and `GatsbyImageSharpFluid_withWebp` fragment. But in chrome it still uses JPEG image though processed. Lighthouse reports that image can be served in next-gen format:

![image](https://user-images.githubusercontent.com/4561050/54184108-e9dfb680-44b6-11e9-9507-d09c271d8698.png)

Maybe I've missed something?

**Comment by timhagn** [comment]
Hi @apaulau,

nice (or not so nice ; ) coincidence: just started working on this last week
and it's high on my priority list for this one!

The cause of it is the removal of the (then thought "superfluous") `<Img />`
component with switching to `Image()` creation after Issue #1.
Should be solved as soon as `v0.2.5` drops, but for the moment 
(and only for [WebP capable browsers](https://caniuse.com/#feat=webp)) 
you might use a function such a the following to switch out JPEG for WebP
before giving the fluid / fixed data to `<BackgroundImage />`:
```js
/**
 * Transitory possibility for switching to WebP.
 *
 * @param imageData   Default imageData (fluid / fixed) from GraphQL query.
 * @return {Object}   Switched source properties to WebP.
 */
const switchToWebP = imageData => {
  let convertedImageData = { ...imageData }

  if (convertedImageData.src && convertedImageData.srcWebp) {
    convertedImageData.srcDefault = convertedImageData.src
    convertedImageData.src = convertedImageData.srcWebp
  }
  if (convertedImageData.srcSet && convertedImageData.srcSetWebp) {
    convertedImageData.srcSetDefault = convertedImageData.srcSet
    convertedImageData.srcSet = convertedImageData.srcSetWebp
  }

  return convertedImageData
}
```
And use it like thus:
```js
const imageData = switchToWebP(data.desktop.childImageSharp.fluid)
```
I added it to the example repo [gbitest](https://github.com/timhagn/gbitest) as well. Hope it helps for the moment : )!

**Comment by timhagn** [comment]
Hi @apaulau,

with the latest master no workaround should be necessary any more,
would you mind testing `v0.2.5` in your environment : )?

**Comment by apaulau** [comment]
Hi @timhagn,

Just checked, works like a charm for me! Thanks for your effort.

**Comment by timhagn** [comment]
Hi @apaulau,

happy to hear that and you're more than welcome : )!
One question if you'd be so kind: 
Might I deduce - from "works like a charm" - that you can't replicate issue #12, either?

**Comment by apaulau** [comment]
> Hi @apaulau,
> 
> happy to hear that and you're more than welcome : )!
> One question if you'd be so kind:
> Might I deduce - from "works like a charm" - that you can't replicate issue #12, either?

Yep, was not able to reproduce it

**Comment by r007** [comment]
+1 for WebP. Lighthouse shows the same thing. Thanks for the workaround by the way.

**Comment by apaulau** [comment]
Hi @timhagn,

Seems like I have this issue again after updating to latest version. You can reproduce it with `gbitest` by specifying `GatsbyImageSharpFluid_withWebp` format.
In `::before` there is a webp image
![image](https://user-images.githubusercontent.com/4561050/56643566-87b3cd00-6682-11e9-961f-1568b6c38127.png)
but in `::after` you will find a jpeg
![image](https://user-images.githubusercontent.com/4561050/56643522-71a60c80-6682-11e9-9f6a-a8bc91c63a99.png)

**Comment by timhagn** [comment]
Hi @apalau,

don't see an issue here with `gatsby-background-image`, that would rather be an `gatsby-plugin-sharp` one - cause this is the object I get with the `GasbyImageSharpFluid_withWebp` GraphQL-Fragement:
```json
{
  "base64": "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wgARCAAUABQDASIAAhEBAxEB/8QAGAABAQADAAAAAAAAAAAAAAAAAAIBAwX/xAAVAQEBAAAAAAAAAAAAAAAAAAACAf/aAAwDAQACEAMQAAAB4dTliAbVCmsG/wD/xAAVEAEBAAAAAAAAAAAAAAAAAAABEP/aAAgBAQABBQIpS//EABQRAQAAAAAAAAAAAAAAAAAAACD/2gAIAQMBAT8BH//EABQRAQAAAAAAAAAAAAAAAAAAACD/2gAIAQIBAT8BH//EABQQAQAAAAAAAAAAAAAAAAAAADD/2gAIAQEABj8CH//EABYQAQEBAAAAAAAAAAAAAAAAAAEQAP/aAAgBAQABPyGGmnf/2gAMAwEAAgADAAAAEBfwf//EABURAQEAAAAAAAAAAAAAAAAAAAEQ/9oACAEDAQE/EGM//8QAFhEAAwAAAAAAAAAAAAAAAAAAARAx/9oACAECAQE/EBEIv//EABgQAAMBAQAAAAAAAAAAAAAAAAAQMUEB/9oACAEBAAE/EBhSYUnYUf/Z",
  "aspectRatio": 1,
  "src": "/static/41d69c74142edcc878ff7122603d84d2/c70d0/seamless-bg-desktop.jpg",
  "srcSet": "/static/41d69c74142edcc878ff7122603d84d2/11344/seamless-bg-desktop.jpg 1040w,\n/static/41d69c74142edcc878ff7122603d84d2/9e805/seamless-bg-desktop.jpg 2080w,\n/static/41d69c74142edcc878ff7122603d84d2/c70d0/seamless-bg-desktop.jpg 4160w,\n/static/41d69c74142edcc878ff7122603d84d2/0779a/seamless-bg-desktop.jpg 4167w",
  "srcWebp": "/static/41d69c74142edcc878ff7122603d84d2/9193e/seamless-bg-desktop.webp",
  "srcSetWebp": "/static/41d69c74142edcc878ff7122603d84d2/09dd9/seamless-bg-desktop.webp 1040w,\n/static/41d69c74142edcc878ff7122603d84d2/deeaf/seamless-bg-desktop.webp 2080w,\n/static/41d69c74142edcc878ff7122603d84d2/9193e/seamless-bg-desktop.webp 4160w,\n/static/41d69c74142edcc878ff7122603d84d2/bb5cb/seamless-bg-desktop.webp 4167w",
  "sizes": "(max-width: 4160px) 100vw, 4160px"
}
```

And of course there's the **base64** image in the `:after` pseudo element, as we haven't used the 
`GatsbyImageSharpFluid_withWebp_noBase64` Fragment (with it there'd only be WebP-Images in both pseudo-elements in the end) and `gatsby-backrgound-image` is fading in from that - or am I missing something you'd like in instead of the base64 image ; )?

Greetz,

Tim.

**Comment by apaulau** [comment]
Thanks for you answer and sorry for misconception, everything is fine with base64 :) Initially I thought that was the reason of lighthouse complain but now I see that there is another thing.. And it a bit strange: on local instance base64 and webp images are used (and it's expected) but on deployed to netlify [instance](https://priceless-clarke-090e60.netlify.com/) I see an extra request for jpeg image..
![image](https://user-images.githubusercontent.com/4561050/56658505-7333fc80-66a3-11e9-90d0-427ddd6f5157.png)

Closing this issue since seems like it isn't related.
