### ISSUE TITLE
Multiple Backgrounds Failing

### ISSUE THREAD

**Issue by bzmillerboy** [timhagn/gatsby-background-image#101]
## Summary
When using multiple backgrounds, the `gatsby-build` fails with `WebpackError: TypeError: Cannot read property 'tracedSVG' of null`

## Relevant information

I've got my background:
```
    <BackgroundImage
      Tag="section"
      className="flex flex-col md:flex-row items-center px-12 pt-32 pb-40 lg:pb-64"
      fluid={backgroundFluidImageStack}
      backgroundColor={`#a5a5a5`}>
```
and my stacked backgrounds
```
  const imgFluid = getFluidGatsbyImage(props.mainImage.asset._ref, {}, sanityConfig)
  const backgroundFluidImageStack = [
    imgFluid,
    `linear-gradient(to right, rgba(255,255,255,1) 0%,rgba(242,187,0,0.15) 100%)`
  ].reverse()
```

this works fine when running `gatsby develop` but I get the following error when building.

```
 ERROR #95313 

Building static HTML failed for path "/homepage/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  44 |       }
  45 | 
> 46 |       return dataElement[propName] || "";
     |                          ^
  47 |     });
  48 |     return getUrlString({
  49 |       imageString: imageString,


  WebpackError: TypeError: Cannot read property 'tracedSVG' of null
  
  - ImageUtils.js:46 
    node_modules/gatsby-background-image/lib/ImageUtils.js:46:26
  
  - ImageUtils.js:37 getCurrentFromData
    node_modules/gatsby-background-image/lib/ImageUtils.js:37:28
  
  - ImageHandling.js:30 switchImageSettings
    node_modules/gatsby-background-image/lib/ImageHandling.js:30:53
  
  - index.js:269 BackgroundImage.render
    node_modules/gatsby-background-image/index.js:269:68
```

### Environment (if relevant)

  System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v10.18.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.18.7 => 2.18.7 
    gatsby-background-image: ^0.10.0 => 0.10.0 
    gatsby-image: ^2.2.40 => 2.2.40 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-postcss: ^2.1.16 => 2.1.16 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16 
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5 
    gatsby-source-sanity: ^5.0.4 => 5.0.4 
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14 
  npmGlobalPackages:
    gatsby-cli: 2.8.29

**Comment by bzmillerboy** [comment]
I should note, this works fine if I reference `imgFluid` instead of `backgroundFluidImageStack `.

```
    <BackgroundImage
      Tag="section"
      className="flex flex-col md:flex-row items-center px-12 pt-32 pb-40 lg:pb-64"
      fluid={backgroundFluidImageStack}
      backgroundColor={`#a5a5a5`}>
```

**Comment by timhagn** [comment]
Hi @bzmillerboy,

should be fixed in the just released `v0.10.1`. But as this is the second similar bug, would you mind creating a reproduction case? As I'm tapping in the dark, _why_ it happened (haven't seen such errors in the wild, even in a macOS VM % ). 

Best,

Tim.

**Comment by akrock** [comment]
Might be related I'm seeing the following on `v0.10.1`

```TypeError: Cannot use 'in' operator to search for 'tracedSVG' in linear-gradient(rgba(87, 8, 97, 0.53), rgba(87, 8, 97, 0.27))

  43 |     return dataElement;
  44 |   }
  45 | 
> 46 |   return dataElement && propName in dataElement ? dataElement[propName] : "";
  47 | });
  48 | return getUrlString({
  49 |   imageString: imageString,
```

My image stack: 

```
export const hexToRgb = (hex: string) => {
    // Expand shorthand form (e.g. "03F") to full form (e.g. "0033FF")
    var shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
    hex = hex.replace(shorthandRegex, function (m, r, g, b) {
        return r + r + g + g + b + b;
    });

    var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16)
    } : null;
};

export const getBackgroundImageStack = (image: import("gatsby-background-image").IFluidObject, color: string) => {
    var rgb = hexToRgb(color);
    return [
        image,
        `linear-gradient(rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, 0.53), rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, 0.27))`
    ].reverse();
};
```

**Comment by bzmillerboy** [comment]
@timhagn I updated to `v0.10.1` and I'm now getting the following error.

![TraceSVG Error](https://cdn-std.droplr.net/files/acc_591113/saVLHO)

I'm working on reproducing this in Codesandbox now. Until then, my code is open: https://github.com/bzmillerboy/newmantractor.com/blob/design-system/web/src/components/block-content/hero.js#L11-L15

**Comment by timhagn** [comment]
Thanks a lot, now things are a little clearer. Gonna try looking into it tomorrow morning : ).

**Comment by timhagn** [comment]
Hi @bzmillerboy,

didn't get around to it yesterday, but just looked into it. It affected `gbitest` as well, no idea how this string-handling bug could elude me oO.
But now it works again, at least for me, with the just published `v0.10.2`.
Would you mind testing it? You're welcome to join as well, @akrock : ).

Best,

Tim.

**Comment by njosefbeck** [comment]
I was having this issue as well and it now seems fixed for me!

**Comment by akrock** [comment]
Can confirm it also resolves my issues as well. Thanks @timhagn!

**Comment by bzmillerboy** [comment]
Thanks @timhagn, this resolved the issue!
