### ISSUE TITLE
Remove console logs

### ISSUE THREAD

**Issue by ness-EE** [timhagn/gatsby-background-image#102]
## Summary

Please can you remove all the console logs, which are appearing in a production build?

### Basic example

    

line 124 of ImageUtils.js
`console.log('foundMedia', mediaData[foundMedia]);`

**Comment by timhagn** [comment]
Ups, some leftovers ^^. Removed 'em in the just released `v0.10.1`.

Best,

Tim.

**Comment by timhagn** [comment]
As this is definitely solved, I'm closing it ; ).
