### ISSUE TITLE
Flashing image on page transitions (Safari only)

### ISSUE THREAD

**Issue by samajammin** [timhagn/gatsby-background-image#106]
## Summary
Hey there - thanks for the great library!

I'm using `gatsby-background-image` in a project ([source code here](https://github.com/ethereum/ethereum-foundation-website)). It appears to work as expected except for in 1) Safari browsers & 2) mobile browsers (Safari & Chrome), where it flashes white between page transitions. This only happens on a deployed version of the site - I don't encounter this issue when developing locally in a Safari browser or emulating a mobile device in Chrome Devtools.

## Relevant information

[Here's the component](https://github.com/ethereum/ethereum-foundation-website/blob/master/src/components/FullBackground.js) where I use the `BackgroundImage` & [here's a preview deploy of the website](https://admiring-shaw-bed230.netlify.com/). I've reproduced the issue on both Chrome & Safari on an iPhone. All browsers on desktop (Chrome, Brave, Firefox) except Safari seem to work fine.

I've isolated this issue to be the background image - I tested removing my `FullBackground` component from my `Layout` component & page transitions all work normally (with no flashing). Any idea what may be causing this issue? 🙏 😬

Thank you in advance!

### Environment (if relevant)

```
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.0.7 - /usr/local/bin/bash
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 72.0.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11 
    gatsby-background-image: ^0.10.2 => 0.10.2 
    gatsby-image: ^2.2.31 => 2.2.31 
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27 
    gatsby-plugin-offline: ^3.0.19 => 3.0.19 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14 
    gatsby-plugin-sharp: ^2.2.37 => 2.2.37 
    gatsby-plugin-styled-components: ^3.1.14 => 3.1.14 
    gatsby-source-filesystem: ^2.1.36 => 2.1.36 
    gatsby-transformer-sharp: ^2.3.3 => 2.3.3 
```

### File contents (if changed)

`package.json`: N/A

**Comment by samajammin** [comment]
I tried removing `gatsby-background-image` & just using a standard Gatsby image. You can see the [PR here](https://github.com/ethereum/ethereum-foundation-website/pull/14) & the [preview deploy here](https://deploy-preview-14--admiring-shaw-bed230.netlify.com/). This fixed my issue with the flashing on page transitions but unfortunately it creates another issue of the background height not expanding with the size of my content 😕

**Comment by samajammin** [comment]
Interesting - moving my `FullBackground` component from within my `Layout` component to within the `wrapPageElement` fixed the flashing when opening & closing the footer but not on page transitions. [PR here](https://github.com/ethereum/ethereum-foundation-website/pull/16) & [preview deploy here](https://deploy-preview-16--admiring-shaw-bed230.netlify.com/).

**Comment by timhagn** [comment]
Hi @samajammin,

sorry for responding so late, the last two weeks were quite stressful % ).
Gonna try digging in this week, no quick reason for this behavior comes to mind...

Best,

Tim.

**Comment by samajammin** [comment]
Thanks @timhagn, I appreciate it!

Update on the cause - it looks to be a Safari browser issue, not a mobile issue (I'm noticing it on iPhone, iPad & Macbook in Safari). No other browsers appear to have this issue.

**Comment by timhagn** [comment]
Hi @samajammin,

preparing the just released `v1.0.0` didn't give me much time to look into this, but I'm gonna try working on this during the week (Covidl has us all in its grip @ WFH % ).

Best nevertheless,

Tim.

**Comment by ricevind** [comment]
Hi,
i am experiencing same behaviour. 
I am also using netlify to host my simple website.

Maybe this might help with resolving the problem.
I am suspecting problem with `Cache-Control` header that netlify is setting by default `Cache-Control: public, max-age=0, must-revalidate`
Not in Chrome but Safari flashes white background when encountering 304 response

**Comment by timhagn** [comment]
Hi @ricevind,

thanks a lot for chiming in! Haven't used `gbi` on netlify myself, so can't tell, but it would make a whole lot of sense with the `Cache-Control` header being to "blame".
Hope I find time this week to investigate : )!

Best,

Tim.

**Comment by samajammin** [comment]
I'm still having this issue.

**Comment by timhagn** [comment]
Hi @samajammin,

so @ricevind's workaround didn't help? Am still a little plastered with work, but definitely haven't forgotten your issue. But, alas, I can't make any promises at the moment when I should find the time,
but don't lose heart : ).

Best,

Tim.

**Comment by samajammin** [comment]
Ah, I'm sorry I totally forgot about that. It looks to have fixed the issue for me, thanks @ricevind @timhagn! Closing this out.
