### ISSUE TITLE
background-position-x doesn't update with media query

### ISSUE THREAD

**Issue by hgezim** [timhagn/gatsby-background-image#108]
## Description

With CSS like the following, `background-position-x` remains constant to `right` and doesn't get updated when page width changes to <1400px.
```
          background-position-y: top;
          background-position-x: right;
          height: 708px;
          @media (max-width: 1400px) {
            background-position-x: 380px;
          }
```

Related to: 

https://github.com/timhagn/gatsby-background-image/issues/107
https://github.com/timhagn/gatsby-background-image/issues/71#issuecomment-600596296
https://github.com/timhagn/gatsby-background-image/issues/71#issuecomment-583661748

Here's how it works without using GBI.

Width > 2000px:
![Xnip2020-04-09_15-43-06](https://user-images.githubusercontent.com/124675/78944539-5c84e200-7a7b-11ea-8211-c82612f210e8.png)

Width < 1400px:
![Xnip2020-04-09_15-46-01](https://user-images.githubusercontent.com/124675/78944551-6575b380-7a7b-11ea-9117-907c8db6241d.png)

As you can see media query works fine. Using GBI it's a different story
Width > 2000px (this is fine):
![Xnip2020-04-09_15-49-30](https://user-images.githubusercontent.com/124675/78944601-83431880-7a7b-11ea-8778-35e6fa1b5ea2.png)

Width < 1400px, (this is incorrect):
![Xnip2020-04-09_15-51-42](https://user-images.githubusercontent.com/124675/78944620-8ccc8080-7a7b-11ea-89c4-bb3853731df0.png)

I've tried combining `background-position-y` and `background-position-x` into `background-position` but that also has the same behaviour. 

### Steps to reproduce

```
export const FlexWithBackgroundImage = styled(props => {
  const tag = props.as ? props.as : 'div'
  return <BackgroundImage Tag={tag} {...props} />
})`
  ${flexCss};

  @media (min-width: 940px) {
    flex-direction: ${(p: FlexProps) => (p.row ? 'row' : 'column')};
  }
`

<FlexWithBackgroundImage
        fluid={props.fileNameToPath['header-image.jpg']}
        css={css`
          background-image: url(${headerImage});
          background-size: contain;
          background-repeat: no-repeat;
          background-position-y: top;
          background-position-x: right;
          height: 708px;
          @media (max-width: 1400px) {
            background-position-x: 380px;
          }
        `}
      >
Content here
</FlexWithBackgroundImage>
```

### Expected result

When width is reduced to below 1400px, background position should update to 380px;

### Actual result

Background position remains at the initial value of `right`.

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.7.0/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12 
    gatsby-background-image: ^1.0.1 => 1.0.1 
    gatsby-image: ^2.3.1 => 2.3.1 
    gatsby-plugin-emotion: ^4.2.1 => 4.2.1 
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3 
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1 
    gatsby-plugin-sharp: ^2.5.4 => 2.5.4 
    gatsby-plugin-typescript: ^2.3.1 => 2.3.1 
    gatsby-source-filesystem: ^2.2.2 => 2.2.2 
    gatsby-transformer-sharp: ^2.4.4 => 2.4.4 
```

**Comment by timhagn** [comment]
Hi @hgezim,

have you tried directly targeting the pseudo-elements as written in the [README](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#responsive-styling) as well?

Best,

Tim.

**Comment by hgezim** [comment]
Thanks for the quick response, @timhagn .I'll try to figure how to do that with emotion. If anyone know, let me know!

**Comment by timhagn** [comment]
AFAIK, emotion doesn't work much different from styled-components (but haven't tried, yet ; ), so hope you're good with the example : )!

**Comment by hgezim** [comment]
Nope. Can't figure it out how to try it on emotion.

**Comment by timhagn** [comment]
Then show what you've got and I'm gotta try digging in.

**Comment by hgezim** [comment]
I managed to target the element I want like so:

```
    <Flex
      as="header"
      css={css`
        width: 100%;
        & .bg-mobile-fixed-auto {
          background-position: top right;
          /* background-position: right; */
        }
        @media (max-width: 1400px) {
          & .bg-mobile-fixed-auto {
            display: none;
            background-position: top 380px;
          }
        }
      `}
    >
      <Nav fileNameToPath={props.fileNameToPath} />
      <FlexWithBackgroundImage
        className={'bg-mobile-fixed-auto'}
        fluid={props.fileNameToPath['header-image.jpg']}
        css={css`
          /* background-image: url(${headerImage}); */
          background-size: contain;
          background-repeat: no-repeat;
          height: 708px;
        `}
      >
```

In this example, `background-position*` is overwritten completely in all widths with `center` value:

![Xnip2020-04-12_20-45-02](https://user-images.githubusercontent.com/124675/79088009-800b8f00-7cfe-11ea-81ba-0e1c3309d66e.png)

**Comment by timhagn** [comment]
Hi @hgezim,

as you might have read in the [README](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#styling--passed-through-styles), `background-position` defaults to `center`
(and how to overwrite it). 
Though I haven't used Emotion yet, I'd guess that it works similar to `styled-components` so 
`bg-mobile-fixed-auto` "belongs" to the Flex component when you're using it with `&`.
And (as written in the linked paragraph) you still have to target the `bg-mobile-fixed-auto:before & bg-mobile-fixed-auto:after` pseudo-elements & overwrite the default value with `style={{ background-position: '' }}`.
Hope that helps!

Best,

Tim.

**Comment by hgezim** [comment]
I'm not sure what I'm missing but I attempted to set `style={{ background-position: '' }}` on the component without success. Going to leave this for now.

If I had one point of feedback is that it's quite difficult to get this right. Not sure what a solution might look like.
