### ISSUE TITLE
[Question] Troubles with Netlify builds

### ISSUE THREAD

**Issue by petrpacas** [timhagn/gatsby-background-image#11]
Hey there,

I'm still troubleshooting this, so can't really pinpoint my issue (might end up being unrelated)...

What I'm struggling with is the fact that when I deploy my site to Netlify, everything gets rebuilt, even if I change one letter in 404 file or sth. That ends up being a 15min build, instead of like 1min it takes on local.

**For some reason Netlify seems to be forced to ignore the cache - localhost (gatsby build > gasby serve) doesn't have any problems.**

So far one of the possibilities is the way this plugin works - you seem to dynamically create the class names (e.g. `.gatsby-background-image-egmmjii`) - I'm not sure whether this is only done on page load, or if these ever changing names already exist in the built files stored in Netlify cache.

**So my question is - have you ever used your plugin in a site deployed to Netlify - and if so - ever noticed this issue?**

(cc @pruzicka)

**Comment by timhagn** [comment]
Hi @petrpacas (& @pruzicka)!

No, I haven't had the chance to deploy and build a project with `gatsby-background-image` on Netlify.
But should your issue pertain this component and the (only per default) dynamically created class names, there's an easy solution with setting a fixed prop of `classId`, as described in the [Configuration & props](https://github.com/timhagn/gatsby-background-image#configuration--props) section of `README.md` - you can see it in action in the example repos [BackgroundSection](https://github.com/timhagn/gbitest/blob/6d2b6c23d56ec8d95a81967d5c22a434ed99b5a2/src/components/index.js#L59).

Hope it helps - and please keep me posted on any updates : )!

**Comment by zachgaskin** [comment]
I'm a noob but I recently deployed to Netlify without the issues you mention using gatsby-background-image.

**Comment by petrpacas** [comment]
It seems I was wrong after all (and the static class didn't change a thing).

It looks like Netlify caches stuff, but doesn't cache the stuff that Gatsby users need and therefore it ends up reprocessing all the images and what not.

This plugin seems to deal with it (have yet to test it myself):
https://github.com/axe312ger/gatsby-plugin-netlify-cache

A gotcha (for the time being):
https://github.com/axe312ger/gatsby-plugin-netlify-cache/issues/15

**Comment by timhagn** [comment]
@petrpacas @zachgaskin 
So might I deduce that the initial issue was a Netlify problem
and had nothing to do with `gatsby-background-image` and this one can be closed?
Or do you think we should add a warning for this case (haven't seen one in `gatsby-image`)?

**Comment by petrpacas** [comment]
Feel free to just close - thanks for your support :-)

**Comment by timhagn** [comment]
You're more than welcome - will keep this issue in my mind, should I get a Netlify Project : )!
