### ISSUE TITLE
Styling the blur-up transition

### ISSUE THREAD

**Issue by ardiewen** [timhagn/gatsby-background-image#110]
## Summary

Hi Tim, thanks again for being so responsive on past issues. I just had a quick question with regards to the possibility of styling the "blur up effect".

I'm trying to "soften" the blur up effect, similar to how Medium treats their images.

On **gatsby-image**, I can use the `placeholderStyle` prop to pass a css property of `filter: blur(15px)` to achieve this effect.

According to your documentation however, it appears that **gatsby-background-image** doesn't use this placeholder at all. And indeed, I don't see the typical placeholder div / img html that **gatsby-image** generates:

```
<div aria-hidden="true" style="width: 100%; padding-bottom: 93.8343%;"></div>
<img aria-hidden="true" src="data:image/jpeg;base64,..." alt="" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: contain; object-position: center center; opacity: 0; transition-delay: 500ms; filter: blur(15px);">
```

Any recommendations on how to achieve the desired effect I'm looking for?

Thanks in advance!

**Comment by timhagn** [comment]
Hi @ardiewen,

yup, the times of `gbi` using placeholder elements are gone since `v0.2.5`, methinks.
But there already is an example of using `filter` in the [README](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#passed-props-for-styled-components-and-suchlike). Should you need more info, [CSSTricks](https://css-tricks.com/apply-a-filter-to-a-background-image/) got you covered : ). 
I'd either use an `onStartLoad()` or `onLoad()` callback to remove the filter on the `background-image`. With the first you get the reference to the image, which you then could check for `complete` like thus:

```
// true when image has loaded
imageRef.complete && imageRef.naturalWidth !== 0 && imageRef.naturalHeight !== 0
```

Hope this helps, best,

Tim

**Comment by ardiewen** [comment]
Hey Tim, this makes sense, thank you!

It looks like the `onStartLoad()` and `onLoad()` callbacks you are referencing are the same as gatsby-image, right?

If so, I'm not understanding where the imageRef comes from, when using `onStartLoad()`. According to **gatsby-image** documentation, the only param available to me is `wasCached`.

I've made a minimal reproduction here using `gatsby-image 2.3.4` and `gatsby-background-image 1.1.1` :
https://codesandbox.io/s/gifted-monad-d67m4

Ardie

**Comment by timhagn** [comment]
Hi @ardiewen / Ardie,

yeah, you're right, of course! `wasCached` is their param, not the ref itself...
Sry for that, recited from the top of my head, should have looked at the sources ; ).
But `onLoad` would fire after the image has loaded, nevertheless, so it would probably still be usable in your case : ).

Any progress in the meantime or would you need further help?

Best,

Tim.

**Comment by ardiewen** [comment]
Hey Tim,

I was able to use the `onLoad()` callback to add a class to the BackgroundImage component that removes the `filter: blur(15px)` css.

However, this implementation doesn't work with styled-components and passed props, as the updated prop causes the styled-component to re-render...

However, I feel like that's less an issue with your library and more of something I need to figure out myself. Any additional thoughts are welcome, though :).

If I figure it out, I'll add an update to this issue for discoverability.

**Comment by ardiewen** [comment]
Alright, here's the example on how to do this with styled components. I decided to avoid passed props into styled components for the reasons above.

I assigned a `ref` prop on the styled-component to access the selfRef method of the BackgroundImage component. Using this, we can toggle an additional class onto the component during the `onStartLoad()` and `onLoad()` callbacks.


1. Set up a reusable component like so:
```
const StyledBG = styled(BackgroundImage)`
  /* Set base styling to whatever you want */
  height: 450px; 
  width: 100%;
  border: 1px solid rebeccapurple;

  /* Pseudoselector to grab "loading" class */
  &.loading {
    &::before,
    &::after {
      /* Apply the filter when "loading" class is enabled */
      filter: blur(15px);
    }
  }
`

const NewBgImage = ({ children, ...props }) => {
  const bgRef = useRef()

  return (
    <StyledBG
      ref={bgRef}
      onStartLoad={() => bgRef.current.selfRef.classList.toggle("loading")}
      onLoad={() => bgRef.current.selfRef.classList.toggle("loading")}
      {...props}
    >
      {children}
    </StyledBG>
  )
}

export default NewBgImage
```

2. Call the component, passing the required props.
```
<NewBgImage fluid={data.file.childImageSharp.fluid}>
  <h2>I'm a background image</h2>
</NewBgImage>
```

Hope that helps anyone else who was looking to do this.

**Comment by timhagn** [comment]
Hey @ardiewen,

great you found a solution! Would you perhaps wanna introduce it as a PR to the aforementioned paragraph in the READMEs of `gbi(-es5)`? Else I'm gonna plug it for the next version, awesome solution you've got there : )!

Best,

Tim.

**Comment by ardiewen** [comment]
Hey @timhagn, I'll fork and PR in the next day or two. Thanks again for your help!
