### ISSUE TITLE
 linear-gradient doesn't work with background-image plugin after implementing my sass styling

### ISSUE THREAD

**Issue by Abderrahmenla** [timhagn/gatsby-background-image#111]
## Description

linear-gradient doesn't work with background-image plugin after implementing my sass styling

### Steps to reproduce

https://github.com/Abderrahmenla/Scouting
clone/download it then npm install
### Expected result

the styling of the class header in the file sass/layout/header.scss should work with the linear-gradient

### Actual result

linear-gradient doesn't work
### Environment
System:
OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
Shell: 4.3.48 - /bin/bash
Binaries:
Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
npm: 6.14.3 - ~/.nvm/versions/node/v13.7.0/bin/npm
Languages:
Python: 2.7.12 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.92
Firefox: 75.0
npmPackages:
gatsby: ^2.20.23 => 2.20.23

gatsby-background-image: ^0.10.2 => 0.10.2
gatsby-image: ^2.3.3 => 2.3.3
gatsby-plugin-manifest: ^2.3.4 => 2.3.4
gatsby-plugin-playground: ^1.0.6 => 1.0.6
gatsby-plugin-react-helmet: ^3.2.3 => 3.2.3
gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
gatsby-plugin-sass: ^2.2.3 => 2.2.3
gatsby-plugin-sharp: ^2.5.5 => 2.5.5
gatsby-plugin-sitemap: ^2.3.3 => 2.3.3
gatsby-plugin-styled-components: ^3.2.2 => 3.2.2
gatsby-plugin-transition-link: ^1.18.0 => 1.18.0
gatsby-source-contentful: ^2.2.8 => 2.2.8
gatsby-source-filesystem: ^2.2.3 => 2.2.3
gatsby-transformer-sharp: ^2.4.5 => 2.4.5

npmGlobalPackages:
gatsby-cli: 2.11.11

**Comment by timhagn** [comment]
Hi @Abderrahmenla,

might you explain where you're heading at? You're setting `linear-gradient` styles directly on the Container component and although `gbi` would take the styling (it starts with `background-*`),
of course it gets overwritten by the used images. 
Should you want to use stacked images, have a look at [How to Use with Multiple Images](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#how-to-use-with-multiple-images).

Best,

Tim.

**Comment by Abderrahmenla** [comment]
HI @timhagn thanks for your apply, so much appreciated.
all I want is to apply my header styling, the styling in on _header.scss in the sass folder, I was importing the image in the sass folder (with the URL() function in the background-image property) the clip-path property works fine the only thing that doesn't work is the linear-gradient I've tried to add the !important and still doesn't work.and I want to use the gatsby-background-image plugin for optimization purpose but I don't know how to make it work

**Comment by Abderrahmenla** [comment]
guys I've solved it thanks to @timhagn gatsby-background-image treat linear gradient as an image (layer) you just need to see [How to Use with Multiple Images](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#how-to-use-with-multiple-images)
