### ISSUE TITLE
If image is in cache, there's still a blur-up transition when using multiple images.

### ISSUE THREAD

**Issue by chemicalkosek** [timhagn/gatsby-background-image#112]
## Description

When using multiple images as background, the blur-up transition still exists when the image is already in cache. That isn't the case when using a single background image.

Multi image, blur up exists with image in cache:
[https://multi.webjuice.pl/](https://multi.webjuice.pl/)
Single image, if image in cache, it loads instantly:
[https://single.webjuice.pl/](https://single.webjuice.pl/)
### Steps to reproduce

```
import React from 'react';
import { useStaticQuery, graphql } from 'gatsby';
import BackgroundImage from 'gatsby-background-image';

const Hero = () => {
  const data = useStaticQuery(
    graphql`
      query {
        file(relativePath: { eq: "shipyard.jpg" }) {
          childImageSharp {
            fluid(maxWidth: 2000) {
              ...GatsbyImageSharpFluid
            }
          }
        }
      }
    `
  );

  return (
    <div className="hero">
      <BackgroundImage
        style={{
          minHeight: '80vh',
          height: '80vh',
          display: 'flex',
          alignItems: 'center',
          padding: '2rem',
        }}
        // IF I UNCOMMENT THE FOLLOWING LINE 
        // AND COMMENT THE MULTI IMAGE LINE IT WORKS FINE
        // fluid={data.file.childImageSharp.fluid}
        fluid={[
          'linear-gradient(to right, #3b1b8d, rgba(4, 243, 67, 0.0))',
          data.file.childImageSharp.fluid,
        ]}
      >
        <h1>The right personnel is the key to your company's success</h1>
      </BackgroundImage>
    </div>
  );
};

export default Hero;
```

### Expected result

When image is in the cache, there should not be a delay with the blur-up animation.

### Actual result

Blur-up transition proceeds, even though the image is in the cache.

### Environment

```

  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
  npmPackages:
    gatsby: ^2.20.25 => 2.20.25 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-image: ^2.3.4 => 2.3.4 
    gatsby-plugin-manifest: ^2.3.5 => 2.3.5 
    gatsby-plugin-offline: ^3.1.4 => 3.1.4 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.2.4 => 3.2.4 
    gatsby-plugin-sass: ^2.2.4 => 2.2.4 
    gatsby-plugin-sharp: ^2.5.6 => 2.5.6 
    gatsby-plugin-typography: ^2.4.4 => 2.4.4 
    gatsby-source-filesystem: ^2.2.4 => 2.2.4 
    gatsby-transformer-sharp: ^2.4.6 => 2.4.6 
  npmGlobalPackages:
    gatsby-cli: 2.11.15
```

**Comment by timhagn** [comment]
Hi @chemicalkosek,

this one sadly is hard to tackle - especially as it doesn't seem to happen in Chrome/ium (tested on Linux & Windoze) & Edge. And FF is a bugger to debug "remotely" with ; ).
Already tried to approach it for #93, though as I'm not one for constant monologues, I let that one slide...

You (and anyone interested) may track my current progress in the [`gbitest`](https://github.com/timhagn/gatsby-background-image/tree/gbitest) branch (already wasted ~4h on it today, again -.-).
Any help or hints would be more than welcome : )!

Best,

Tim.

**Comment by chemicalkosek** [comment]
I mainly test on Chrome. It happens to me on Chrome (Windows, Linux, Android), Firefox (Windows, Linux). So you say that at this link: [https://multi.webjuice.pl/](https://multi.webjuice.pl/) it doesn't happen? I can definitely see the blur-up delay on subsequent refreshes (F5) and not only initial load. This doesn't happen on a single image background like here [https://single.webjuice.pl/](https://single.webjuice.pl/)

**Comment by chemicalkosek** [comment]
Ok, I also narrowed it down to this: If using two real images in the fluid array (png, jpg whatever) it works just as fine as in single image. But If I use linear-gradient (like I'm using in the example above), it breaks and we have the blur-up delay. Does that help?

**Comment by timhagn** [comment]
Mkay, we talked squarely past one another.
I guess your issue rather has to do with #92, but then, sorry to say, this is no issue of `gbi`.

You're probably rather lucky with your hosts "Cache-Control" headers in combination with your browser configuration - as usually a refresh of the page should look like your "broken" result as well, refresh destroys the `imageCache` and the browsers cache storage isn't accessible without conflicting with GDPR or suchlike.

For me, in fact, I saw no difference pertaining the blur-up in both your examples % ).
It just sounded like you had the problem of blur-up when changing routes (that's why I was irritated that none of your Links worked ; ).

The latter one is a bug, the first one is sadly the browsers design : /.
Maybe I'm gonna release a persistent cache with GDPR consent for Gatsby in the near future, but ftm. there's nothing I could do...

Best nevertheless,

Tim.

**Comment by chemicalkosek** [comment]
Ok so it looks like my long-time experience with F5 refreshing is blown away :) 
On this page [https://single.webjuice.pl/](https://single.webjuice.pl/) I can soft-refresh (F5) and I don't see the blur-up, so I thought the imageCache is not destroyed. On the other hand, I see the blur-up when revisiting this page by just typing its address, and not refreshing by F5. I think I'm just confused.

So if I'm understanding correctly, gatsby-image will load images only after all JS has been parsed, even if they are in cache?

Ok then, I will be closing this issue.

Anyway, thank you for your unusual, comprehensive and kind responses. Very much appreciated.

**Comment by chemicalkosek** [comment]
Sorry for reopening, but I have just made a quick site to make comparison with gatsby-image side by side.
[https://image.webjuice.pl/](https://image.webjuice.pl/)

<BackgroundImage/> on the left, <Img/> from gatsby-image on the right.
There is more delay on the left side, is that how it supposed to be? 
Is that because this background image comes from css and is executed later?

**Comment by timhagn** [comment]
Hi again, @chemicalkosek,

no need for apologies, I'm happy to help : ).

Pertaining the `imageCache`, that's just a `WeakMap` in `gatsby-image` & `gbi`, both.
The direct browser cache isn't accessible through JS & storage options like `localStorage` or suchlike would have to be used to make the cached images (only the URI is saved) persistent - which of course would have implications within GDPR or similar laws.
So sadly it ain't easily possible to forego the blur-up or traced SVG animations after a refresh : /.

*But you are able to control the transition period by tweaking the `durationFadeIn` prop.*
Alas, while `gatsby-image` has access to the native `picture` element & the browsers load-handling, which interrupts / speeds up the transitions, there's no such thing for the `background-*` styles (except using badly supported CSS props), so the transitions in `gbi` add up until the image(s) is / are loaded (see [line 265ff in `index.js`](https://github.com/timhagn/gatsby-background-image/blob/f83dc24d41d38cc0e4446a84b958390f1d9f97eb/packages/gatsby-background-image/src/index.js#L265)). And at the moment stacked strings like `linear-gradient` get interpreted as their own "images" and add one extra transition (which in your last examples case seems to be correct % ). That's the bug I was talking about, btw. ; ).

Hope this clears things up, a little : )!

Best,

Tim.

P.S.: Thanks for your many examples, after we were talking bout the same issue, they were quite helpful zoning in on the problems at hand : ).

**Comment by chemicalkosek** [comment]
:) Yes, following your answer I can confirm that the issue I was talking about is that

> stacked strings like linear-gradient get interpreted as their own "images" and add one extra transition 

which mistakenly looked for me like `gbi` didn't recognize images in cache and added the long blur-up delay.

I don't know whether I should close this issue or not, so I'm leaving it open for you to decide.
