### ISSUE TITLE
BackgroundImage not responding to css

### ISSUE THREAD

**Issue by arnelamo** [timhagn/gatsby-background-image#114]
## Summary
Hi. My background image does not take the whole height of the viewport, despite that I have 
it defined in my css. I have the image above a sticky navbar, that sticks to the top after you scroll down. So, I want the navbar to be just below the viewport and then stick it to the top when you scroll down. 

If i enter 'height: 100vh;' in the devtools inspector however, it does respond and set the correct height.

## CSS classes

The BackgroundImage css class:

```javascript
.masthead {
  width: 100%;
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  height: 100vh;
  margin: 0;
}
```

The Navbar css class:
```javascript
.navbar {
  background-color: $bg;
  border-bottom: 4px solid $secondary;
  user-select: none;
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  justify-content: flex-start;
  min-height: 50px;
}
````

### Environment 

 System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 72.0.2
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.0 => 2.21.0
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-plugin-manifest: ^2.4.1 => 2.4.1
    gatsby-plugin-netlify: ^2.3.0 => 2.3.0
    gatsby-plugin-offline: ^3.2.0 => 3.2.0
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-sass: ^2.3.0 => 2.3.0
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0
    gatsby-source-filesystem: ^2.3.0 => 2.3.0
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0
  npmGlobalPackages:
    gatsby-cli: 2.12.0

I'm sorry if this is a stupid question, and I would be happy if anyone could help me out.

**Comment by Alcas1** [comment]
I'm experiencing the same thing on all browsers

**Comment by timhagn** [comment]
Hi there @arnelamo  & @Alcas1,

well, the `background-image`s width & height depends on its content, as with any div or suchlike _container_ component.
For it to stretch on itself, one has to use `min-width & min-height`. Setting `width` or `height` in the devtools seemingly acts like these two.

Probably you both have found this out for yourselves in the meantime, sorry it took me so long to respond. May & June were packed with work for me & in other aspects just not my months % ).

But should this solve your issue, feel free to close it. Shouldn't it do, please give me some more code to work from : ).

Best,

Tim.
