### ISSUE TITLE
Background image with Webp also pulling back JPG

### ISSUE THREAD

**Issue by jf-home** [timhagn/gatsby-background-image#117]
## When pulling back image withWebp, JPG is also returned to the page
Let me start by saying how much I love this plug-in ...it's fantastic!

There seems to be an issue however when pulling images back in Webp format.  Not sure why, but the gatsby-background-image plug-in appears to be pulling back a JPG in addition to a Webp when a Webp format is requested (GraphQL fragment: ...GatsbyImageSharpFluid_withWebp).  This appears to be different behaviour to gatsby-image, in which just the Webp is returned when requesting Webp format.

The issue with returning the JPG in addition to the Webp is that it increases the page payload and hurts the performance of the page as a result.

### Steps to reproduce

Create a page that makes use of the gatsby-background-image plug-in and, through the GraphQL query that pulls back the image, append the "_withWebp" instruction: 

image {
          childImageSharp {
            fluid(maxWidth: 3000 quality: 80) {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }

View the resulting page in a browser i.e. Chrome, with dev tools open and on the "Network" tab.  Then Ctrl F5 and review all of the page artefacts that are listed.  You will see an entry for the Webp and also a corresponding JPG which, generally, is larger in size than the Webp.

### Expected result

I would expect only the Webp to be pulled back for browsers (such as Chrome) that support this file type.

### Actual result

Webp and unwanted JPG pulled back.

### Environment

Site currently deployed on Netlify: 
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.0.76 => 2.21.22
    gatsby-background-image: ^0.9.19 => 0.9.19
    gatsby-image: ^2.0.20 => 2.4.3
    gatsby-plugin-catch-links: ^2.3.2 => 2.3.2
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-manifest: ^2.0.9 => 2.4.2
    gatsby-plugin-netlify: ^2.3.5 => 2.3.5
    gatsby-plugin-netlify-cms: ^4.3.1 => 4.3.1
    gatsby-plugin-offline: ^2.0.16 => 2.2.10
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.0.2 => 3.3.1
    gatsby-plugin-recaptcha: ^1.0.5 => 1.0.5
    gatsby-plugin-sharp: ^2.0.14 => 2.6.2
    gatsby-plugin-sitemap: ^2.4.4 => 2.4.4
    gatsby-plugin-svgr: ^2.0.1 => 2.0.2
    gatsby-remark-images: ^3.3.3 => 3.3.3
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-contentful: ^2.3.7 => 2.3.7
    gatsby-source-filesystem: ^2.0.8 => 2.3.1
    gatsby-transformer-remark: ^2.8.7 => 2.8.7
    gatsby-transformer-sharp: ^2.1.8 => 2.5.2
  npmGlobalPackages:
    gatsby-cli: 2.12.24

![2020-06-16-gatsby-background-image-webp-jpg-issue](https://user-images.githubusercontent.com/49573557/84774761-36794200-afd6-11ea-9f06-1c3a4bfade2d.png)

**Comment by timhagn** [comment]
Hi @jf-home,

would you please first try if it happens with the latest version as well? We're at `v1.1.1` now.

Best,

Tim.

**Comment by jf-home** [comment]
Hi Tim, 

Ah - my sincere apologies - this doesn't appear to be an issue with version 1.1.1.   

Thank you for the steer on that - much appreciated!

Kind regards

**Comment by ahmadkhalaf1** [comment]
@timhagn Hi , i have v 1.1.2 and i also have this issue where JPG is also downloaded and show in network next to webp , i changed to v1.1.1 and issue still exist , can u please help? i am following same config as in this issue above . 

![image](https://user-images.githubusercontent.com/18447392/102346511-3ff06080-3f9f-11eb-9101-eb93ef2bba15.png)
