### ISSUE TITLE
NPM install has the js files in the `dist` subfolder rather than the root

### ISSUE THREAD

**Issue by johngrasty** [timhagn/gatsby-background-image#12]
Title says it all.

I drug the files out of the subfolder and it seems to work great. Thanks for the great plugin!

**Comment by timhagn** [comment]
Hi @johngrasty!

Mkay, strange, with neither `npm` nor `yarn` and `"main": "dist/index.js",` in `package.json` I've had a problem with the installation and usage in projects oO. 
Would you be so kind and give me a quick `gatsby info`? Example repo would be even better, of course, but not entirely necessary.
Definitely thnx for mentioning it, hope it doesn't spread ; ).

**Comment by johngrasty** [comment]
Hi @timhagn,

Thanks so much for the response. I will dig that out for you later today. I have quite a few meetings at the moment. 😀 And yes, I see that you have "main": `"dist/index.js"` in the `package.json`, so it shouldn't be an issue. Hmmm…

Thanks so much for the plugin though. It really works great in the setup I've got going on and saved me some trouble.

**Comment by timhagn** [comment]
Hi @johngrasty,

no problem, your issue definitely incentivized me having a deeper look at my bundle structure ^^.
Gonna dig into it and hope to have this quirks removed today : ).

That beside, thanks for the flowers - happy it and me could help you : )!

**Comment by r007** [comment]
Can't replicate it. Here's the file structure on my Ubuntu 18.10 (gatsby-background-image 0.2.4).

![File structure of gatsby-background-image](https://user-images.githubusercontent.com/78280/54359458-24468080-467c-11e9-819e-89dec204dc78.png)

**Comment by timhagn** [comment]
Hi @r007, 

thanks for joining in and trying to replicate this! Though the issue initially arose over 
`gatsby-background-image v0.2.5`, published yesterday, where I did some bugfixes and - more important - refactoring like moving the build to a dist folder.
If you could spare the time to try it with `0.2.5` and maybe the now cleaned up and just published `0.2.6` I'd be deeply grateful : )!

And @johngrasty, would you mind testing it with `0.2.6` - I'm now strictly following npm's own [package.json](https://github.com/npm/cli/blob/latest/package.json).

**Comment by r007** [comment]
@timhagn oh, sorry, my bad. Just updated to v0.2.6 and yes, all the images are in the dist folder now.

**Comment by johngrasty** [comment]
@timhagn  Hey, thanks for the help. Here's a bit more info along with my `gatsby info` at the bottom. I've tested this on two different machines with similar but probably not identical environments, and everything works fine in another repo I have which is running on version 0.2.3 of your plugin.

Here's where everything gets more interesting. I just checked `gatsby-background-image 0.2.6`, and it still fails, **but** if I move your plugin's folder to the local plugins folder, it works just fine with no changes to your setup. 

This gatsby issue seems to touch on this issue: https://github.com/gatsbyjs/gatsby/issues/5559


```
~/g/m/blog-starter> gatsby info

  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) M-5Y31 CPU @ 0.90GHz
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 8.12.0 - /opt/pkg/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.8.0 - ~/.npm-packages/bin/npm
  Languages:
    Python: 2.7.15 - /opt/pkg/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.32 => 2.1.32 
    gatsby-background-image: ^0.2.6 => 0.2.6 
    gatsby-cli: ^2.4.15 => 2.4.15 
    gatsby-image: ^2.0.33 => 2.0.33 
    gatsby-plugin-facebook-sdk: ^1.0.6 => 1.0.6 
    gatsby-plugin-feed: ^2.0.15 => 2.0.15 
    gatsby-plugin-google-analytics: ^2.0.17 => 2.0.17 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-postcss: ^2.0.6 => 2.0.6 
    gatsby-plugin-react-helmet: ^3.0.9 => 3.0.9 
    gatsby-plugin-remote-images: ^1.0.1 => 1.0.1 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.28 => 2.0.28 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-typography: ^2.2.10 => 2.2.10 
    gatsby-remark-copy-linked-files: ^2.0.10 => 2.0.10 
    gatsby-remark-images: ^3.0.9 => 3.0.9 
    gatsby-remark-prismjs: ^3.2.5 => 3.2.5 
    gatsby-remark-responsive-iframe: ^2.0.10 => 2.0.10 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.25 => 2.0.25 
    gatsby-source-graphql: ^2.0.14 => 2.0.14 
    gatsby-source-wordpress: ^3.0.42 => 3.0.45 
    gatsby-transformer-remark: ^2.3.3 => 2.3.3 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.12
```

**Comment by timhagn** [comment]
Mkay, then let's put em back in the main folder - though imho ignoring conventions on npm isn't the greatest move on their side (or not having such cases in the docs ; ).

**Comment by timhagn** [comment]
#done - would you mind testing `0.2.62` @johngrasty? @r007, too, if you would be so kind : ).

**Comment by johngrasty** [comment]
Yep. `0.2.62`works for me.

**Comment by timhagn** [comment]
@johngrasty Nice : )! But still strange that it worked on Linux, but ceases to do so on macOS oO.
Anyway, might this be seen as closed?

**Comment by johngrasty** [comment]
Yes, we can close this. Even more interesting to me than the platform difference is that the normal conventions are respected when the plugin is in the local plugins folder in Gatsby but not when installed as an npm package!

**Comment by timhagn** [comment]
Don't know, maybe has something to do with filesystem searches or notifications (e.g. I see
`fsevents` popping up everywhere and it only seems to do some job on macOS).
Internally Gatsby might have solved it another way than npm / yarn / etc. do 
- but that's just a wild guess ^^.
As long as it's working now, I'm happy, thanks again for bringing this up : )!
