### ISSUE TITLE
Multiple Images bug - tracedSVG issue back again

### ISSUE THREAD

**Issue by alec-francis** [timhagn/gatsby-background-image#121]
Hi all,

FYI, this issue re-surfaced https://github.com/timhagn/gatsby-background-image/issues/101

I got the tracedSVG error again. I was running version 1.1.1

I just rolled back to version 0.10.2 and can confirm that the issue didn't happen with this version.

Cheers,

Alec

**Comment by timhagn** [comment]
Hi @alec-francis,

would you mind giving me your `gatsby info` & a reproduction case? Cause I wasn't able to reproduce it with the current `gbitest` & its image-stack page.

Best,

Tim.

**Comment by alec-francis** [comment]
Hi Tim,

I re-installed 1.1.1 and this time tried `gatsby clean` before running `gatsby develop`. The issue was resolved.

Thanks for your great work on this repository by the way!

Cheers,

Alec
