### ISSUE TITLE
Please add a demo page

### ISSUE THREAD

**Issue by balibebas** [timhagn/gatsby-background-image#123]
I saw in #30 you were were planning to add an online demo. This is _highly_ appreciated given this is a graphical component and having a demo will save individuals time and effort locating, cloning, running and examining the example locally just to get a look at what a single-click on a demo could provide.

If you need help getting Vercel set-up please let me know and I'll give you a hand.

**Comment by timhagn** [comment]
Hi @balibebas,

would love to add one, but am currently very sparse on time cause of client work.
But postponed isn't canceled, so stay tuned. 
And nope, I wouldn't need help setting Zeit/Vercel up, but thnx for the offer ; ).

Best,

Tim.

**Comment by balibebas** [comment]
Always assume good intentions. A screenshot or GIF in the readme would work too. Happy belated birthday.
