### ISSUE TITLE
Background Image Animation not working

### ISSUE THREAD

**Issue by abdullahe** [timhagn/gatsby-background-image#124]
## Summary
Hi,
I'm using gatsby-background-image plugin on a site with Bulma. For the hero section, I want to animate the image. But the animation does not work. If I switch to ```<div>``` animation works as intended. Am I doing something wrong? 

## Relevant information

index.js template:
```
<BackgroundImage
        Tag="section"
        className="hero is-fullheight is-paddingless is-marginless herobackground"
        fluid={bannerimage.childImageSharp.fluid}
        style={{
          backgroundSize: `cover`,
          backgroundAttachment: `local, scroll`,
          maxWidth: "100vw",
          maxHeight: "100vh",
          minHeight: "100vh",
        }}
        //* for the lighthouse score *//
        loading="eager"
        fadeIn={false}
      > {children}
</BackgroundImage>
```

Relevant sass:
```
.herobackground
  background-size: 200%
  background-position: center
  background-repeat: no-repeat 
  background-attachment: scroll
  animation: 10s ease-out 1 both animatedBackground !important


@keyframes animatedBackground 
  0%
    background-size: 200%
    background-position: center
  100%
    background-size: 100%
```

**Comment by timhagn** [comment]
Hi @abdullahe,

you should probably only have to target the `before` & `after` pseudo-elements for your animations, I guess, but it's hard to say, have never tried it. But I think the semi-automatic initial `backrgound-*` style grabbing won't work, when it's done in SASS...

Interesting but murky waters, this...

Best (& intrigued),

Tim.

**Comment by abdullahe** [comment]
Thanks a lot  @timhagn!

Great plugin by the way. Cheers.
