### ISSUE TITLE
How to disable blur-up effect

### ISSUE THREAD

**Issue by mfanuzzi** [timhagn/gatsby-background-image#126]
Hi, I'm unable to figure out how to disable the blur-up effect. I can make it faster or different thru CSS, but there's no way that I see to completely remove it, or replace it with, for example, a solid color.

Or is this more the domain of a `gatsby-transformer-sharp` config?

**Comment by mfanuzzi** [comment]
the answer is, of course, to use in your GraphQL:
`...GatsbyImageSharpFluid_withWebp_noBase64`
🤦‍♂️

**Comment by timhagn** [comment]
Great you could figure that out on your own : ).

Best,

Tim.
