### ISSUE TITLE
Incompatibility with the Preact plugin

### ISSUE THREAD

**Issue by timuster** [timhagn/gatsby-background-image#127]
## Description

The background image shows up really blurred when the Gatsby Preact plugin is active. This behavior does not occur for other images loaded via gatsby-image. 

### Steps to reproduce

1. Add a background image and load the site
2. Enable the Preact plugin, as directed in the official docs: https://www.gatsbyjs.com/plugins/gatsby-plugin-preact/ 
3. Build the gatsby site again [ background image is now extremely blurred ]

### Expected result

Like Gatsby Image, the 'gatsby background image' plugin should not behave differently when the Preact plugin is enabled.

### Environment

```

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 80.0.1
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-cli: ^2.12.89 => 2.12.89 
    gatsby-image: ^2.4.12 => 2.4.12 
    gatsby-plugin-google-gtag: ^2.1.10 => 2.1.10 
    gatsby-plugin-preact: ^4.0.10 => 4.0.10 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sass: ^2.3.10 => 2.3.10 
    gatsby-plugin-sharp: ^2.6.17 => 2.6.17 
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10 
    gatsby-source-filesystem: ^2.3.18 => 2.3.18 
    gatsby-transformer-sharp: ^2.5.10 => 2.5.10 
  npmGlobalPackages:
    gatsby-cli: 2.12.51

```

**Comment by timhagn** [comment]
Hi @timuster,

as `gatsby-background-image` never claimed to work with preact (it was developed for react.js, after all) - and I've never used preact myself, you definitely should provide a reproduction case. Perhaps first try it with `gbi v1.1.2` with small changes, but I can't provide much help atm without a reproduction - and to make matters worse, I'm ill right now and just couldn't sleep, that's the only reason I'm answered so soon : /.

Best anyways,

Tim.
