### ISSUE TITLE
2nd image doesnt show when i resize the browser unless i refresh the page

### ISSUE THREAD

**Issue by karltud123** [timhagn/gatsby-background-image#129]
I have create div with 2 image stack in it. One is for desktop image , the other one is for mobile image

The image works fine if on page load on each size but if i come from desktop size then i resize the browser to mobile size. The image doesnt show, 

ANy way to solve this?

THank you

**Comment by karltud123** [comment]
Issue only happens on firefox browser

**Comment by lezan** [comment]
I have a similar issue on Mozilla Firefox. Changing size of window does not cause a new request for a new image with the right size (I check it on network panel of dev tool). I have no problem with gatsby-image, so maybe could be a gatsby-background-image related issue.

Fetch data
```
configHome: file(relativePath: { eq: "home/home_intro_background.jpg" }) {
	childImageSharp {
		fluid(maxWidth: 1920) {
			...GatsbyImageSharpFluid_withWebp
			...GatsbyImageSharpFluidLimitPresentationSize
		}
	}
}
```

Use image
```
<BackgroundImage
	className="intro intro-home pb-4"
	fluid={configHome.childImageSharp.fluid}
>
```

**Comment by karltud123** [comment]
> 
> 
> I have a similar issue on Mozilla Firefox. Changing size of window does not cause a new request for a new image with the right size (I check it on network panel of dev tool). I have no problem with gatsby-image, so maybe could be a gatsby-background-image related issue.
> 
> Fetch data
> 
> ```
> configHome: file(relativePath: { eq: "home/home_intro_background.jpg" }) {
> 	childImageSharp {
> 		fluid(maxWidth: 1920) {
> 			...GatsbyImageSharpFluid_withWebp
> 			...GatsbyImageSharpFluidLimitPresentationSize
> 		}
> 	}
> }
> ```
> 
> Use image
> 
> ```
> <BackgroundImage
> 	className="intro intro-home pb-4"
> 	fluid={configHome.childImageSharp.fluid}
> >
> ```

Does yours also happening on safari and firefox only as well?

**Comment by lezan** [comment]
> 
> 
> > I have a similar issue on Mozilla Firefox. Changing size of window does not cause a new request for a new image with the right size (I check it on network panel of dev tool). I have no problem with gatsby-image, so maybe could be a gatsby-background-image related issue.
> > Fetch data
> > ```
> > configHome: file(relativePath: { eq: "home/home_intro_background.jpg" }) {
> > 	childImageSharp {
> > 		fluid(maxWidth: 1920) {
> > 			...GatsbyImageSharpFluid_withWebp
> > 			...GatsbyImageSharpFluidLimitPresentationSize
> > 		}
> > 	}
> > }
> > ```
> > 
> > 
> > Use image
> > ```
> > <BackgroundImage
> > 	className="intro intro-home pb-4"
> > 	fluid={configHome.childImageSharp.fluid}
> > >
> > ```
> 
> Does yours also happening on safari and firefox only as well?

No idea for safari, but I am experience it with Mozilla Firefox.
