### ISSUE TITLE
gatsby-background-image flickering and reshaping on scroll

### ISSUE THREAD

**Issue by Guiguerreiro39** [timhagn/gatsby-background-image#130]
## Summary

I am using the gatsby-background-image plugin on my background images but, on mobile, when scrolling up and down in a section with a background image is seems that the image is reshaping and flickering making it annoying and sometimes slow. My background images are set to fixed and this can cause that issue perhaps.

## Relevant information

You can check out this issue on this link [https://guilherme-guerreiro.netlify.app/](url)
To reproduce it, just be on a mobile phone and try scrolling up and down a bit faster than usual on the background image sections.

This issue does not occur when I'm testing the responsiveness on my laptop browser but everytime I tried it on a phone it happens.

I was hoping someone could help me out to solve this issue? I've tryed looking online but nothing solved it yet..

**Comment by timhagn** [comment]
Hi @Guiguerreiro39,

could you tell me, on which Device you noticed this behavior? As I just tested it on your site & can't replicate it on my phone...

Best,

Tim.
P.S.: Perhaps a reproduction video could help pinpointing it as well : ).

**Comment by peabodys** [comment]
I am also experiencing this issue. It only happens when viewing the site on my iPhone 8 Plus. 

[https://romantic-kilby-1fe56a.netlify.app/](https://romantic-kilby-1fe56a.netlify.app/)

**Comment by peabodys** [comment]
I've just tested further, and it seems to only occur in Chrome on the iPhone. Safari rendered it perfectly.
