### ISSUE TITLE
Blur up effect not working

### ISSUE THREAD

**Issue by nboliver** [timhagn/gatsby-background-image#134]
## Description

The blur up effect is not working. Tried changing `fadeIn` to all documented options.

### Steps to reproduce

Installed gatsby-background-image and passed the component a `fluid` prop. Background shows abruptly with no fade, regardless of its position above / below the fold.

### Expected result

Image should blur up.

### Actual result

Image does not blur up.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 78.0.2
    Safari: 13.1.3
  npmPackages:
    gatsby: ^2.18.17 => 2.24.67 
    gatsby-image: ^2.2.37 => 2.4.20 
    gatsby-plugin-create-client-paths: ^2.3.10 => 2.3.12 
    gatsby-plugin-google-analytics: ^2.1.31 => 2.3.15 
    gatsby-plugin-layout: ^1.1.18 => 1.3.12 
    gatsby-plugin-manifest: ^2.2.34 => 2.4.33 
    gatsby-plugin-offline: ^3.0.30 => 3.2.30 
    gatsby-plugin-react-helmet: ^3.1.18 => 3.3.12 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sass: ^2.1.26 => 2.3.14 
    gatsby-plugin-sharp: ^2.3.10 => 2.6.38 
    gatsby-source-filesystem: ^2.1.43 => 2.3.32 
    gatsby-source-sanity: ^6.0.4 => 6.0.4 
    gatsby-transformer-sharp: ^2.3.9 => 2.5.16 
  npmGlobalPackages:
    gatsby-cli: 2.12.65
```
Note that images are sourced from `gatsby-source-sanity`, which is compatible with gatsby-image (and the same images are fading in as expected when using gatsby-image directly.

**Comment by timhagn** [comment]
Hi @nboliver,

would you be able to provide a reproduction case?

Best,

Tim.

P.S.: from your `gatsby info` `gbi` wouldn't be installed at all ; ).
