### ISSUE TITLE
How can I use this with styletron and add breakpoints?

### ISSUE THREAD

**Issue by tunztunztunz** [timhagn/gatsby-background-image#139]
## Summary

I'm trying to use Styletron to add some style breakpoints that will change the backgroundSize, but the breakpoints are being ignored.

Below is the component and styles I am trying to use. It ignored any breakpoint I use, but will use the other css there. Is there a way to get this working?

```
<BackgroundImage
      Tag={`section`}
      className={css({
        [`@media screen and (min-width: ${theme.breakpoints.large}px)`]: {
          backgroundSize: "100vw 20%"
        },
        backgroundSize: "100vw 58%",
        backgroundPosition: "top",
        backgroundRepeat: "no-repeat",
        minHeight: "100vh",
        minWidth: "100vw"
      })}
      id={`media-test`}
      fluid={backgroundImage}
    >
```

`package.json`: N/A

**Comment by timhagn** [comment]
Hi @tunztunztunz,

that sadly won't work - unless you could target the pseudo-elements with styletron (have never worked with it) : /.
(The "magic" happens in the `:before & :after` pseudo-elements)

Best,

Tim.
