### ISSUE TITLE
DOMException: "The operation is insecure."

### ISSUE THREAD

**Issue by r007** [timhagn/gatsby-background-image#14]
Hi @timhagn 

I have a strange issue which I'm trying to solve right now. And it's probably somehow related to CORS. There are tons of warnings in console (Firefox, latest version):

```
Unable to read stylesheet rules for null DOMException: "The operation is insecure."
Unable to read stylesheet rules for null DOMException: "The operation is insecure."
Unable to read stylesheet rules for null DOMException: "The operation is insecure."
Unable to read stylesheet rules for null DOMException: "The operation is insecure."
```
Here's how I use this plugin:

```js
const HeroContainer = styled(BackgroundImage)`
  color: #ffffff;
  font-family: ${font('effra')};
  height: calc(100vh - 4em);
  margin-left: auto;
  margin-right: auto;
  position: relative;
  overflow: hidden;

  @media (max-width: ${mq.max[720]}) {
    max-height: 592px;
  }
`;

HeroContainer.defaultProps = {};

const HeroBlock = ({ children, image }) => (
  <HeroContainer Tag="section" className="HeroBlock" fluid={image}>
      {children}
  </HeroContainer>
);`;
```
If I remove custom styled styles, there is no changes at all. Warnings are still there. And here's how I query images:
```js
export const query = graphql`
  query getHomepageImages {
    HeroBackground: file(relativePath: { eq: "images/wallpaperocius-768x432.jpg" }) {
      childImageSharp {
        fluid(quality: 90, maxWidth: 1200) {
          ...GatsbyImageSharpFluid_withWebp
        }
      }
    }
  }
`;
```
I'm wondering, what could be wrong? Any ideas?

Sergey

**Comment by r007** [comment]
Solved this mystery! Turns out it's because function in backgroundUtils.js:15 iterates through all loaded stylesheets, including browser extensions. Read more about in on StackOverflow: [Uncaught DOMException: Failed to read the 'rules' property from 'CSSStyleSheet'](https://stackoverflow.com/questions/49161159/uncaught-domexception-failed-to-read-the-rules-property-from-cssstylesheet)

Disabled all my browser extensions and warnings are gone. Can you refactor this part, please?

**Comment by timhagn** [comment]
Hi @r007,

ah, FF seems to have integrated this finally - this issue already came up on Chrome in #6.
The warnings you're seeing are only `console.debug()` calls in the `catch` part of a `try .. catch` block around the stylesheet iteration (here)[https://github.com/timhagn/gatsby-background-image/blob/424127b7ef69291e745da3330f2957d0342e0f58/src/BackgroundUtils.js#L16], but as you're the second to mention this as a bug I probably should get them out... ^^.

**Comment by r007** [comment]
@timhagn no, it's fine. Just updated 0.2.4 ➡️ 0.2.6 and all these warning are gone. Good job. But now I see a couple more: 

```
Error getting opacity from style prop: styledProps.style is undefined
```
Only a couple of them showing up. StyleUtils.js:22

```js
/**
 * Prevent possible stacking order mismatch with opacity "hack".
 *
 * @param props
 * @return {Object}
 */
const fixOpacity = props => {
  let styledProps = Object.assign({}, props);

  try {
    if (styledProps.style.opacity) {
      if (isNaN(styledProps.style.opacity) || styledProps.style.opacity > .99) {
        styledProps.style.opacity = .99;
      }
    }
  } catch (e) {
    console.debug('Error getting opacity from style prop: ', e.message);
  }

  return styledProps;
};
```

**Comment by timhagn** [comment]
That one came with #8 - I should check for `styledProps.style` beforehand % ).

**Comment by petrpacas** [comment]
Just letting you guys know I'm having the opacity errors as well.

**Comment by timhagn** [comment]
Just published `0.2.61`, removing the `console.debug()` calls.

**Comment by r007** [comment]
@timhagn yes, they are gone. Awesome, thanks!

**Comment by timhagn** [comment]
@r007 Great : )! Would you want to do the honor of closing this issue, or shall I? 
Btw. with (hopefully solving) issue #12 we're now at `0.2.62` ^^.

**Comment by r007** [comment]
Sure, thanks! :)
