### ISSUE TITLE
The "fixed" and "fluid" resolvers are now deprecated.

### ISSUE THREAD

**Issue by SrJuggernaut** [timhagn/gatsby-background-image#147]
## Summary

It could be useful to migrate to the new gatsby model to display images

### Basic example
```jsx
<BackgroundImage
      Tag={`section`}
      id={`test`}
      className={className}
      image={data?.avatar?.childImageSharp?.gatsbyImageData}
    >
```

**Comment by joernroeder** [comment]
@SrJuggernaut see https://github.com/timhagn/gatsby-background-image/issues/141 for a short term fix

**Comment by timhagn** [comment]
Hi @SrJuggernaut & @joernroeder!

Closing this in favor of the mentioned #141 as an umbrella Issue (thanks for mentioning it, @joernroeder! : ).

Best,

Tim.
