### ISSUE TITLE
A blank background is briefly shown before the placeholder is rendered

### ISSUE THREAD

**Issue by matthewkwong2** [timhagn/gatsby-background-image#148]
## Description

As shown in the following image, when the page is first rendered, a blank background is displayed before the blurred placeholder takes place. **Note, the issue only appears in the production build.**
![image](https://user-images.githubusercontent.com/32725014/110409095-b04fdf00-80c1-11eb-9f4c-b3074cb0865f.png)

### Possible cause
I noticed the placeholder is not embedded in the inlined CSS. Instead, it is loaded from a JSON file. Since the browser loads the HTML first before loading the JSON files (even with preload), this might be the reason behind it.

### Steps to reproduce

A basic sample given in the guide is enough to reproduce the issue:
https://www.gatsbyjs.com/plugins/gatsby-background-image/#how-to-use

### Expected result

The placeholder (blurred, trace svg) should be rendered as soon as the page is displayed.

### Actual result

There is a slight delay between the page is displayed and the placeholder is rendered.

### Environment

````
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 15.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1
  Browsers:
    Chrome: 81.0.4044.113
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^3.0.3 => 3.0.3 
    gatsby-background-image: ^1.4.1 => 1.4.1 
    gatsby-plugin-emotion: ^6.0.0 => 6.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0 
    gatsby-plugin-preconnect: ^1.2.0 => 1.2.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.20 => 1.1.20 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0

````

**Comment by timhagn** [comment]
Hi @matthewkwong2!

This ain't easy to tackle, as it's caused by the need to prevent flashing of the preview images on page changes.
So it's either smooth page transitions (no preset preview images in `style`) or flickering but directly shown : /.
Or could you think of anything?

Best,

Tim.

**Comment by justinkneff** [comment]
I still have this issue too. Is the `placeholder: BLURRED` supposed to be a part of this graphql request?

**Comment by justinkneff** [comment]
@timhagn This seems to be related to the wrapping element not using the data on the element. When using gbimage-bridge I still get this issue.
Before using gbimage-bridge the `Pseudo ::before element` has the style which contains the `background-image:url(data:image/jpeg:base64....` and if you go into developer tools and disable the `::after element` image size it defaults to this blurred image.
After using the gbimage-bridge the `Pseudo ::before element` does not contain the `background-image:url...` content.
Is there a way to remove any delay before the placeholder image is placed?

**Comment by justinkneff** [comment]
Pretty sure there is an issue with the gatsby-background-image code not parsing the pseudoBefore
If you look at this code and the expected UI it has nothing rendering for the pseudoBefore. I never see the backgroundStyles or other properties applied to the returned styled here. 
https://github.com/timhagn/gatsby-background-image/blob/15165233fb32129ecebd41e4b9fd2e315e9d2ae1/packages/gatsby-background-image/src/lib/StyleCreation.js#L115
