### ISSUE TITLE
no background image on gatsby build

### ISSUE THREAD

**Issue by nerdess** [timhagn/gatsby-background-image#152]
## Summary

Background images not showing in build :(

## Relevant information

I recently switched from `gatsby-image` to `gatsby-plugin-image`. I am including my background images using `gbimage-bridge`, thee code is pretty straightforward:

`
<BgImage image={gatsbyImageData}> {children} </BgImage>
`

When running `gatsby develop` all works fine, I get a Background Image. But when I am using `gatsby build` no image gets displayed.

Here is the different source code that gets generated:

**Gatsby develop, all good**

![develop](https://user-images.githubusercontent.com/711925/111511415-ff93b080-874e-11eb-8d76-d282ddb3f3ef.png)

**Gatsby build, not so good, the background image is missing**

![build](https://user-images.githubusercontent.com/711925/111511520-1f2ad900-874f-11eb-9f64-6b9d3838e110.png)

All the other normal images that are not served through `<BgImage>` are fine.

Any help would be great!

**Comment by nerdess** [comment]
the odd thing: the images are inside the  /public/static folder so the  assets are there. they just don't get referenced in the CSS generated by the `bgImage`component.

so e.g. this asset which should be displayed as background image is available in the /public/static folder:

![Bildschirmfoto 2021-03-18 um 14 19 16](https://user-images.githubusercontent.com/711925/111632839-2d333500-87f5-11eb-97f3-7fc65554447e.png)

**Comment by timhagn** [comment]
Hi @nerdess,

do you talk about the initial rendering in the created `.html` files? Then it's probably a duplicate to #148 or at least explained there.

**Comment by timhagn** [comment]
Hi @nerdess,

been there, had that ^^. Great you could solve it!

Best,

Tim.

**Comment by MadalitsoNyemba** [comment]
@nerdess , I followed what you did but still getting no image after build.
