### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by thevangelist** [timhagn/gatsby-background-image#156]
Code example in https://www.gatsbyjs.com/plugins/gatsby-background-image/#gatsby-3--gatsby-plugin-image is not working:

`GatsbyImage is not defined react/jsx-no-undef`

**Comment by timhagn** [comment]
Got rectified by #157 : )!

**Comment by timhagn** [comment]
Just released `v1.5.3` for it. Feel free to close this issue : ).

Best, 

Tim.

**Comment by timhagn** [comment]
As this is solved, I'm closing it.
