### ISSUE TITLE
BgImage not rerendering with updated prop 

### ISSUE THREAD

**Issue by bjrnschmdt** [timhagn/gatsby-background-image#165]
Hi there,

when I use the `BgImage` wrapper component it does not rerender when props get updated. 

## Description

For example if I want to toggle the visibility of the `BgImage` wrapper component by changing the `className` with a `useState` hook the component does not render the component with the new `className`.

### Steps to reproduce

```
import React, { useState } from 'react';
import { getImage } from 'gatsby-plugin-image';
import { BgImage } from 'gbimage-bridge';

const HeroImage = ({ image }) => {
	const [heroVisibility, setHeroVisibility] = useState(true);
	const isVisible = heroVisibility ? 'visible' : 'hidden';

	const pluginImage = getImage(image);

	useEffect(() => {
		//some logic to setHeroVisibility
	});

	return (
		<BgImage
			Tag="div"
			image={pluginImage}
			className={isVisible}
		>
			//some jsx
		</BgImage>
	);
};

```

### Expected result

I expect the component to have the updated `className` on rerender when the State changes.

### Actual result

No change in the `className` after rerender when State changes.

### Comment

I will try to replicate the issue with gbitest but I thought maybe there is a quick answer to the issue.

Could it be related to this issue #135? 

Thanks a lot for your help! And thank you for your work on this Plugin which is in my opinion very much needed. :-)

**Comment by timhagn** [comment]
Hi @bjrnschmdt, 

have you read the README ; )? This should cover what you intended: [Passed Props for styled-components and suchlike](https://github.com/timhagn/gatsby-background-image/tree/main/packages/gatsby-background-image#passed-props-for-styled-components-and-suchlike).

Best,

Tim.

**Comment by bjrnschmdt** [comment]
Hi @timhagn ,

thanks a lot for your reply! I must have read it over. Sorry for not seeing this and thank you for pointing me to the right spot in the readme.

Again thanks a lot and all the best
Björn

**Comment by timhagn** [comment]
Hi @bjrnschmdt,

no problem at all, you're welcome : ). Sorry from my side for taking so long to reply, am currently swamped with work % ).

All the best to you,

Tim.
