### ISSUE TITLE
Provide compatibility with Gatsby v4

### ISSUE THREAD

**Issue by Vacilando** [timhagn/gatsby-background-image#168]
This plugin currently does not install under Gatsby v4.

```
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^2.0.0 || ^3.0.0" from gatsby-background-image@1.5.3
npm ERR! node_modules/gatsby-background-image
npm ERR!   gatsby-background-image@"^1.*" from the root project
```

**Comment by Vacilando** [comment]
Can we please reopen this. This ticket is clearly necessary for the future of this plugin, there are 8 users who've indicated they support the idea, and I'm sure there are more. 

While it's understandable that Tim cannot do everything right away, it does not mean tickets should be just closed.

**Comment by timhagn** [comment]
Hi there,

am currently flooded with work and to be honest mostly working with next.js. Probably have set the GH action a little too eager to close issues... Will try to add `|| ^4.0` next week to package.json.

Best,

Tim.

**Comment by timhagn** [comment]
Hi there,

as @garbledTech provided a PR for it I merged in both open ones & just publishes `gbi(-es5)@v1.6.0` & `gbimage-bridge@0.2.0`.
Please let me know if it now works with Gatsby 4 : ).

Best,

Tim.

**Comment by Vacilando** [comment]
Installs and works flawlessly with Gatsby v4 now. Thanks!
