### ISSUE TITLE
Issues with gbimage-bridge

### ISSUE THREAD

**Issue by JonathinK** [timhagn/gatsby-background-image#170]
## Description
Hello there,
I am here because i can't seem to find any solutions to this problem. In short with gatsby v3 the gatsby-background-image and gbimage-bridge worked flawlessly and now with the v4 update nothing works at all. Gatsby-image-background installs perfectly fine but gbimage-bridge throws a  list of errors. Forcing the install is useless as it does nothing and still doesn't work.
Is anyone else experiencing this as well or am I just crazy and a really bad developer lol. I removed both the dependancies as they weren't useful because they didn't work.

### Expected result
Working plugin.

### Actual result
The errors that were being thrown were......
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-starter-default@0.1.0
npm ERR! Found: gatsby-plugin-image@2.4.0
npm ERR! node_modules/gatsby-plugin-image
npm ERR!   gatsby-plugin-image@"^2.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby-plugin-image@"^1.0.1" from gbimage-bridge@0.2.0
npm ERR! node_modules/gbimage-bridge
npm ERR!   gbimage-bridge@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Environment
 System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    npm: 7.21.1 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 91.0.2
    Safari: 15.1
  npmPackages:
    gatsby: ^4.1.3 => 4.1.3
    gatsby-plugin-gatsby-cloud: ^4.1.1 => 4.1.1
    gatsby-plugin-google-analytics: ^4.1.0 => 4.1.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-google-tagmanager: ^4.1.1 => 4.1.1
    gatsby-plugin-image: ^2.4.0 => 2.4.0
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2
    gatsby-plugin-manifest: ^4.1.2 => 4.1.2
    gatsby-plugin-offline: ^5.1.2 => 5.1.2
    gatsby-plugin-react-helmet: ^5.1.0 => 5.1.0
    gatsby-plugin-robots-txt: ^1.6.14 => 1.6.14
    gatsby-plugin-sharp: ^4.1.2 => 4.1.2
    gatsby-plugin-sitemap: ^5.1.1 => 5.1.1
    gatsby-plugin-styled-components: ^5.1.0 => 5.1.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^4.1.1 => 4.1.1
    gatsby-transformer-sharp: ^4.1.0 => 4.1.0
  npmGlobalPackages:
    gatsby-cli: 4.4.0
    gatsby: 4.3.0

**Comment by timhagn** [comment]
Hi @JonathinK!

Fixed the peer dependencies in the just published `gbimage-bridge@v0.2.1`, would you care to try it?
Happy Holidays!

Best,

Tim.

**Comment by JonathinK** [comment]
Absolutely would love to.

**Comment by timhagn** [comment]
When it works, feel free to close the issue : ).
And no godness required, thanks for the error msgs ^^.

**Comment by JonathinK** [comment]
lol. No problem.  =)
