### ISSUE TITLE
Does not work in React Storybook

### ISSUE THREAD

**Issue by brianecook** [timhagn/gatsby-background-image#174]
## Description

Background image is not working in React storybook. Throws an error "can't access property "includes", r[0] is undefined".

![image](https://user-images.githubusercontent.com/6539449/152444081-fc6f4a22-b6c2-46e3-8f38-1f25f77f6dbf.png)

### Environment

System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 15.0
  npmPackages:
    gatsby: ^4.4.0 => 4.4.0
    gatsby-background-image: ^1.6.0 => 1.6.0
    gatsby-plugin-contentful-optional-fields: ^2.2.2 => 2.2.2
    gatsby-plugin-gatsby-cloud: ^4.4.0 => 4.4.0
    gatsby-plugin-google-gtag: ^4.4.0 => 4.4.0
    gatsby-plugin-image: ^2.4.0 => 2.4.0
    gatsby-plugin-react-helmet: ^5.4.0 => 5.4.0
    gatsby-plugin-root-import: ^2.0.8 => 2.0.8
    gatsby-plugin-sharp: ^4.4.0 => 4.4.0
    gatsby-plugin-sitemap: ^5.4.0 => 5.4.0
    gatsby-plugin-styled-components: ^5.4.0 => 5.4.0
    gatsby-source-contentful: ^7.2.0 => 7.2.0
    gatsby-source-filesystem: ^4.4.0 => 4.4.0
    gatsby-source-shopify: ^6.4.0 => 6.4.0
    gatsby-transformer-sharp: ^4.4.0 => 4.4.0

**Comment by YungTosti** [comment]
We're having the same issue. Please re-open.

**Comment by danychi** [comment]
Same issue here
