### ISSUE TITLE
Upgrade gbimage-bridge to React 18

### ISSUE THREAD

**Issue by AlexCherrypi** [timhagn/gatsby-background-image#176]
## Summary

I would very much appreciate a bump of gbimage-bridge to React 18 as staying up to date is necessary to provide a usable plugin.

### Motivation

Why should this be supported?  Because it makes life much easier when having a lot of plugins installed to stay up to date with all dependencies.

**Comment by dmorda** [comment]
+1 for this one, I've been getting all too used to appending `--legacy-peer-deps`.

**Comment by timhagn** [comment]
Just published `gbimage-bridge@v0.2.2` with #177 merged in.
