### ISSUE TITLE
Can I pass ID to the component?

### ISSUE THREAD

**Issue by smartdreams** [timhagn/gatsby-background-image#21]
Hi,

How do I pass "id" to this component? I have a section to display background image but it also requires to pass the html property "id" since external CSS is using ID. I tried using/wrapping with HOC but "id" didn't show up.

`
   

     const hoc = (WrappedComponent)=>(props)=>{
    
         return (
            <WrappedComponent {...props} id={props.id}>
            </WrappedComponent>
         )
     }

    const TestHoc = hoc(BackgroundImage)

    const Banner = (props) => (<div>
    
    <TestHoc Tag="section" id="banner"
                           className="major"
                           fluid={props.bgImage}
                           backgroundColor={`#040e18`}>
        <h1>Hello gatsby-background-image</h1>
    </TestHoc>     .......

`

**Comment by smartdreams** [comment]
Sure thing.

 Happy anniversary!

**Comment by timhagn** [comment]
Hi @smartdreams!
Thanks to @davebra's already merged in PR, your issue should be solved,
we now have an `id` prop and current release is `0.2.8-beta` : ).

And thanks for the nice anniversary wishes, was a great evening / night : )!

**Comment by timhagn** [comment]
Hi @smartdreams!

Did you already get the chance to test `0.2.8-beta` so we might close this issue?

Thanks in advance,

Tim.

**Comment by smartdreams** [comment]
It works. Thanks so much!
