### ISSUE TITLE
[Question] Possible to use with external sources?

### ISSUE THREAD

**Issue by MatteoGioioso** [timhagn/gatsby-background-image#27]
Is it possible to use the component with external image sources? Or simply passing a plain url?

**Comment by timhagn** [comment]
Well you could probably do this, you'd just have to replicate the `fluid` or `fixed` objects, like I have done in the tests:
```js
export const fixedShapeMock = {
  width: 100,
  height: 100,
  src: `test_fixed_image.jpg`,
  srcSet: `some srcSet`,
  srcSetWebp: `some srcSetWebp`,
  base64: `string_of_base64`,
}

export const fluidShapeMock = {
  aspectRatio: 1.5,
  src: `test_fluid_image.jpg`,
  srcSet: `some srcSet`,
  srcSetWebp: `some srcSetWebp`,
  sizes: `(max-width: 600px) 100vw, 600px`,
  base64: `string_of_base64`,
}
```
Then passing in the object as a prop to `<BacḱgroundImage />` like thus:
```js
const fixedMock = {
  fixed: fixedShapeMock,
}
// e.g.: <BackgroundImage fixed={fixedMock} />

const fluidMock = {
  fluid: fluidShapeMock,
}
// e.g.: <BackgroundImage fluid={fluidMock} />
```
Based on this approach it _should_ be possible to just set an object the following and use it:
```js
const fluid = {
  fluid: { src: `https://your-custom-url-image.jpg` },
}
...
<BackgroundImage fluid={fluid} crossOrigin={`Anonymous`} />
```
But do this at your own risk, no guarantees ; )! And of course you'd be missing out on the "Blur-Up" Effect, the tracedSVG or even image minification / conversion to WebP. 
For Gatsby I'd probably rather got the way through `gatsby-node.js` like some transformer or source plugins for external sources do...
Hope this helps : )!

**Comment by MatteoGioioso** [comment]
Hey, thanks for the explanation. So basically with those types of plug-ins (`gatsby-background`, `gatsby-image`, etc...) is not possible to use a CDN or an image hosted remotely?

**Comment by timhagn** [comment]
Well, you *are* able to with the help of plugins like [`gatsby-plugin-remote-images`](https://www.gatsbyjs.org/packages/gatsby-plugin-remote-images) - though downloading them beforehand would kinda defeat the purpose of a CDN, methinks. But it's also purpose-defeating, the other way round: Gatsby is a *static* site generator - meant to process images beforehand and make it possible for one's site to load in the fastest way, so what would a CDN add % )?
You wouldn't wanna tell me your usage case, or would you ; )?

**Comment by MatteoGioioso** [comment]
Ah, I get it now, I guess I still have to get into Gatsby mindset. Thanks for the clarification.

**Comment by timhagn** [comment]
You're welcome! Happy Coding and welcome to the Gatsbyverse : )!
