### ISSUE TITLE
Only one image shown many times when multiple GBI instances on a page

### ISSUE THREAD

**Issue by EricSSartorius** [timhagn/gatsby-background-image#29]
## Summary
After updating to gbi v 0.5.3, I realized that on pages where I have instances of 2or more gbi being used, that all the spots using the image show the exact same image. 

## Relevant information
No matter how many pictures I add that use gbi, it is always the last in the html that is shown in every instance. I also have multiple instances of gatsby image on the page but they all behave as expected. This problem is on every page that uses gbi and I have double checked that I am not accidentally calling the same image more than once. Unfortunately, I wasn't paying much attention as to the version number that this problem occurred. I had been updating the version randomly on a branch and only noticed the problem in this most recent update. I just wanted to see if anyone else has possibly come across this issue or if it is related to a newer version.

### Environment (if relevant)
```
  System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.1
  npmPackages:
    gatsby: ^2.4.2 => 2.4.2 
    gatsby-background-image: ^0.5.3 => 0.5.3 
    gatsby-image: ^2.0.10 => 2.0.13 
    gatsby-plugin-google-analytics: ^2.0.14 => 2.0.14 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-layout: ^1.0.12 => 1.0.12 
    gatsby-plugin-manifest: ^2.0.18 => 2.0.18 
    gatsby-plugin-offline: ^2.0.22 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-robots-txt: ^1.4.0 => 1.4.0 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-source-shopify: ^2.0.26 => 2.0.26 
    gatsby-transformer-sharp: ^2.1.2 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.5.12
```

### File contents (if changed)

`package.json`: N/A

**Comment by EricSSartorius** [comment]
Of course, right after creating an issue I got things to work. The problem was when I was using  a custom component and using gbi as a styled wrapper for the component. when I only used BackgroundImage without the custom component then the multiple images showed up fine.

I am however baffled as to why creating a custom component with gbi causes this problem.

 I had been using a custom component and using gbi as a styled wrapper for the component so I could add a gradient overlay to images where necessary.
So for example, if I had `const GBIWrapper = styled(BackgroundImage);` and a component that looked something close to (minus a few other props that i have in my repo to keep things simple)
```
const BackgroundImg = ({overlay, children, fluid}) => (
<GBIWrapper fluid={fluid}>
 {children}
  <Overlay />
</GBIWrapper>
)
```

@timhagn any ideas as to why this format in a newer gbi version would cause all images to render the same?

**Comment by dajinchu** [comment]
Seeing the same thing here. Works great in 0.2.74, but breaks in 0.3.0

**Comment by dajinchu** [comment]
Looks like this commit introduced our issue 6986e4547ba711d9459bb435654a15fd2a0b042e
I think it is because GBI stopped generating unique classId to be used for the :before containing the image. 

*Workaround:*

Give every `GBIWrapper` a unique className.

**Comment by timhagn** [comment]
Thanks @EricSSartorius for bringing this up and @dajinchu for chimining in : )!
After reading through your posts, Eric, one of the first things I wanted to ask, is if you're giving styled-components `className` prop to your Wrapper - but never mind, you seem to, cause as Da-Jin Chu pointed out, multiple Wrappers with the same `className` won't work as well % ).

You two really seem to have stumbled on the first example where `classId` wouldn't seem to be entirely superfluous ^^! It wouldn't have to be brought back, though, as - for once - it still exists, only get's deactivated per default if any `className` is present. And see below why I still want to deprecated it.
The reason I considered it deprecated was easing how to target the pseudo-elements (afterwards they were directly target-able through `styled-components`) without having to use jet another wrapper - or worse, having a random additional `className` without knowing how to target it.

A workaround for the moment might either be giving you `GBIWrapper` an additional `className` per element like you'd do with a `key` prop. Or one could go back to `classId` and use this as a "key".
I'd go with the first way, as the final classes get combined like thus, anyway:
```jsx
pseudoClasses = `.${classes.join('.')}${appendix}`
```
and `classId` just get's added to them if present afterwards at the moment:
```jsx
    pseudoClasses += `${pseudoClasses &&
      `,\n`}.gatsby-background-image-${classId}${appendix}`
```

So to me it seems like `classId` wouldn't really be needed after all, we just should refer to such a case in the README - and I'm definitely gonna add an example to the Demo / Documentation page for `gatsby-background-image` I'm just creating ^^.
Or would one of you know any way, how we could automatically recognize duplicate `className`s? Cause, thinking about it, we can't be sure any `BackgroundImage` component is already present in the DOM, so a simple `document.getElementsByClassName()` on Mount is out of the question : /.
Curious for your ideas, and thanks again for opening this issue : )!

P.S.: @dajinchu Why still using versions ~ `0.3.0`?

**Comment by dajinchu** [comment]
Just to track down which version introduced this issue

**Comment by timhagn** [comment]
@dajinchu Thanks for doing that, made it immediately clear to me, what was happening : )!
Any ideas on how to tackle this issue, or would you just go with the proposed README / Documentation change?

**Comment by dajinchu** [comment]
I think having to add your own class in each BackgroundImage feels like a workaround, and not a permanent solution. For my project I am just sticking to 0.2.9 to avoid dealing with it. Could you explain again why `document.getElementsByClassName` won't detect duplicates?

**Comment by EricSSartorius** [comment]
@timhagn to answer your question I was not using className at all in the component. Is this different than expected behavior? I know you mentioned if a component has a className then the classId is deactivated.

**Comment by timhagn** [comment]
@dajinchu As I said, we can't be sure (at least I ain't ; ) that any `BackgroundImage` component is already present in the DOM on first render, so probably `document.getElementsByClassName` would always return an array with a `length` of zero `HTMLElement`s. I'm gonna try it anyways and report back : ).
But of course I completely concur with you on the "workaround feeling" with an additional class.

@EricSSartorius On going through your code given above again I realized, that here `styled-components` automatically sets a `className` (or two, for that matter, one for tracking reasons, another "randomized" one with the actual CSS properties), so the workaround with an additional `className` wouldn't  even work - you have to use an  additional `classId` for the moment.

But I'm gonna investigate this, hoping `document.getElementsByClassName` will work against my expectations ^^. Wouldn't be the first time I learned something new about the DOM's internal workings since this project started as it's own package (e.g. would you believe, that the picture / image HTMLElement reference used to ascertain which image of the `srcSet` / `srcSetWebp` should be rendered never is actually added to the DOM and works anyway? % )...

**Comment by timhagn** [comment]
@dajinchu Yup, it's sadly as I guessed -.- During first render neither `document.getElementsByClassName` nor our own `getStyle('.<CLASSNAME>:before')` finds any element : /. What's strange is that while testing it `js-dom` finds elements % |!
Gonna investigate further, but for the moment only the workarounds seem feasible...

**Comment by issydennis** [comment]
Also came across this issue today when using multiple instances of GBI via a styled component. 
Managed to get what I needed working by using inline styles instead but not ideal of course.

Not sure how to implement the ClassID workaround mentioned (relatively new to styled-components and gatsby).

**Comment by timhagn** [comment]
Hi @EricSSartorius, @dajinchu & (welcome to the table) @issydennis!
Just released `v0.5.4` with `className` based component "caching", and added it's description to the
[README - Multiple Instances of Same Component](https://github.com/timhagn/gatsby-background-image#multiple-instances-of-same-component), including a warning on styling.
Please test and report, if you'd be so kind : )!

**Comment by dajinchu** [comment]
Very cool! Works great.

**Comment by issydennis** [comment]
Works for me now too. 
Thanks for such a speedy fix!

**Comment by timhagn** [comment]
Great that it works for you both : )! While I wouldn't talk about a "speedy fix", @issydennis, it took nearly a day ; ). And I'm not 100% satisfied having to use a second global variable (`imageCache` being the first, which was adapted from `gatsby-image`), but anything else failed, as written above.
Should perhaps write a blog post about the DOM quirks I've encountered during the continuing creation of `gatsby-background-image` % ).
If you, @EricSSartorius, are pleased for the moment, too, the honor of closing this issue is of course your's : ).

**Comment by timhagn** [comment]
@dajinchu It seemingly doesn't work in build, don't know why ad hoc... -.-

**Comment by dajinchu** [comment]
Yeah I just noticed that as well. Very strange!!

**Comment by timhagn** [comment]
At least at my place it seems like (on build) Gatsby fixes the additional `className` to `<BackgroundImage />` and it never gets changed on subsequent renders - so although the created `<style />` writes the correct images for the pseudo-elements and initial renders, they get never applied on the last render...

**Comment by timhagn** [comment]
OK, got it working in build - had to exchange the randomized additional class (like `gbi-yxzdhsh`) with a simple 32bit integer hash implementation of Java's `hashCode()`. The additional class now looks like such `gbi-1393017994` and is created from either the current `srcSet` or `className` given.
@dajinchu, @issydennis & @EricSSartorius, would you mind testing `v0.5.5` : )?

**Comment by EricSSartorius** [comment]
Sorry I am late to the party, @timhagn I can confirm v 0.5.5 works for me! If it works for others as well feel free to close the issue. Otherwise I will leave it open

**Comment by timhagn** [comment]
No prob, @EricSSartorius, you just missed a stony process ^^. Great it works for you, too : ).
As soon as the others chime in on your observation, the honor is all yours ; ).

**Comment by dajinchu** [comment]
Works great! Thanks @timhagn for the fix!!

**Comment by issydennis** [comment]
Works perfectly for me too :)

**Comment by timhagn** [comment]
: )
