### ISSUE TITLE
Image loads in black and white

### ISSUE THREAD

**Issue by oliverlambson** [timhagn/gatsby-background-image#32]
Thanks for developing this plugin, I'm finding it super useful :)

## Description

When loading the page, the image loads in black and white then sometimes fades in to color, and sometimes stays greyscale.

#### Here's my React component:

Props:
* ```Tag="div"```
* ```className=null```
* ```children=``` tested (1) with content and (2) with only an empty div with ```height=100vh```

```
import React from "react"
import { graphql, StaticQuery } from "gatsby"

import BackgroundImage from "gatsby-background-image"

const BackgroundSection = ({ Tag, className, children }) => (
  <StaticQuery
    query={graphql`
      query {
        bgImg: file(
          sourceInstanceName: { eq: "images" }
          relativePath: { eq: "some-image.png" }
        ) {
          childImageSharp {
            fluid(maxWidth: 1920) {
              ...GatsbyImageSharpFluid_tracedSVG
            }
          }
        }
      }
    `}
    render={data => {
      const imageData = data.bgImg.childImageSharp.fluid
      return (
        <BackgroundImage
          Tag={Tag}
          className={className}
          fluid={imageData}
          backgroundColor={`#fefefe`}
          title="Some image"
          fadeIn={false}
        >
          {children}
        </BackgroundImage>
      )
    }}
  />
)

export default BackgroundSection
```

### Expected result
Image loads in color.

### Actual result

The image either loads-in black and white and never gets color, or loses and regains its color depending on the screen size.

Methods of changing the screen size used:
* moving browser from 1440p monitor to 1080p monitor
* using Chrome Dev Tools to check responsive layout
* accessing on an iPhone over the local network

### Environment

This is on WSL, but the same issue occurs on my MacBook Pro running macOS.
```
  System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.2.0 - ~/n/bin/node
    npm: 6.9.0 - ~/n/bin/npm
  npmPackages:
    gatsby: ^2.4.2 => 2.4.2
    gatsby-background-image: ^0.5.4 => 0.5.4
    gatsby-cli: ^2.5.14 => 2.5.14
    gatsby-image: ^2.0.41 => 2.0.41
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.0 => 2.1.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.0.36 => 2.0.36
    gatsby-source-filesystem: ^2.0.33 => 2.0.33
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19
  npmGlobalPackages:
    gatsby-cli: 2.5.14
```

**Comment by timhagn** [comment]
Hi @oliverlambson!

What you see are flashes of the traced SVG of your image in your background color (`#fefefe`).
The `0.5.x` version range was sometimes a little buggy and many changes were made since then, would you please try it with the latest version `0.6.1` and report back?

Thanks and fingers crossed,

Tim.

**Comment by oliverlambson** [comment]
Thanks for responding so quick, @timhagn!

I've updated the package (along with all my other outdated packages), but still no luck.

### Things I tried after updating
1. Commented out the ```backgroundColor``` prop—this made no difference
2. Substituted the ```...GatsbyImageSharpFluid_tracedSVG``` for ```...GatsbyImageSharpFluid```—the blurred-up image was in color and the final image in black and white, what do you think of this?

Oliver

**Comment by timhagn** [comment]
Mkay, @oliverlambson, this leaves me a little stunned at the moment % |...
The only thing I could think of is - as of your initial description) the `className` of `null` - why do you set it at all if you don't need it (and how is the `<BackgroundImage />` styled)?, but else... 
Why it then still would work in FF I have no idea ^^.
You wouldn't happen to have an example repo of your code and images ready, or would you (or could have one ready tomorrow)?
Definitely wanna have a deeper look at this tomorrow, as that's a new one ; ).

**Comment by oliverlambson** [comment]
I’m not actually setting the className to null, I was just clarifying that I wasn’t using it (I have a class but removed it to test). I can add you as a contributor to the private repo if that works for you?

**Comment by timhagn** [comment]
Yip, that'd be great (of course I'm keeping everything confidential) and thanks for the clarification!
As I wrote above, I'm only gonna be able to dig into it tomorrow, as it soon is midnight around here and I'm sitting in front of my keyboard way too long already ; ).

**Comment by timhagn** [comment]
Mkay, couldn't help but have a quick look ^^. And though I could replicate it in Chromium _and_ Firefox on Linux, it seems your issue has nothing to do with `gatsby-background-image` but with 
`gatsby-plugin-sharp`'s handling of PNGs (or the original image) - cause as soon as I quickly converted and changed `guitar_front-top_wide-angle.png` to a jpg and restarted `yarn develop` it showed up in color % ).

**Comment by oliverlambson** [comment]
Oh that’s great progress. Will dig around tomorrow and see if anyone else has experienced something similar with sharp. 

At least that should help me out in the short-term since I was planning on moving to JPGs because I don’t need transparency.

**Comment by timhagn** [comment]
Should you need any further help, I'm happy to oblige ; ). Else feel free to close this issue : ).
Nice theme (product class) by the way!

**Comment by oliverlambson** [comment]
Thanks, I really appreciate it :)
