### ISSUE TITLE
Contributors, assemble : )!

### ISSUE THREAD

**Issue by timhagn** [timhagn/gatsby-background-image#35]
Hi contributors!

Due to merging the old repo of `gatsby-background-image` into a lerna monorepo, though you're still mentioned in the commit history, GitHub seems to have lost track of you.

So if you all could just open a little PR ("empty" ones would be OK, too ; ), you'd officially show as contributors again. 
So:
@ambethia 
@nshoes 
@adam-wheatley
@r007 
@milanito 
@einarbirgir 
@davebra 
@spencersmb 
@seangenabe 
Please file a PR : )!

And as we now are at 10 contributors (and many more help through issues and such), methinks we maybe should give `AllContributors` a go, what do you think?

Awaiting your PRs and replies,

best,

Tim.

**Comment by timhagn** [comment]
No reaction except @nshoes oO? Come on let's do this : )!

**Comment by nshoes** [comment]
Someone isn't keeping up to date on their notifications! 😆

**Comment by timhagn** [comment]
Looks like it ^^.

**Comment by timhagn** [comment]
Hi Nate / @nshoes,

would you mind open a small PR (perhaps even a small change in the docs or even comments, as my main language is still German ; ), so that GitHub would be able to count you as a contributor again? No one else seems interested - although I'm offering at least maintainer status ^^.

It'd be a pleasure having you onboard : )!

Thnx,

Tim.

P.S.: I'm closing this issue on Monday the 23rd at the latest (it's getting annoying else-wise), so whomever is interested, I'm definitely open for maintainers and of course attributions : )!

**Comment by timhagn** [comment]
As this issue seems stale for some time and ProBot strangely didn't act, I'm closing it now manually. Should there still be interest, just give a shout : ).
