### ISSUE TITLE
default styles

### ISSUE THREAD

**Issue by mr-bios** [timhagn/gatsby-background-image#36]
is there a sample somewhere that contains how to set the default style props to the empty strings shown in the readme for gatsby-background-image-es5? 

example:
  backgroundSize: '',
  backgroundPosition: '',
  backgroundRepeat: '',

Sorry for the lack of info.  im posting from my phone.

Regards

**Comment by timhagn** [comment]
Hi @mr-bios!

Mkay, maybe I should clarify this somehow in the README a bit more (and perhaps you might help me in clarifying it : ). 
Unsetting the [default background properties](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image-es5#styling--passed-through-styles) you mentioned does just that:
It prevents `gatsby-background-image(-es5)` from spreading the _defaults_ into _both_ pseudo-elements used for the transitions (`:before & :after`), so you are able to (and have to) target them individually in your CSS / CSS-in-JS (like in [gbitest's layout.css](https://github.com/timhagn/gbitest/blob/3536d8fee9f7ee1dd5d8f30130dfd84202002c2b/src/components/layout.css#L633) or its [`components/index.js`](https://github.com/timhagn/gbitest/blob/3536d8fee9f7ee1dd5d8f30130dfd84202002c2b/src/components/index.js#L110)).
You could of course just set each of the three `style={{}}` props to your own defaults; unsetting them is really just meant to give you more control over individual styling of the pseudo-elements.

Hope I could lift the fog a little for the moment; I'm working on a demo page for `gbi` shedding some more light on "all" it's possibilities : ).

Else I'm happy to help more, so just shoot % )!

Best regards,

Tim.

**Comment by timhagn** [comment]
Hi @mr-bios!

Did my comment answer your question and if so, would you want to close this issue?

Greetz,

Tim.

**Comment by timhagn** [comment]
Hi @mr-bios.

As you ain't answering any of my replies, I'm closing this issue.

Greetz,

Tim.
