### ISSUE TITLE
Opacity or Alpha manipulation on the image

### ISSUE THREAD

**Issue by Kitefr** [timhagn/gatsby-background-image#38]
Hello,

Thanks for making this plugin whch was exaclty what i wanted for my website.

I wanted to know if there is a way to manipulate the **opacity** or the **background alpha**, to diminish it a bit **without impacting the children components** ? 

Thanks

**Comment by timhagn** [comment]
Hi @Kitefr,

thanks for the flowers : ).

Am I guessing correctly, that you're talking about a `rgba()` bg "image"? Cause that's definitely on my TODO (as this was already asked for over at Gatsby's spectrum.chat), though needs some heavy rewrite of all image handling functionality.
For the moment you might be able to use a wrapper for the children with a `position: absolute;`, taking them out of the flow and using e.g. 
`opacity: 0.5 ! important;` on `<BackgroundImage />` - but I haven't tested it...
Or did I guess wrongly and you might be able to show me with "normal HTML / CSS" what you're trying to do?

Greetz,
Tim.

**Comment by Kitefr** [comment]
You understood correctly. For now, as a do not want to use absolute position for it, I just save the image with a lower opacity. I do not have a lot of image so this is working as a workaround.

I am not in a hurry so this is cool.

I am mostly, for now,  trying to understand with your basic exemple on how to use the plugin, how to pass data like image filename to the component and graphql because for now, it is hardcoded into my component...

But I am having fun :)

**Comment by timhagn** [comment]
That's another workaround, of course ^^.
Will try to find the time to implement `rgba()` in the upcoming week.
You having fun with this nifty little package is important, though should you have more questions on how to get "productive", I'm happy to help (some code from you might help ; ).

**Comment by Kitefr** [comment]
Thank you. Well i am mostly learning how to use Gatsby but yeah, it is fun :)

**Comment by timhagn** [comment]
Hi Yann / @Kitefr,

this is now possible (at least it is at my place with FF and Chrome % ) with the just published `v0.7.2` like shown in the example in its [README](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#how-to-use-with-multiple-images) : ).

Should it work for you, feel free to have the honor to close this issue : ).

Best,

Tim.

**Comment by Kitefr** [comment]
Thanks @timhagn !

I'll update my project soon to test that.

**Comment by timhagn** [comment]
As this issue should be solved, seems stale for some time and ProBot strangely didn't act, I'm closing it now manually. Should there still arise problems, just give a shout : ).
