### ISSUE TITLE
`bgImage` getting set to empty string on every other pixel interval when resized

### ISSUE THREAD

**Issue by nshoes** [timhagn/gatsby-background-image#4]
![backgroun image flicker on resize](https://user-images.githubusercontent.com/4118389/51062877-62a4be00-15ad-11e9-88b8-ea8c40211408.gif)

When resizing, on every other render [the `bgImage` variable is being set to an empty string](https://github.com/timhagn/gatsby-background-image/blob/master/src/index.js#L289). If you change this line to `bgImage = nextImage` it solves the issue and tests pass 🤷‍♂️.

I could not figure out why the component rerenders on every pixel change when resizing. Can someone provide some insight? I'd like to understand the problem fully and provide a sensible fix.

**Comment by timhagn** [comment]
Setting `bgImage` to an empty string was the easiest way to switch images and set opacity accordingly when the component get's rendered. Funnily I have no problems with resizing on the page I wrote this for in the first place [fCC Portfolio Page](https://fcc.timhagn.com) - here's it's usage in the [repo](https://github.com/timhagn/th_front/blob/master/src/components/StyledBottomSection.js). We might introduce a "state" variable or deduce the current `bgImage` / `nextImage` in another way to work around your (and maybe other's) issue. Would you mind giving details of your browser & system and maybe some code?

**Comment by nshoes** [comment]
Sorry about the radio silence, just getting back in and settled from vacation. If it has worked for you, there is probably something specific to our project that is causing the flickering. I'll get an example up and running tomorrow.

**Comment by timhagn** [comment]
No problem @nshoes, wasn't too involved myself this week. But made a test site to develop with and now see your issue manifested (plain `gatsby new ...` with added styled-components and `npm link`ed this repo locally). Working on `v0.2.0` with no more superfluous tags and load handling with `Image()`, and of course am trying to resolve the "flickering" issue while at it.

**Comment by nshoes** [comment]
Oh great! Let me know when it's live, I'd love to take a look at it.

**Comment by timhagn** [comment]
@nshoes `0.2.0` has just been published : ).

**Comment by timhagn** [comment]
As this now should be fixed, I'm closing the issue for now - should you find any behaviour extraordinaire,
just give me a Msg : ). Thnx for bringing this up, @nshoes, kicked me to be done with the placeholder elements ; ).

**Comment by timhagn** [comment]
@nshoes no problem : ).
