### ISSUE TITLE
Adding utility classes breaks the classes (margin, padding, etc.)

### ISSUE THREAD

**Issue by miniplus** [timhagn/gatsby-background-image#40]
## Description
```css
.p-5 {
    padding: 10px;
} 
```
Adding a utility class by using `className="p-5"` breaks the utility class (or any other class really) as the background image styling gets applied to the `p-5` class in this example.

### Expected result

Adding a className shouldn't change the styling of the original added className.
Instead the className should be added to the container div with no additional styling

### Actual result

`.p-5` gets background image styling applied, causing the css class to no longer be useful as reuse is no longer possible.

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.8.6 => 2.8.6 
    gatsby-background-image: ^0.7.2 => 0.7.2 
    gatsby-image: ^2.1.2 => 2.1.2 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.1 => 2.1.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3 
    gatsby-source-filesystem: ^2.0.38 => 2.0.38 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
  npmGlobalPackages:
    gatsby-cli: 2.6.9
```

**Comment by timhagn** [comment]
Hi @miniplus,

Are you really only using `className="p-5"` on `<BackgroundImage />`? 
This of course would apply everything to `.p-5`, when no other class is given. Would you perhaps have an example repo, or at least some more code? 
Cause going only from this and your `gatsby info` leaves me in the dark what you actually meant with "the original added className" at the moment...

Greetz,

Tim.

**Comment by miniplus** [comment]
I can't share the actual code as it's private, I did make some quick adjustments and screenshots however. Hoping this will do, otherwise I'll have to make an entire reproduction repo (can't do that today).

Actual code:
<img width="390" alt="code" src="https://user-images.githubusercontent.com/1800310/59773419-dd38de80-92ad-11e9-8063-1f3935a3c9d9.png">

Rendered result:
<img width="591" alt="result" src="https://user-images.githubusercontent.com/1800310/59773443-ea55cd80-92ad-11e9-906b-ae453387d26d.png">

Generated HTML:
<img width="1051" alt="generated-html" src="https://user-images.githubusercontent.com/1800310/59773456-f2ae0880-92ad-11e9-93f8-dc19093f0b1c.png">

Generated CSS:
<img width="306" alt="generated-css" src="https://user-images.githubusercontent.com/1800310/59773460-f5106280-92ad-11e9-9fbb-e25645ba435c.png">

As you can see  in the last screenshot (generated CSS), the background image is applied to the .p-3 class causing it to bleed out across the entire page.

**Comment by timhagn** [comment]
Thanks for replying so quickly and nope, you won't have to create it's own repo for it, as it's just as I mentioned in my first comment: Of course it "leaks" out to every other `p-3` or `p-5` "utility / helper" classes when you use it outside again, as CSS does the heavy lifting in `<BackgroundImage />`, so there's sadly no way around it, when you give a `className`.

Should you really just need to add some extra padding, I'd either leave the `className` out altogether, as then the auto generated `classId` kicks in, as [mentioned in the README](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#deprecated-styling), and add the padding by `style={{ padding: `0.5px` }}` (though you'd have the first case, where `classId` actually would make some kind of sense ; ).

Or I'd (*rather*) add a specific class for `<BackgroundImage />` and the `p-3` after it like `className="test p-3"`, cause then only `.test` gets changed and p-3 gets applied, too (at least when I just tested it in my upcoming demo-page for `gbi`) cause of CSS-specificity. 

Hope I could be of help (and didn't sound to condescending, today isn't my best of days % ).
Should it have helped, feel free to close this issue : ).

Best (wishes and hoping for),

Tim.

**Comment by miniplus** [comment]
Doesn't sound condescending at all, I appreciate the help!

As a workaround, using multiple css classes is what I'm currently doing indeed.
I wasn't looking for help on the matter, I actually thought this was a bug, hence the issue.

I'm just thinking, there must be a way to scope the css generated by`gbi` (as is the case with the classId) to the component instance?

Not blaming or wanting to sound condescending either, just trying to find a possible solution as I'm sure I can't be the only one to experience this.

**Comment by timhagn** [comment]
Great the "second class" (pun not intended ; ) approach works for you! I already "feared" we'd have to keep the `classId` (as it's a nuisance having to check for it ^^).

The problem with just having classes "scoped" to `gbi` (or randomly generated as has to be done with "multiple singular instances") is making it kinda hard (`!important;` CSS modifier, I look at you) to style the pseudo elements from the outside.

So I rather went the CSS "default" way, easing it especially for CSS-in-JS folks.

Your comment didn't sound condescending, either, no worries : )! You're really just the first one opening an issue for this - or asking on Gatsby's spectrum.chat or discord channels, where I try to be of help, too (not only for `gbi` ; ).

As your original issue seems to be solved, I'd rather close it (or leave the honors to you : ), as we can continue our conversation on a closed issue, too : ). 
Just want to keep the issue count as low as possible, lest my blood pressure rises to high ^^.

**Comment by timhagn** [comment]
Thanks, @miniplus : )!
