### ISSUE TITLE
IBackgroundImageProps types possibly incorrect

### ISSUE THREAD

**Issue by joshdcuneo** [timhagn/gatsby-background-image#42]
## Description
Current types don't allow for mixed array of IFluidObject and string.

### Steps to reproduce
Current types:

 `fluid?: IFluidObject | [IFluidObject]`

### Expected result
Required types:

`fluid?: IFluidObject | (IFluidObject | string)[]`

I think that is correct. Can anyone confirm?

Happy to open a PR.

**Comment by timhagn** [comment]
Hi @joshdcuneo,

thnx for opening this! As I'm quite new to TS, the definitions in [`index.d.ts`](https://github.com/timhagn/gatsby-background-image/blob/b8c47d95f046ea6963e49f5b84530e3597e3dd69/packages/gatsby-background-image/index.d.ts#L30) might be incorrect, or I might've missed publishing them with the last version (or both % ). And I might've forgotten changing them in `gbi-es5`, too : /...
Every correction and PR would be greatly appreciated thus I'd be happy should you want to have a go and open one : )!

**Comment by joshdcuneo** [comment]
I'm pretty new also but I think both those things are true! I'll have a
look through over the weekend and hopefully get a PR up. Not much open
source experience here so don't be shy with feedback either.
