### ISSUE TITLE
White flash after cached image loads.

### ISSUE THREAD

**Issue by jackstrosahl** [timhagn/gatsby-background-image#44]
## Description
When loading a cached image, it correctly blurs up to full resolution, but then it flashes white briefly and reappears.

### Steps to reproduce
1. Use BackgroundImage tag.
2. Load page
3. The image loads correctly.
4. Reload the page
Repo to reproduce: https://github.com/jackstrosahl/jackstrosahl.github.io/tree/1842763c2a8bfedd3f669774df03c2b4050e9cad.  (Sorry, but I couldn't get gbitest working locally)

### Expected result
The image loads the same as it originally did.

### Actual result
The image "blurs up", flashes white, and reappears.

### Environment

```System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.9.2 => 2.9.2
    gatsby-background-image: ^0.7.3 => 0.7.3
    gatsby-cli: ^2.7.2 => 2.7.2
    gatsby-image: ^2.1.4 => 2.1.4
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.3 => 2.1.3
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.5 => 2.1.5
    gatsby-source-filesystem: ^2.0.39 => 2.0.39
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.6.13
    gatsby: 2.9.11```

**Comment by timhagn** [comment]
Hi @jackstrosahl,

I couldn't replicate your issue locally on Mint 19.1 (based on Ubuntu 18.04.1 not your 18.0.4.2, though) with FF 67.0.4 and Chromium 77.0.3833.0 (Developer Build), which browser(s) in did you experience it?

Would of course also be interested, which errors you got with `gbitest`? As I just reinstalled it without a problem and also tested it with `gbi` updated to `v0.7.3` (in all three versions of node % ).

Hoped I'd be able to offer more help, though from testing it in a VM with your exact Ubuntu version, I'm at a loss : /.

Greetz,

Tim.

**Comment by jackstrosahl** [comment]
@timhagn Classic, it was my fault.  I was storing the fluid data in state, then updating the state (different key).  That caused a new request.  I was doing that all wrong so I just put the data in a variable.

Anyway, my issue with gbitest is that it always threw errors like this:
```Generating image thumbnails [=====-------------------------] 1/6 0.0 secs 17%error UNHANDLED REJECTION

  Error: Failed to process image /home/jack/gbitest/src/images/gatsby-astronaut.png```
(in different variations of the image being processed and progress through generating the thumbnails)

I fixed it by changing the GraphQL fragments to the bare ...GatsbyImageSharpFluid.  It's worth noting I'm on WSL, could be the issue.  Thanks for your time :)

**Comment by timhagn** [comment]
Was I using another branch than you? Or was that repo a demo?
But great it turned out positive in the end!

Mkay, WSL might be at least partly involved ; ) Or do other png images work without a problem (especially as the astronaut is just from `gastby-starter-default`)?

And no probs, you're welcome.
Do you want the honors to close this?

Best,

Tim.

**Comment by jackstrosahl** [comment]
I only have one branch for development, I think we had the same code.  

It seems using the Webp fragments is the issue on gbitest on my end.
