### ISSUE TITLE
Multiple images - when linear-gradient overlaying an image it breaks noscript tag

### ISSUE THREAD

**Issue by borisirota** [timhagn/gatsby-background-image#45]
## Description

Hi, in order to make the effect of linear-gradient overlaying an image, the linear-gradient must have some opacity and be located before the image -> 
```
...
        const backroundImage = [
          `linear-gradient(rgba(255, 255, 255, 0.6), rgba(255, 255, 255, 0.6))`,
         image.childImageSharp.fluid
        ]
...
              <BackgroundImage
                fluid={backroundImage}
              >
...
```

The problem is that in order to fallback to mode where javascript is disabled, [the first element in the array is taken into account](https://github.com/timhagn/gatsby-background-image/blob/master/packages/gatsby-background-image/src/index.js#L282) but since it is the `linear-gradient` and not the image itself, the fallback functionality is broken and the img tag has no src ->
```
<noscript><picture><img src="" alt="" style="position:absolute;top:0;left:0;z-index:-1;transition:opacity 0.5s;transition-delay:0.5s;opacity:1;width:100%;height:100%;object-fit:cover;object-position:center"></picture></noscript>
```

Thanks for a great package :)

**Comment by timhagn** [comment]
Hi @borisirota,

thanks for noticing this (and the flowers, of course). This one slipped me ^^. Shall be rectified this week (unless you want to open a PR ; ). Thought bout replacing the default `<noscript />` Picture element completely, as it's the (multiple) background we want, not a single `<img />`...

Gonna look into it, so thanks again!

Greetz,

Tim.

**Comment by borisirota** [comment]
Hi @timhagn Thanks for the quick reply!

> ... as it's the (multiple) background we want, not a single \<img \/\>

You are right :)

And your idea sounds a great solution!

**Comment by timhagn** [comment]
**\*hmmz\*** Which images should we choose for the `<noscript />` `background-image`(s)?
Sadly [`image-set()`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-set#Browser_compatibility) is not usable for the near future (and how should we decide on WebP support)... Mulling it over, though I'm definitely open for suggestions! As using only the `src` would make a lie out of the "optimized images" part for sites with JavaScript deactivated -.-

**Comment by borisirota** [comment]
When the user supplies single image the current fallback does the job as expected.
There is a problem only when the user supplies multiple images and it seems that there is no ideal solution.

I think there should be 2 modes for fallback (you already mentioned everything I'm just summarising my thoughts :) ):

1. single image - no need to change nothing.

2. multiple images - use the `src` as you proposed - it will be good enough (at least for starters).
We, as users, responsible of generating the background image with dimensions that are good enough (`maxWidth` of at least the maximum width it will be presented) so choosing `src` should work as expected. Its possible to add small section to the README mentioning how it works when JS disabled and we want to use multiple images.

It seems to me that in this scenario replacing the `<noscript>` contents with something like the following (maybe there are more options to be set but I'm using only a fraction of the API) can solve it in the most simple way ->
```
<noscript>
    <style>
        .RELEVANT_CLASS:before {
            background-image: fluid[0] /* if linear-gradient */,url(fluid[1].src) /* if image */,...; 
            opacity: 1; 
        }
    </style>
</noscript>
```

It is not the most efficient solution, but, It does work out of the box as the user expects.

Then, it possible to think about the media-queries solution (without WebP support though) is there is need.

**Comment by timhagn** [comment]
Hi @borisirota,

just got it working in a (near) functional example like thus, even with WebP support (as browsers which support it will only load the images from the second `background-image` and those that don't will fallback on the first) from this stack of images:
```js
  const backgroundFluidImageStack = [
    seamlessBackground.childImageSharp.fluid,
    `linear-gradient(rgba(220, 15, 15, 0.73), rgba(4, 243, 67, 0.73))`,
    astronaut.childImageSharp.fluid,
    singleSilverBorder.childImageSharp.fluid,
    singleBorder.childImageSharp.fluid,
  ].reverse()
```
to this `noscript` element:
```html
<noscript>
    <style>
          .MultiBackground__StyledMultiBackground-sc-1ao4jpx-1.hriooV:before {
            content: '';
            display: block;
            position: absolute;
            z-index: -100;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            
            background-position: center;
background-repeat: no-repeat;
background-size: cover;

            background-image: url('/static/dc8b6bed2e85a79f4efcbd4daba02255/ae2c8/single-border.png'),url('/static/a53626caed781a127ec5fcabbbb5468f/b2727/single-silver-border.png'),url('/static/6d2384666305c9c7b5d4756db1652d2c/ea5de/astronaut.png'),linear-gradient(rgba(220, 15, 15, 0.73), rgba(4, 243, 67, 0.73)),url('/static/4fc092b63e812cb0aa88744706443667/0b413/seamless-background.jpg');
            background-image: url('/static/dc8b6bed2e85a79f4efcbd4daba02255/4ce47/single-border.webp'),url('/static/a53626caed781a127ec5fcabbbb5468f/f07ef/single-silver-border.webp'),url('/static/6d2384666305c9c7b5d4756db1652d2c/0c129/astronaut.webp'),linear-gradient(rgba(220, 15, 15, 0.73), rgba(4, 243, 67, 0.73)),url('/static/4fc092b63e812cb0aa88744706443667/6502c/seamless-background.webp');
          }
    </style>
</noscript>
```
You can have a look at how it's generated in [`StyleUtils.js:254`](https://github.com/timhagn/gatsby-background-image/blob/e918d3f569377fcbe4496799e9f4be52abe00103/packages/gatsby-background-image/src/StyleUtils.js#L254) in the branch `change-noscript-behavior`.

Then (turning off JS in a built and served version) I noticed, that (of course) the current background-styles were unable to be parsed from CSS, as therefore we would need a `window` object (and that's neither available during build nor SSR). I only could rectify it by duplicating the `background-*` styles from the CSS classes themselves to the `style={{}}` object like thus:
```js
      style={{
        backgroundRepeat: `no-repeat, no-repeat, no-repeat, no-repeat, repeat`,
        backgroundPosition: `bottom right, top left, bottom right, center, center`,
        backgroundSize: `auto`,
      }}
```
Don't like this at all, though that's the simplest way I could come up with for the moment : /.
Though I don't know if we should implement media queries at all for the time being, as this would probably bloat the HTML by a manifold. Alone in my example with four images and a CSS string we would accumulate 10 media queries oO...

**Comment by borisirota** [comment]
Hi @timhagn Thank u very much for the fast progress :)

few things:

1. WebP support doesn't work this way. If the image inside the `background-image `isn't recognised by the browser, it just being replaced with the value `none` and not fallback to the previous declaration of `background-image`. I tried it before my previous answer and now ensured it again in Safari.

2. I'm not quite sure why you include in the noscript style tag other properties than `background-image` and `opacity`. The final html already includes all styles as inline style tags and these properties already included in the default style tag [that this plugin generates](https://github.com/timhagn/gatsby-background-image/blob/e918d3f569377fcbe4496799e9f4be52abe00103/packages/gatsby-background-image/src/StyleUtils.js#L190) (which outside the noscript). Am I missing something?

3. I'm not sure I understand why to parse the background-styles from the css on SSR. Maybe the previous bullet is the solution for this? because the styles already exist in the html as a style tag so there is no need to get them?

4. Not very critical but a small optimisation - the `:before` pseudo element doesn't really need to include the tracedSVG or base64, no? the `:after` pseudo element already has it and it responsible to show it, no? Am I missing something?

**Comment by timhagn** [comment]
Hi @borisirota,

some nice points and damnit, there's always Safari : /. Works flawlessly in Firefox & Chomium, but what the heck, gonna look into it. To your points in Detail, starting with 2:

2. As I wrote, it just was a quick trial and error example setup, I just copied over the implementation from `createPseudoStyles()` and adapted them accordingly, to rapidly get a working prototype; cleaning up comes when we're done ; ).

3. The `background-*` styles are parsed to be added to the pseudo elements. It not only kicks in during SSR but later in production as soon as the scripts are loaded. Else everyone would have to style their pseudo elements on their own, which would definitely digress from the "without the work" in `gbi`'s title.

4. Might you explain a little, where you're heading here? Are you speaking about `createNoScriptStyles()` or where would I have to look?

5. You've got a point there, as well **\*hmmz\***. Gonna think about it, just went and switched one for the other.
EDIT: Only came to me after commenting: the `<picture />` tag breaks in IE11 (which a few issues around where opened % ).

6. Here I completely concur ^^!

Thanks for your help with this, up till now : ).

Greetz,

Tim.

**Comment by borisirota** [comment]
2. Sure :)
3. Ohhh I see. But isn't styling by their own means replacing
    ```
    .my-background-image {
        background-*: "BLABLABLA";
    }
    ```
    with
    ```
    .my-background-image::before,
    .my-background-image::after {
        background-*: "BLABLABLA";
    }
    ```
    Which is more explicit for the user, affects the target element (background-* styles on the wrapping div has no effect so what is the meaning of that? only as a "convenient" way (API) for the user to pass styles through class and to save him user the need to type `::before` and `::after`?) and fixes the problem you currently facing. Am I missing something?
    * _In addition it will fix the [IE11 issue of parsing the background-* styles](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#todo)_ :)
4. I mean the default behaviour, with javascript enabled. Both the SSR served html and the runtime code generates the tracedSVG\base64 placeholder in `background-image` for both the [before pseudo element](https://github.com/timhagn/gatsby-background-image/blob/e918d3f569377fcbe4496799e9f4be52abe00103/packages/gatsby-background-image/src/StyleUtils.js#L218) and the [after pseudo element](https://github.com/timhagn/gatsby-background-image/blob/e918d3f569377fcbe4496799e9f4be52abe00103/packages/gatsby-background-image/src/StyleUtils.js#L230). And then the real image once loaded placed in both pseudo elements as well just with different `z-index` (`::before` has `-100` and `::after` has `-101`). Why setting this for both elements?
5. Yep I guess its better to make the fallback to be background image as well (at it was intended) rather than converting it to be regular `img` tag which not always valid (e.g. multiple images as background).

Thank u you for addressing these issues :)

Boris

**Comment by timhagn** [comment]
Addressing the first point on Safari and WepP, I now threw out their handling. The second one is literally cleaned up as well ; ).

3. Yup, up front and foremost it's a convenience API for developers. But as I myself am sometimes lazy, too, and this feature already has seen a few issues and PRs (would have to have a closer look at the dependent themes, but I guess they make use of it as well), this can't go for the moment. I concur with your observation that adding the styles to the encasing `<Tag />` element is superfluous - but an easy way to see on first glance, if CSS parsing succeeded ; ). I still stand by this package's tagline `without the work`, so transferring the responsibility to the user is out of the question (and parsing of IE11 as well as the late Edge's {before Chromium} styles is an issue on it's own % ).

4. Oh, now I get your meaning. That's for fallback reasons: we never know which images will come first, depending on the `GraphQL Fragment` used and final image caching. And as it doesn't lead to a duplicate image loading, but safer backgrounds, I stuck with it for the moment, but of course am happy for every PR ; ). This behavior was introduced quite some time back, see #16.

5. Mkay, we could introduce a switch between single images and multiple ones... Though I never really was happy with the `HTMLPictureElement` being used as a `noscript` fallback. As you say,  "as it was intended" concerns background-image(s) and with the `<picture />` we'd be switching one problem in `noscript` (no natural WebP switch) for another in some (especially older) browsers: Having either no support for `picture` (and e.g. `picturefill` depends on JS, AFAIK) or having problems with `object-fit` which needs its own ugly hacks... Yeah, I guess we should stick with the bg-image even for singular ones ^^.

Thanks for your input : )!

Tim.

**Comment by borisirota** [comment]
Sure! Thanks :)

**Comment by timhagn** [comment]
Hi @borisirota,

mkay, I tried the `<picture />` approach (using a `div` container for background CSS functions) for multiple images but promptly threw it overboard again (especially as I don't know of any possibility for `background-repeat` through `object-*` styles. You may still have a look at my small experiments within [`OldNoScript.js`](https://github.com/timhagn/gatsby-background-image/blob/master/packages/gatsby-background-image/src/__tests__/mocks/OldNoScript.js), where I back-upped them to ftm.

As that approach was useless, I stuck with the `<style />` one and just published `v0.8.0`.
And who would have thought, suddenly IE 11 & Edge have no problems getting the styles % ). Probably the old `<picture />` approach broke the styling there oO...
Also tested it in Safari with both JS deactivated and active, no further problems seen.

Should this solve your initial issue (for the moment, WebP support for bg-Images during `noscript` is still a TODO), feel free to have the honor to close this : ).

Thanks again,

Tim.

**Comment by borisirota** [comment]
Amazing! Thanks a lot @timhagn :)

**Comment by timhagn** [comment]
Great that it's working for you! You're welcome, of course, thanks for noticing this and again for your input : )!
