### ISSUE TITLE
Support for Art Direction?

### ISSUE THREAD

**Issue by Frannsoft** [timhagn/gatsby-background-image#47]
## Summary

I was wondering if there is support for art direction? Looking through `gatsby-image` docs I see it supports it via [media key](https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images). 

I've been looking through the `gatsby-background-image` docs and using the `gatsby-image` examples, but it doesn't seem to apply the proper background image based on my specified media query.

## Relevant information

My config so far:
```
  const data = useStaticQuery(graphql`
    query {
      mobile: file(relativePath: { eq: "home-small.png" }) {
        childImageSharp {
          fluid(quality: 100, maxWidth: 1000) {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
      desktop: file(relativePath: { eq: "home.png" }) {
        childImageSharp {
          fluid(quality: 90, maxWidth: 4160) {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
    }
  `);

  const sources = [
    {
      ...data.mobile.childImageSharp.fluid,
      media: `(max-width: 767px)`
    },
    {
      ...data.desktop.childImageSharp.fluid,
      media: `(min-width: 768px)`
    }
  ];

//...usage
 <BackgroundImage
        critical
        fadeIn={false}
        className={`hero is-fullheight ${styles.backgroundImageLarge}`}
        fluid={data.desktop.childImageSharp.fluid}
      >
      //content
</BackgroundImage>
```
### Environment (if relevant)

Gatsby info:
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gatsby: ^2.11.7 => 2.11.7
    gatsby-background-image: ^0.7.6 => 0.7.6
    gatsby-image: ^2.2.4 => 2.2.4
    gatsby-plugin-sass: ^2.1.0 => 2.1.0
    gatsby-plugin-sharp: ^2.2.2 => 2.2.2
    gatsby-source-filesystem: ^2.1.2 => 2.1.2
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1
```

Thanks for creating this! It's been pretty easy to use.

**Comment by timhagn** [comment]
Hi @Frannsoft,

the way `gatsby-image` is used as an Array must have been introduced after I added the possibility to use multiple (stacked) background images to `gbi`, gonna have a look, how they implemented it.

As an Array already indicates to `gbi` that multiple bg-images should be used, simply attaching the `media` key won't be possible without a refactor I guess...

As a workaround you might simply check yourself via the window's `width` which image to give to `gatsby-background-image` for the moment, but I'm open to suggestions : ).

**Comment by whalesingswee** [comment]
@timhagn noob question here, if you don't mind me asking, how do you check window's width via Gatsby?

**Comment by Frannsoft** [comment]
@timhagn Cool, I'll check out your workaround. My use case is pretty small, so for now I'm just using plain old media queries and hiding the background images and `children` prop that should be shown based on what fits.

Thanks for looking into it!

**Comment by whalesingswee** [comment]
@timhagn I was able to resolve my issue. By following this [WindowSize Hook](https://usehooks.com/useWindowSize/), I was able to achieve changing image sizes based on the window size.

```
const Layout = ({ children }) => {
  const size = useWindowSize();

  const data = useStaticQuery(graphql`
    query {
      backgroundD: file(relativePath: { eq: "kv-1-201906718-s.jpg" }) {
        childImageSharp {
          fluid(maxWidth: 1366) {
            ...GatsbyImageSharpFluid
          }
        }
      }
      backgroundM: file(relativePath: { eq: "kv-1-201906718-s-mobile.jpg" }) {
        childImageSharp {
          fluid(maxWidth: 768) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  `)

  const bg = {
    desktop: data.backgroundD.childImageSharp.fluid,
    mobile: data.backgroundM.childImageSharp.fluid
  }

  return (
    <>
      <BackgroundImage
        Tag="section"
        className="bgBackground"
        fluid={(size.width > 1024) ? bg.desktop : bg.mobile}
        backgroundColor={`black`}
      >
        <Container>
          <main>{children}</main>
          <h1>{(size.width > 1024) ? "BIG" : "SM"}</h1>
          <Footer></Footer>
        </Container>
      </BackgroundImage>
    </>
  )
}
```

**Comment by timhagn** [comment]
@whalesingswee Great that you could solve it yourself, wanted to give the following snippet to @Frannsoft as soon as I'd be at my keyboard again, and missed your comments % ).
```js
/**
 * Basic Sizes.
 */
let thisWidth = 640
let thisHeight = 480
if (typeof window !== `undefined`) {
  thisWidth = window.innerWidth
    || document.documentElement.clientWidth
    || document.body.clientWidth

  thisHeight = window.innerHeight
    || document.documentElement.clientHeight
    || document.body.clientHeight
}
export const Width = thisWidth
export const Height = thisHeight
```
Simply kept in a `Constants.js` and imported when needed this worked for me before - though your Hook approach already has a built in `onResize` which this approach misses (perhaps only add the two  `clientHeight`s / `clientWidth`s to it for `size.width` & `size.height` - so that it will work in IE11 & Safari as well : ).

Should one of the approaches suffice (perhaps I should simply add them to the READMEs), feel free to close it, @Frannsoft : ). Should feature parity with `gatsby-image` be of importance, then I'd be willing to have a look, maybe I come up with something without having to refactor the image handling function ; ).

Best,

Tim.

**Comment by Frannsoft** [comment]
Awesome, thanks!
