### ISSUE TITLE
Add Tag support for gatsby's 'Link'?

### ISSUE THREAD

**Issue by fraserisland** [timhagn/gatsby-background-image#48]
## Summary

Title says it all, would this be possible? If you think it is, i'm more then happy to help out and try implement this.

**Comment by timhagn** [comment]
Hi @fraserisland,

mkay, I _think_I get where you're heading at (Buttons and such?), but a little more elaboration bout your idea would be great ; ).
Do you want to use `gbi` as a HOC or which places for it to go do you have in mind? Definitely no ridicule meant, am really curious about your idea : ).

Best,

Tim.

**Comment by timhagn** [comment]
Hi @fraserisland,
should you still be interested to elaborate a little more where you wanted to head with this issue, give me a shout. As ProBot didn't act, I'm marking this as `Stale?` now and soon am gonna close it.
Best,
Tim.

**Comment by timhagn** [comment]
Hi @fraserisland,

as I already wrote before and in #52 as well, shouldn't you deign to answer during the weekend, I'm going to close this issue, as using React Components as `Tag` definitely goes beyond the scope of this package and you can easily wrap a `<BackgroundImage />` in a `Link`.
Definitely no offense meant, I just have to "get rid" of non essential issues, as I'm starting some new projects next week.

Best,

Tim.

**Comment by timhagn** [comment]
As written before, just have to close this for now without further information.

Though all the best,

Tim.
