### ISSUE TITLE
Breaks if no ClassName prop is added.

### ISSUE THREAD

**Issue by drobinhood** [timhagn/gatsby-background-image#5]
I get a type error when no className prop is added. Adding an empty className="" prop seems to fix it.

`TypeError: Cannot read property 'includes' of undefined

**Comment by timhagn** [comment]
Ah, OK, thanks for pointing this out. That's the working of `getBackgroundStyles()` in [BackgroundUtils.js](/timhagn/gatsby-background-image/blob/master/src/BackgroundUtils.js), how could I miss that oO.
Gonna look into it - or feel free to open a PR ; ).

**Comment by timhagn** [comment]
Hi @drobinhood, would you mind testing version `0.2.2`? Should be fixed now (including further checks).

**Comment by timhagn** [comment]
As it should be working now, would you mind testing `0.2.3` @drobinhood ?
Would like to close this issue ; ).

**Comment by timhagn** [comment]
As all the tests are running, I'm closing this issue as solved.
Should a problem arise, I'm happy to go into it : ).
