### ISSUE TITLE
On initial page load in production, only traced SVG is briefly displayed.

### ISSUE THREAD

**Issue by hkolsen** [timhagn/gatsby-background-image#51]
Hi 👋 really love this plugin, thank you for your work on it. Did come across an issue today and would appreciate any help you can provide!

## Description

Found an interesting bug that prevents the actual background image to display on first page load. If I navigate away from the page and come back, the image displays as expected.

When looking under the hood, I see this on my production build:
```
<div class="gatsby-image-wrapper">
<style>...</style>
<noscript>
<style>
.sc-laTMn.hcSsrm:before {
   opacity: 1;
   background-image: url('/static/7aa040dc05327e4365a7ceb001e869d2/883ab/hero-img.jpg');
}</style>
</noscript>
{children}
</div>
```

Whereas locally, I see the following code:
```
<div class="gatsby-image-wrapper">
::before
<style>...</style>
<noscript></noscript>
{children}
</div>
```

It appears that the style in `<noscript>` is not inserted correctly on page load. Any thoughts on how to resolve this? I have another Gatsby site that uses this plugin and do not have the same issues. ¯\_(ツ)_/¯

### Steps to reproduce

Locally the background images load as expected, but after building the static site the background image only displays the traced placeholder SVG briefly before displaying the background color. This happens in both mobile and desktop, across all browsers.

### Environment

```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /var/folders/wx/d6kmj0_s4r7cw452rl6lkp_00000gn/T/yarn--156349
5919334-0.7470076285424669/node
    Yarn: 1.17.3 - /var/folders/wx/d6kmj0_s4r7cw452rl6lkp_00000gn/T/yarn--156349
5919334-0.7470076285424669/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.0.66 => 2.13.15
    gatsby-background-image: ^0.8.0 => 0.8.0
    gatsby-image: ^2.0.23 => 2.2.5
    gatsby-plugin-create-client-paths: ^2.0.5 => 2.1.2
    gatsby-plugin-extract-schema: ^0.0.5 => 0.0.5
    gatsby-plugin-google-analytics: ^2.0.19 => 2.1.2
    gatsby-plugin-manifest: ^2.0.29 => 2.2.2
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3
    gatsby-plugin-netlify: ^2.0.15 => 2.1.1
    gatsby-plugin-netlify-cms: ^3.0.18 => 3.0.18
    gatsby-plugin-offline: ^2.0.24 => 2.2.2
    gatsby-plugin-prefetch-google-fonts: ^1.4.0 => 1.4.2
    gatsby-plugin-react-helmet: ^3.0.4 => 3.1.1
    gatsby-plugin-react-svg: ^2.1.0 => 2.1.1
    gatsby-plugin-sharp: ^2.2.8 => 2.2.8
    gatsby-plugin-styled-components: ^3.0.6 => 3.1.1
    gatsby-plugin-typescript: ^2.0.13 => 2.1.1
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.1.1
    gatsby-remark-images: ^3.0.11 => 3.1.4
    gatsby-remark-relative-images: ^0.2.1 => 0.2.2
    gatsby-source-filesystem: ^2.0.31 => 2.1.4
    gatsby-source-instagram-all: ^2.0.5 => 2.0.5
    gatsby-transformer-remark: ^2.6.6 => 2.6.6
```

**Comment by timhagn** [comment]
Hi @hkolsen,

thanks for bringing this to my attention, though I ain't able to think about a cause for your issue's behavior from the top of my head : /. Especially since you mentioned not running into this with another Gatsby Site ^^. The only thing that comes to mind might be different dependency versions of `gatsby` and it's plugins for your two cases; from which was your `gatsby info`?

Would it be possible for you to let me have a look at your specific case / repo? Wasn't able to replicate it on my machine (Linux one) or a MacOS VM at the moment...

Thanks in advance, best,

Tim.

**Comment by hkolsen** [comment]
Hi @timhagn! I apologize for the delay in responding, the team and I were able to figure out the issue. There was a `styled-components` dependency that prohibited the `displayName` to be prefixed in the class, which appears to have caused the issue. (i.e. instead of `<div class="ComponentName_1mpnmaj"></div>` it was just `<div class="1mpnmaj"></div>`

In case anyone is having a similar issue, here is my Gatsby info after the issue being resolved:
```
 System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /var/folders/wx/d6kmj0_s4r7cw452rl6lkp_00000gn/T/yarn--156469
4534565-0.8361153830650874/node
    Yarn: 1.17.3 - /var/folders/wx/d6kmj0_s4r7cw452rl6lkp_00000gn/T/yarn--156469
4534565-0.8361153830650874/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.0.66 => 2.8.2
    gatsby-background-image: ^0.5.0 => 0.5.9
    gatsby-image: ^2.0.23 => 2.1.2
    gatsby-plugin-client-side-redirect: ^0.0.2 => 0.0.2
    gatsby-plugin-create-client-paths: ^2.0.5 => 2.0.5
    gatsby-plugin-extract-schema: ^0.0.5 => 0.0.5
    gatsby-plugin-google-analytics: ^2.0.19 => 2.0.20
    gatsby-plugin-manifest: ^2.0.29 => 2.1.1
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3
    gatsby-plugin-netlify: ^2.0.15 => 2.0.17
    gatsby-plugin-netlify-cms: ^3.0.18 => 3.0.18
    gatsby-plugin-offline: ^2.0.24 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.12
    gatsby-plugin-react-svg: ^2.1.0 => 2.1.1
    gatsby-plugin-sharp: ^2.0.35 => 2.1.3
    gatsby-plugin-styled-components: ^3.0.6 => 3.0.7
    gatsby-plugin-typescript: ^2.0.13 => 2.0.15
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.0.13
    gatsby-remark-images: ^3.0.11 => 3.0.14
    gatsby-remark-relative-images: ^0.2.1 => 0.2.2
    gatsby-source-filesystem: ^2.0.31 => 2.0.38
    gatsby-source-instagram-all: ^2.0.5 => 2.0.5
    gatsby-transformer-remark: ^2.3.10 => 2.3.12
```

**Comment by timhagn** [comment]
Hi @hkolsen / Heidi,

great you and your team could figure it out! And yup, then `gbi` couldn't have made hands and tails out of it (especially in the lower `0.5.0` version range % ). Should this really be resolved for you (did you already try it with the just published `v0.8.3`?), you of course have the honors of closing this issue - though perhaps you might mention which `styled-components` dependency really did the trick, as the Gatsby plugin of it is still at the same version in your `gatsby info` ; ).

Best,

Tim.

**Comment by hkolsen** [comment]
Hi Tim!

The specific dependency was `babel-plugin-styled-components` and we had to revert to previous versions of recently updated plugins to resolve the conflict. It was a bit of a mess but happy to help someone if they find themselves in the same situation!

Just upgraded to the latest version of `gatsby-background-image` and all is well, thanks again for a 💯 plugin!

**Comment by timhagn** [comment]
Hi Heidi,

gonna refer anyone to this issue if they find themselves in such a situation (am rather the kinda guy of quickly iterating to the newest versions - and yup, this brought me into deep troubles before ; ).

Thanks again for the flowers : )!

Best,

Tim.
