### ISSUE TITLE
Trouble getting multiple background images to work

### ISSUE THREAD

**Issue by SceptreData** [timhagn/gatsby-background-image#53]
## Summary

I'm trying to get multiple background images to work using the example code found [here].(https://www.gatsbyjs.org/packages/gatsby-background-image/#acknowledgements)

But it isn't working! React is telling me that the fluid prop is expecting an object, not an array.

## Relevant information
Here is the error message I'm getting: 
Warning: Failed prop type: Invalid prop fluid of type array supplied to BackgroundImage, expected object.
    in BackgroundImage (at Background.js:38)
    in MultiBackground (created by Context.Consumer)

and here is a hastebin link to what I assume is the [relevant code](https://hastebin.com/camoxasama.js).

Any idea what I'm doing wrong? Thanks in advance!

**Comment by timhagn** [comment]
Hi @SceptreData,

would you be so kind and give me your `gatsby info`? The code looks correct at first glance,
though it's sadly not enough to go from. You error shouldn't usually happen as the propType is declared as:
```js
...
  fluid: PropTypes.oneOfType([
    fluidObject,
    PropTypes.arrayOf(PropTypes.oneOfType([fluidObject, PropTypes.string])),
  ]),
...
```

Best,

Tim.

**Comment by SceptreData** [comment]
Hi Tim! Thanks for getting back to me so fast. A quick look at my gatsby info revealed that I had somehow installed a much older version of the package, 0.6.2. 

npm update / npm install did not upgrade the package like I thought it would (Even after checking to make sure my package-lock and package.json weren't holding things back).

I finally got it to work after npm uninstalling the package, then reinstalling. I'm not too sure why the update didn't work, or how I ended up with 0.6.2 in the first place.

Thanks again for the quick response! I think it's safe to close the issue now.
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.7.3 => 2.13.37
    gatsby-background-image: ^0.6.2 => 0.6.2
    gatsby-cli: ^2.7.19 => 2.7.19
    gatsby-image: ^2.1.0 => 2.2.6
    gatsby-plugin-manifest: ^2.1.1 => 2.2.4
    gatsby-plugin-netlify: ^2.0.17 => 2.1.3
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-netlify-cms: ^4.0.0 => 4.1.6
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.2
    gatsby-plugin-sass: ^2.0.11 => 2.1.3
    gatsby-plugin-sharp: ^2.0.37 => 2.2.9
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.1.3
    gatsby-remark-images: ^3.0.11 => 3.1.7
    gatsby-remark-prismjs: ^3.2.9 => 3.3.3
    gatsby-remark-relative-images: ^0.2.2 => 0.2.2
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.2.4
    gatsby-remark-smartypants: ^2.0.9 => 2.1.2
    gatsby-source-filesystem: ^2.0.36 => 2.1.6
    gatsby-transformer-json: ^2.1.11 => 2.2.2
    gatsby-transformer-remark: ^2.3.12 => 2.6.9
    gatsby-transformer-sharp: ^2.1.19 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.7.19
