### ISSUE TITLE
Trying to make my Gatsby page scrollable while using gatsby-bg-image

### ISSUE THREAD

**Issue by fullspectrumprocessing** [timhagn/gatsby-background-image#54]
## Summary
Hello. I am using gatsby-background-image for the first time in a project. I really like how it makes it easy to use Gatsby-image to render my BG image. However when I use it, it pretty much stops my page from scrolling and "locks" all my other components up( components that extend past the viewport can't be seen or scrolled to. The way i set up gatsby-bg-image might not be the best but I got it working up until this point. Just need some help getting the page to scroll while still using gatsby-bg-image component. 
## Relevant information

**So pretty much I have a Gatsby Starter that has two pages. In both pages I have a Layout component, which is below, that is wrapping both contents of the pages. The contents of each page are being passed as props to the parent Layout component**  
Below layout.js I added one of the pages just so you can see what's being passed to Layout
> layout.js
```
import React from "react"
import PropTypes from "prop-types"
import StyledBGImage from '../components/bgimage'
import Header from "./header"
import '../styles/layout.scss'
import Footer from '../components/footer'
import styled from 'styled-components'
import SideDrawer from '../components/sidedrawer'
import DrawerOverlay from '../components/draweroverlay'

const Overlay = styled.div`
  width: 100vw;
  height: 100vh;
  background: linear-gradient( rgba(250, 230, 230, 0.43), rgba(220, 230, 180, 0.54));
`

class Layout extends React.Component {
  state = {
    sideDrawerOpen: false
  }

  handleDrawer = () => {
    // e.preventDefault()
    // this.setState({content: !this.state.content})\
    this.setState(prevState => {
      return { sideDrawerOpen: !prevState.sideDrawerOpen }
    })
    console.log('clicked');
    console.log(this.state, 'state')
  }

  handleDrawerOverlay = () => {
    this.setState({
      sideDrawerOpen: false
    })
    console.log(this.state, 'state')
  }

  render() {

    const { children } = this.props
    let overlay
    if (this.state.sideDrawerOpen) {
      overlay = <DrawerOverlay click={this.handleDrawerOverlay} />
    }
    return (
      <>
        <StyledBGImage>
          <Overlay>
            <Header click={this.handleDrawer} />
            <SideDrawer show={this.state.sideDrawerOpen} click={this.handleDrawerOverlay} />
            {overlay}
            <div>
              <main>{children}</main>
            </div>
          </Overlay>

        </StyledBGImage>
        <Footer />
      </>
    )
  }
}

Layout.propTypes = {
  children: PropTypes.node.isRequired,
}
export default Layout
```

> index.js
```
import React from 'react'
import Layout from '../components/layout'
import SEO from '../components/seo'
import '../styles/landing.scss'

const Landing = () => (
  <Layout>
    <SEO title='Landing Page' />
    <div id='landingText'>
      <h3> we are</h3>
      <h1>CBD</h1>
      <h2>wellness</h2>
    </div>
    <button id='explore'>
      explore our line >
            </button>
  </Layout>
)
export default Landing
```

> page-2.js
```
import React from "react"
import { Link } from "gatsby"
import Layout from "../components/layout"
import SEO from "../components/seo"
const SecondPage = () => (
  <Layout>
    <SEO title="Page two" />
    <h1>Page 2</h1>
    <p>Welcome to page 2</p>
    <Link to="/">Go back to the homepage</Link>
    {` `}
    <h1>Page 2</h1>
    <p>Welcome to page 2</p>
    <Link to="/">Go back to the homepage</Link>
    {` `}
    <h1>Page 2</h1>
    <p>Welcome to page 2</p>
    <Link to="/">Go back to the homepage</Link>
    {` `}
    <h1>Page 2</h1>
    <p>Welcome to page 2</p>
    <Link to="/">Go back to the homepage</Link>
  </Layout>
)

export default SecondPage

```

As you can see I have the gatsby-background-image as 'StyledBGImage' wrapped around the whole layout component. This is how I got the BG image lazy loading behind each page correctly. But the way its setup won't allow me to scroll down the page. Below I'll include my gatsby-background-image component which contains the queries and styling for the image. I tried following the docs as much as I can and I got it working but just cant figure out how to make the page scroll while still using the gatsby-bg-image component. 

> bgimage.js
```
import React from "react"
import { StaticQuery, graphql } from "gatsby"
import styled from 'styled-components'
import BackgroundImage from 'gatsby-background-image'
// Use the following to support legacy browsers like IE11:
// import BackgroundImage from 'gatsby-background-image-es5'
import { generateMedia } from 'styled-media-query'

const media = generateMedia() //for media queries see styled BGImage component at bottom
/**
 * In this functional component a <BackgroundImage />  is compared to an <Img />.
 * @param className   string    className(s) from styled-components.
 * @param children    nodes     Child-components from index.js / page-2.js.
 * @return {*}
 * @constructor
 */
/*
 * This component is built using `gatsby-image` to automatically serve optimized
 * images with lazy loading and reduced file sizes. The image is loaded using a
 * `useStaticQuery`, which allows us to load the image from directly within this
 * component, rather than having to pass the image data down from pages.
 *
 */
const BgImage = ({className, children}) => (
  <StaticQuery query={graphql`
    query {
      placeholderImage: file(relativePath: { eq: "landing_bg.jpg" }) {
        childImageSharp {
          fluid(quality: 90, maxWidth: 4160) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  `}
  render ={data => {
    const imageData = data.placeholderImage.childImageSharp.fluid
    return (
      <StyledWrap>
        <BackgroundImage
        Tag='section'
        className={className}
        fluid={imageData}
        backgroundColor={'#040e18'}
        title='HempUpBG'
        id='BG'
        role='img'
        fadeIn={'soft'}
        aria-label={'hempupbg'}
        // You are able to set a classId and style by wrapper (see below or
              // https://github.com/timhagn/gatsby-background-image/#styling--passed-through-styles):
              // classId=" "
              // style={{
              //   // Defaults are overwrite-able by setting one of the following:
              //   // backgroundSize: '',
              //   // backgroundPosition: '',
              //   // backgroundRepeat: '',
              // }}
        >
          {children}
        </BackgroundImage>
      </StyledWrap>
    )
  }}
 />
)

const StyledWrap  =styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  overflow: hidden;
`
const StyledBGImage = styled(BgImage)`
  width: 100vw;
  // !These three crucial styles (if existing) are directly parsed and added to
  // !the pseudo-elements without further ado (except when overwritten).
  //background-repeat: repeat-y;
  //background-position: left center;
  //background-size: cover;

  // !With media-queries you have to overwrite the default options (see style={{}} above).
  // ${media.lessThan('large')`
  //   background-size: cover;
  //   &:after, &:before {
  //     background-size: contain;
  //   }
  // `}
  
  // !For pseudo-elements you have to overwrite the default options (see style={{}} above).
  // !See: https://github.com/timhagn/gatsby-background-image/#styling--passed-through-styles 
  //&:after, &:before {
  //   background-clip: content-box;
  //   background-size: contain;
  //}
`
export default StyledBGImage
```

### Environment 
```
System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.13.25 => 2.13.25
    gatsby-background-image: ^0.8.0 => 0.8.0
    gatsby-cli: ^2.7.15 => 2.7.15
    gatsby-image: ^2.2.6 => 2.2.6
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sass: ^2.1.3 => 2.1.3
    gatsby-plugin-sharp: ^2.2.7 => 2.2.7
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-source-filesystem: ^2.1.5 => 2.1.5
    gatsby-transformer-sharp: ^2.2.3 => 2.2.3
  npmGlobalPackages:
    gatsby-cli: 2.7.15


```

### File contents (if changed)

`package.json`: 
`"dependencies": {
    "babel-plugin-styled-components": "^1.10.6",
    "gatsby": "^2.13.25",
    "gatsby-background-image": "^0.8.0",
    "gatsby-image": "^2.2.6",
    "gatsby-plugin-manifest": "^2.2.3",
    "gatsby-plugin-offline": "^2.2.4",
    "gatsby-plugin-react-helmet": "^3.1.2",
    "gatsby-plugin-sass": "^2.1.3",
    "gatsby-plugin-sharp": "^2.2.7",
    "gatsby-plugin-styled-components": "^3.1.2",
    "gatsby-source-filesystem": "^2.1.5",
    "gatsby-transformer-sharp": "^2.2.3",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-headroom": "^2.2.8",
    "react-helmet": "^5.2.1",
    "react-spring": "^8.0.27",
    "styled-components": "^4.3.2",
    "styled-media-query": "^2.1.2"
  },`

I added this screen shot trying to show how the contents of page 2 (which I  included the code for above) extends pass the viewport but I can't access it by scrolling or any other method the way I have the components set up now. It's like what ever is wrapped inside the BG component is stuck there. Is there a better way to set my my components with gatsby-background-image so that I can still use the component and be able to scroll through the pages.  I tried playing with the <BackgroundImage/> style properties to no avail. Would love some help with this. If you need more code please let me know. 
[Repo]( https://github.com/fullspectrumprocessing/HempUP-Gatsby.git)

![Layer 1](https://user-images.githubusercontent.com/52926072/61908843-99fe0b00-aefe-11e9-870a-f002e99f14ec.png)

**Comment by timhagn** [comment]
Hi @fullspectrumprocessing,

from the top of my head I'd guess your problem might be not be created by `gbi`, but instead by your
```js
const StyledWrap  =styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  overflow: hidden;
`
```
which pretty much would fix the Wrapper to just one page...
Cloning your repo anyhow to see if I'm shooting in the right direction ; ).
Gonna get back to you afterwards.

Best,

Tim.

**Comment by fullspectrumprocessing** [comment]
Hey Tim I just fixed the link error the repo was private but it should be accessible for now. I'll go ahead and try your above solution and see if it works. Let me know if you find out anything else. I really appreciate your swift response! thank you

**Comment by timhagn** [comment]
Thanks @fullspectrumprocessing, already cloned it, so you can privatize it again ; ). But sadly I gotta jump now, so shouldn't your problem be solved with my initial intuition, I'm gonna have a look at it tomorrow : ).

Fingers crossed and best wishes,

Tim.

**Comment by fullspectrumprocessing** [comment]
Okay thanks Tim!! lets keep in touch. I;ll go ahead and make those edits now. I'm thinking about adding React-spring's Parallax component to get a cool scrolling effect with the gbi in the background. I'll let you know if i figure it out in the meantime. Thanks again!!

**Comment by fullspectrumprocessing** [comment]
Hey Tim I think i found a cool solution using react springs Parallax. Give the repo another look and let me know what you think.

**Comment by timhagn** [comment]
Hi @fullspectrumprocessing,

have definitely not forgotten bout you, just had too many meetings to prepare for - great for me, though not for this package at the moment. Gonna try to squeeze in some time tomorrow to check out the Parallax branch : ).

Best,

Tim.

**Comment by fullspectrumprocessing** [comment]
No Problem Tim!! Keep working hard over there and there's is no pressure on this side. Just switched over to some other problems in the mean time lol. You know how it never ends. I really appreciate you though and this package. And yes check it out when you get a chance. react-Spring is really cool and their parallax feels very realistic. Hope your meetings are going well. Keep grindin'!! 
¯\_(ツ)_/¯

**Comment by timhagn** [comment]
Thanks for your understanding & sympathy, ... uhm, what's your name, if I might ask? Typing @fullspectrumprocessing all the time seems a little impersonal to me ^^. And thanks for the wishes, the meeting today went quite fruitful, next one's probably on Wednesday, that one already payed for : ).

**Comment by fullspectrumprocessing** [comment]
Ayyy congrats on that!! Are you working as a contractor or freelance right now?? Also,  My name is Avery-Dante. This is my work gitHub account at this new job I started. This is actually my first professional development jon. My personal acct. is @thelovesmith . I'm Building this website for my job and they want it to look state-of-the-art lol so im pulling together all the new tech I've been working with these last few months.  I'll make sure to follow you from my personal account too.

**Comment by timhagn** [comment]
Thanks a lot, Avery-Dante! Freelance subcontractor on the one mentioned (RN) + full freelance on a probable second one (with "freedom / weapon of choice" on frameworks, speaking Gatsby ; ). Congrats on the new job and you just got yourself a new follower : ).

**Comment by fullspectrumprocessing** [comment]
Man that is amazing!! I hope to one day be able to work for myself or even a smaller company of devs working together. And yes Freedom of choice, i recently realized, makes such a big difference.  I am completely in love with Gatsby and GraphQL. trying to persuade our team over here to use it as much as possible lol. And thank you Tim! Devs like yourself continue to inspire and motivate me to work harder and reach towards independence. Make sure you get some rest bro, I have bad insomnia and just started using CBD to get sleep and it makes coding the next day so much easier lol (less punching my computer screen)  Lets stay in touch!!

**Comment by timhagn** [comment]
Hi again @fullspectrumprocessing / Avery-Dante : )!

Though I still didn't find the time to look at your repo, it might quite be that with publishing `v0.8.3` (solving #57) your issue might be solved as well. Had a remnant of the time `gbi` was still an "offspring" of `gatsby-image` (see the [Acknowledgements](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#acknowledgements) section in its README), `overflow: 'hidden'` defaulted to. This could explain your issue with scrolling % ).
Would you try perhaps be so kind to try it?

And btw. though I'm definitely open to talk about personal stuff with you, GitHub just doesn't seem to be the right forum for it to me (find my E-Mail Address in my website's Imprint / "Impressum" ; ).

And thanks a lot for the Flowers, am just not that good at receiving compliments % |...

Hope your issue is rectified by the new publication - and of course reading from you in my Inbox : ).

Best (and I feel thee @ your insomnia) and definitely let's keep in touch,

Tim.

**Comment by timhagn** [comment]
Hi @fullspectrumprocessing / Avery-Dante,

finally came round to have a look at your repo, much seems to have happened oO!
But before I pulled your newest changes I quickly tested if `v0.8.3` would perhaps solve the scrolling problem and it seems it did, indeed (didn't change a thing beforehand).

One thing to mention: in your newest sources you import `NavDesktopSubMenu` from `NavDesktopSubMenu.js` while it's called `NavDesktopSubmenu.js` ; ).

Should your issue be solved either way, you of course may have the honors of closing it : ).

Best,

Tim.

P.S.: Still awaiting a mail from you % ).

**Comment by timhagn** [comment]
Hi @fullspectrumprocessing / Avery-Dante,

as there not even seems to be any action on your repo, I'm gonna close this for now, it seems solved.

Best,

Tim.
