### ISSUE TITLE
Consecutive images with the same source cause the first one to not load until user scrolls

### ISSUE THREAD

**Issue by KB1RD** [timhagn/gatsby-background-image#55]
## Description

When I place two `BackgroundImage`s consecutively, the first one will only load once the second one has been scrolled to in a **production build**.

### Steps to reproduce

Place two images a fair distance apart consecutively on a page with the same fluid source like so:
```jsx
<BackgroundImage
  style={{width: '100%', height: '100vh'}}
  fluid={backgroundFile.childImageSharp.fluid}
/>

<div
  style={{width: '100%', height: '100vh'}}
/>

<BackgroundImage
  style={{width: '100%', height: '100vh'}}
  fluid={backgroundFile.childImageSharp.fluid}
/>
```
...assuming `backgroundFile` is populated by a GraphQL query with the Sharp image.
Then run `npm run build` and `npm run serve`.

### Expected result

At least the top image should load when in the viewport.

### Actual result

The top image only loaded once the bottom image was in the viewport

### Environment
```
  System:
    OS: Linux [redacted other info]
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    [redacted]
  npmPackages:
    gatsby: 2.13.41 => 2.13.41
    gatsby-background-image-es5: ^0.8.0 => 0.8.0
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-manifest: 2.2.4 => 2.2.4
    gatsby-plugin-postcss: 2.1.2 => 2.1.2
    gatsby-plugin-purgecss: 4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: 3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-directus7: ^0.8.1 => 0.8.1
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.7.0
```

**Comment by timhagn** [comment]
Hi @KB1RD,

thanks for noticing, this completely slipped through the cracks as I solved issue #29 ^^!
Your issue was an easy one to fix (though `lerna` wouldn't want to let me publish `gbi-es5` at first, but that's another story % ).
Simply had to add the `randomAnswerToLifeTheUniverseAndEverything` (yeah, the pun was worth the additional few bits ; ) to the "uniquely hashed" class added when multiple `<BackgroundImage />`s with the same styling / classNames are added to a single page like thus:
```js
  // Really just the answer to issue #55 ; ).
  const randomAnswerToLifeTheUniverseAndEverything = Math.round(
    Math.random() * 42
  )

  // Create random "uniquely hashed" additionalClass if needed.
  const randomClass = ` gbi-${hashString(
    (imageData && imageData.srcSet) || className
  )}-${randomAnswerToLifeTheUniverseAndEverything}`

  // Should an element exist, add randomized class.
  const additionalClass = elementExists ? randomClass : ``
```  
Published with `v0.8.2` of both `gbi` and `gbi-es5`, at least at my place it's working now, would you mind testing it on your side : )?

Best,

Tim.

**Comment by KB1RD** [comment]
@timhagn problem solved, thank you for the fast response! (yes, the pun is worth the extra 10 bytes or so :P )

**Comment by timhagn** [comment]
Hi @KB1RD,

yeay, and thanks for your ultra-fast response : )! I usually don't quote myself, though `Surrender all hope, humor dies last!` is quite fitting at the moment ^^.

Have a nice weekend, I'm done for the day (`lerna` aggrieved me too much and it's fucking hot here anyhow ; ).

Best,

Tim.

P.S.: Nice Profile pic, btw. owls of the world, unite (at night ^^)!
