### ISSUE TITLE
Same image when looping through array and using same className

### ISSUE THREAD

**Issue by philonor** [timhagn/gatsby-background-image#56]
## Description

When having an array of images and looping over them using `.map`, everyone displays the same first image on build as they are having the same CSS selectors.

### Steps to reproduce

```
    return <>
      {row.map((el, index) => {
       <BackgroundImage className="cover h-100" fluid={el.image.fluid}/>
      })}
    </>
```

results in the following `<style/>` tag for every instance with a duplicate `.cover.h-100` selector that is not unique.

```

          .cover.h-100:before,
          .cover.h-100:after {
            content: '';
            display: block;
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            
            transition: opacity 0.5s ease 500ms;
            background-position: center;
background-repeat: no-repeat;
background-size: cover;

          }
          .cover.h-100:before {
            z-index: -100;
            background-image: url(..); /*Contains correct unique image url*/
            
            opacity: 1; 
          }
          .cover.h-100:after {
            z-index: -101;
            
            background-image: url(..); /*Contains correct unique base64*/
          }
        
```

### Expected result

Every instance should have a unique CSS selector as described [here](https://www.gatsbyjs.org/packages/gatsby-background-image/#multiple-instances-of-same-component). The `gbi-...` class and selector is actually present in the `<noscript/>`'s `<style/>` tag, but not within the normal `<style/>` tag.

### Actual result

All instances share same CSS selector and hence show same first image (as the first takes precedence).
When adding another unique class, everything works fine, e.g.
```
    return <>
      {row.map((el, index) => {
       <BackgroundImage className={`cover h-100 unique-${index}`} fluid={el.image.fluid}/>
      })}
    </>
```

### Environment

```

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v11.15.0/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
  Languages:
    Python: 2.7.15 - 
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.2
  npmGlobalPackages:
    gatsby-cli: 2.6.5
```
```
    "gatsby-background-image": "^0.8.2",
```

**Comment by timhagn** [comment]
Hi @philonor (& @dimroth),

thanks for pointing this out and the great summary, this seems  at first like a case the detection method doesn't seem to cover, but then I'm a little astounded, it works for the `noscript` tag oO. Gonna try to squeeze in some time tomorrow to have a look, hope this ain't a too hard one to solve, as I'm quite busy at the moment - good for me, though not for the package % ).

Best,
Tim.

P.S.: Any help would be appreciated, of course : ).

**Comment by jimmed** [comment]
I think I'm experiencing the same issue via a less direct route.

Instead of using BackgroundImage directly within a loop, I am using BackgroundImage inside another component, which I am then rendering multiple instances of in the page.

Unfortunately this is occurring only in production on a project that is not ready for public release, so I can't share the underlying code, but this is the general idea:

#### Wrapper component around BackgroundImage
```ts
const ImageWrapper = ({ imageData }) => (
  <...>
    <BackgroundImage fluid={imageData.fluid} />
  </...>
)
```

#### Hook which grabs images from a static query
```ts
const useImage = (name) => {
  const allImages = useStaticQuery(...)
  return images.find(/* where image matches name */)
```
  
#### Images used in a page
```ts
const Page = () => {
  const imageA = useImage('a')
  const imageB = useImage('b')
  const imageC = useImage('c')

  return (
    <...>
      <ImageWrapper imageData={imageA.fluid} />
      ...
      <ImageWrapper imageData={imageB.fluid} />
      ...
      <ImageWrapper imageData={imageC.fluid} />
    </...>
  )
```

The outcome is that the final ImageWrapper will render image A, instead of image C. This only occurs in the production build, not in the development build.

**Comment by jimmed** [comment]
On further inspection, it looks like only the final image is receiving a unique `gbi-*` className -- this also occurs within the `<style>` block rendered in production, hence the first image also appearing in the final panel.

#### All but final image

![First image](https://user-images.githubusercontent.com/318961/62382293-2d5dbe80-b545-11e9-8b07-ccd48599dec6.png)

Notice the lack of `gbi-` class in both the `<div>` and the `<style>`

#### Final image

![image](https://user-images.githubusercontent.com/318961/62382354-4c5c5080-b545-11e9-8d3e-15f7a3b759fd.png)

**Comment by jimmed** [comment]
Just a note to say that I too worked around this by injecting an additional unique className into each instance. Everything's working fine again!

Thanks for a fantastic library!

**Comment by paulgaumer** [comment]
Thank you so much guys, I have been pulling my hair on this bug for the past few days! Applied the above fix, every works now! 🙏

**Comment by timhagn** [comment]
Gonna look into it tomorrow, today (Friday) is /was my 11th wedding anniversary / non church related ; ). What about simple React `keys`? That might solve the problem of production builds, methinks...

**Comment by pqt** [comment]
@timhagn have you been able to get any movement on this? Would love to see a quick resolution. It's the only (obvious) bug to my site that viewers would run into frequently.

**Comment by timhagn** [comment]
Hi all,

sadly I didn't find the time this weekend to get anything done for `gbi`, as Saturday I was feeling the "aftermath" of our Anniversary (we "partied" quite heavily ; ). And today I had to prepare my Laptop for the freelance Gig I'm starting on tomorrow. And stupid of me, React `key` won't work of course, as it's a protected config variable not accessible via `props`. 
And @pqt a few comments above their's a workaround which seems to work for the moment.

But definitely didn't forget about it : )!

Best,

Tim.

**Comment by timhagn** [comment]
Hi again, all,

have quite a hefty week behind me but managed to give it a look today. Didn't come up with a solution in the short time I had this weekend (now working the Gig and having a second freelance Project to look after % ), but methinks it might have to do with the handling of `componentClassCache` in `StyleUtils.js`, which is a simple boolean at the moment. Perhaps we have to cache the generated & randomized additional class as well to it in `fixClassName()`...

Should anyone have the time to give it a look and either open a PR or point me in a possible direction I'd definitely be wholeheartedly thankful (and the thought about adding `AllContributors` still ain't of the table ; ).

Best,

Tim.

**Comment by jimmed** [comment]
Thanks for your ongoing work on this @timhagn! My new (gatsby-background-image-powered) website is going live this morning, so once that happens I might be able to look at fixing this myself. Stay tuned for a PR!

**Comment by timhagn** [comment]
Hi @jimmed,

did you get a chance to gaze at it? Gonna try coming round doing some work of it today, no promises, though - so any help would be greatly appreciated : ).

Best,

Tim.

**Comment by timhagn** [comment]
Hi all,

I just published `gbi(-es5)` @ `v0.8.4`, which should rectify these problems (at least it does on my side for built sites ; )! Would one of you be so kind as to test it : )? 

For those of you who wanna know, that was definitely "mea culpa", cause as I solved issue #55, I added the following to `fixClassNames()`:

```js
// Really just the answer to issue #55 ; ).
const randomAnswerToLifeTheUniverseAndEverything = Math.round(Math.random() * 42)
```

Rectified it now by adding an additional `state` variable `addedClassName` which stores the randomized class now returned from `fixClassNames()` and changed the above to:

```js
// Really just the answer to issue #55 ; ).
const randomAnswerToLifeTheUniverseAndEverything = addedClassName
  ? addedClassName
  : Math.round(Math.random() * 42)
```

That was a really stupid one, but what the heck ^^. Hope it's now working for you all : )!

Thanks for all the input!

Best,

Tim.

**Comment by timhagn** [comment]
And now we are at `v0.8.5` solving #50, too : ).

**Comment by pqt** [comment]
Thank you @timhagn, this library is fantastic. Just want to say that your work is greatly appreciated.

**Comment by timhagn** [comment]
Aww, thanks a lot, @pqt : )!

Then the only question remaining is, does @philonor want to have the honors of closing this issue as OP, or shall I in the course of this week ^^?

**Comment by jimmed** [comment]
@timhagn sadly like the cleaning of a house, or the mowing of a lawn, the work on a website never actually ends! Thanks so much for the fix; I'll test it out as soon as I get the chance

**Comment by timhagn** [comment]
@jimmed Don't start a (rather) positive sentence with "sadly" oO... Though you're quite right, no project is ever "done" it seems ^^. Have phun testing, hope (and am rather sure of, meanwhile) it works : )!

**Comment by philonor** [comment]
> Aww, thanks a lot, @pqt : )!
> 
> Then the only question remaining is, does @philonor want to have the honors of closing this issue as OP, or shall I in the course of this week ^^?

Thanks a lot for fixing! I'll close as offered. ;) Thanks for your work on the library again!
