### ISSUE TITLE
Why overflow:hidden?

### ISSUE THREAD

**Issue by tremby** [timhagn/gatsby-background-image#57]
I see the container has been styled with `overflow: hidden` since the initial commit. What's the reason?

It doesn't seem to make any visual difference for me, and I have to override it to get the styling I want in a particular case.

I find I have to do `!important`, which I'd rather not do. The readme says it's styleable with styled-components but the inline `overflow: hidden` is overriding my `overflow: visible`.

Wondering if it's to help with an IE bug or some such.

**Comment by timhagn** [comment]
Hi @tremby / Bart,

oh, you're completely right, should take it out - this is a remnant of `gbi`'s beginnings as stated in the [README's Acknowledgements Section](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#acknowledgements) - and was still needed before the change to `background-image`s for `noscript` images % ).

As this is a quick one, I'm gonna try to rectify it after I'm back home from today's Meeting.

Thanks for bringing this to my attention!

**Comment by timhagn** [comment]
It's probably gonna be a quick issue to solve, but I'm quite burned out for the day, gonna do it first thing tomorrow % ).

Best,

Tim.

**Comment by timhagn** [comment]
Hi @tremby,

removed `overflow: 'hidden'` in the just published `v0.8.3`.
Should probably solve this issue, so feel free to have the honors to close it, else I'm gonna do it later today : ).

Best,

Tim.

**Comment by timhagn** [comment]
As promised, I'm gonna close this now, feel free to respond conversely ; ).
