### ISSUE TITLE
Art-Direction Support (was: Different images for different media queries)

### ISSUE THREAD

**Issue by tremby** [timhagn/gatsby-background-image#58]
## Summary

Support loading different images for different browser media queries (e.g. aspect ratios or dimensions).

### Basic example

A large hero section which has vastly different aspect ratios on desktop machines (full viewport width, height somewhere between a few hundred pixels and the viewport height, i.e. landscape aspect ratio) vs mobile devices (full width, which is narrow, and full or more-than-full height, i.e. portrait aspect ratio).

### Motivation

In the above scenario using a single image will always be wasteful in at least one of the two cases.

### References

I see that something similar was asked for in #47. The solutions there were to use Javascript to detect the viewport dimensions. I don't like this since it breaks in the server-side rendering case, where the dimensions are not known. A CSS-only solution would be more appropriate, I think.

**Comment by timhagn** [comment]
Why are thee doing this to me? Open a friggin PR ; P... Gonna look at it in "the morning".

**Comment by timhagn** [comment]
Gonna try working on this today, as #61 seems to request for the same. No promises, though ; ).

**Comment by tremby** [comment]
> Why are thee doing this to me ^^? Open a friggin PR ; P... Gonna look at it in the morning

It's a feature request, not a feature demand!

**Comment by timhagn** [comment]
Hi @tremby, 

hope my initial reaction didn't get across wrong : ). Was just really "kaput" after a hard day of work and then this feature request hit me straight in the face ; ). Hope there are no hard feelings, trying to get around to solving some issues - and as this one seems in high demand, I just added `media` to the objects. Don't know how we should reconcile this array behavior with the one needed for stacked background images, yet, though...

Best, 

Tim.

**Comment by erichodges** [comment]
Thanks Tim, I will continue to research this.

**Comment by manuelsoldini** [comment]
Any updates or workarounds? I'm really looking forward for this feature

**Comment by timhagn** [comment]
Hi @manuelsoldini & @all,

I'm having an eye on this and gonna try squeezing some hours in this Friday / weekend, but no promises... Sadly there's no workaround for this, as for each `media` array their has to be a switch in how the current stacked images are processed. Any help would be appreciated : ).

Best,

Tim.

**Comment by keplersj** [comment]
I think I just wrote something related to this. I use BackgroundImage in a few different parts of my site, and wanted to change the image if the user agent is using dark mode. I was able to accomplish this using emotion and media queries. ([The commit](https://github.com/keplersj/website/commit/d2cecf05c9a251929e449179022671246af2365c))

**Comment by timhagn** [comment]
Hi @keplersj,

thnx for mentioning the commits. And yup, that's the lane I was thinking of to go down (without the extra sprinkle of emotion / styled-components ; ). The media queries will only have to be processed for all images in all formats available in `media`, though. And I gotta find a way to distinguish the "normal" stacked images from media query arrays... But there's nearly nothing that isn't possible, so no hopes forlorn : ).

Spooky Samhain % )!

**Comment by timhagn** [comment]
Hi @all,

though I squeezed in a little time today to get into this, I sadly won't be able to apply work on it this weekend (it's nearly gone by, had much to do : / ). At least I now had a look at how `gatsby-image` works with `media` attributes and we probably could use or adapt some of the functions for `gbi`. And perhaps we won't even need media-queries, as `gbi` internally works with a (not displayed) `HTMLPictureElement` which has the `media` prop. Hopefully I finally will get round working on this next weekend : ).

Best,

Tim.

**Comment by erichodges** [comment]
Interesting! Thank you for your efforts!

**Comment by ehannes** [comment]
I guess [[gatsby-image] Art direction feature does not support different aspect ratios #15189](https://github.com/gatsbyjs/gatsby/issues/15189) in `gatsby-image` is relevant for this feature...

**Comment by timhagn** [comment]
Hi @all!

_I finally found the time to sit down and integrate this feature!_
With publishing `v0.9.6`, `gbi(-es5)` now has **Art-direction support** : )!
Please be so kind and test this extensively % ).

Two things left TODO:
- [ ] combine Multiple Background Images &  Art-Direction support (right now it's one or the other)
- [ ] add Art-Direction support to `noscript` styles

But in basic mode it now works (and doesn't even seem to have the issue mentioned by @ehannes ; ).

Wasn't all to easy, but I hope you're as happy as I am this finally works ^^.

Best,

Tim.

P.S.: We're now at `v0.9.6` and not `v0.9.0` as with refactoring the large utility sources to logical entities suddenly `gatsby-node.js` & `gatsby-browser.js` weren't published any more. And if anyone of you could tell me why on [npmjs](https://www.npmjs.com/package/gatsby-background-image) `gbi` now has a extra header `<h2>` from the first example, I'd be all to thankful % )!

**Comment by danboyle8637** [comment]
@timhagn thanks for working on this but I still seem to have an issue with different aspect ratios. 

Here's my question I posted today: https://github.com/gatsbyjs/gatsby/issues/19702

I've tried many different ways to get it to work with no avail. Not sure but in my comment after my issue you can see I have this div in my DOM tree that I did not put there. It seems to be messing everything up with is padding-bottom. 

Just wanted to let you know.

**Comment by timhagn** [comment]
Hi @all!

A few changes, now supported with `v0.9.7`:
-[x]  add Art-Direction support to noscript styles

I also added examples for multiple stacked background images & art-directed images to `gbitest` & everything seemingly works even in IE11 : ).

Oh, and @danboyle8637, I have to say I don't really get where you're heading at concerning `gbi` in relation to your comments, cause neither does `gbi` use the aspect ratios, as the container should be styled for their respective sizes (they are `background-image`s, after all), nor should there be a stray `div` in `gbi`, as none is added oO... Care to explain or test with `gbitest`?

That's all for now, folks,

best,

Tim.

**Comment by timhagn** [comment]
We're now at `v0.9.8`, fixing #88 : ).
