### ISSUE TITLE
Border-radius CSS-property not working on Background Image (Version 0.8.3)

### ISSUE THREAD

**Issue by Alexcraftish** [timhagn/gatsby-background-image#59]
## Description

After upgrading my version of the plugin from 0.8.2 to 0.8.3 I noticed that my border-radius property wasn't working on my background images. 

### Steps to reproduce

Try to set a border-radius on a background image (e.g. 15px). It's like I didn't apply it, it still has edgy corners. As soon as I downgraded to 0.8.2 the issue seems to be gone.

### Environment
My package.json
{
  "name": "gatsby-starter-hello-world",
  "private": true,
  "description": "A simplified bare-bones starter for Gatsby",
  "version": "0.1.0",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "env-cmd -f .env.development gatsby develop",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\""
  },
  "dependencies": {
    "axios": "^0.19.0",
    "gatsby": "^2.13.51",
    "gatsby-background-image": "^0.8.3",
    "gatsby-image": "^2.2.8",
    "gatsby-plugin-google-fonts": "^1.0.1",
    "gatsby-plugin-react-helmet": "^3.1.3",
    "gatsby-plugin-remote-images": "^1.0.3",
    "gatsby-plugin-sass": "^2.1.4",
    "gatsby-plugin-sharp": "^2.2.9",
    "gatsby-source-graphql": "^2.1.3",
    "gatsby-source-wordpress": "^3.1.13",
    "gatsby-transformer-sharp": "^2.2.5",
    "intersection-observer": "^0.7.0",
    "node-sass": "^4.12.0",
    "path": "^0.12.7",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "react-spring": "^8.0.27",
    "resize-observer-polyfill": "^1.5.1"
  },
  "devDependencies": {
    "env-cmd": "^9.0.3",
    "prettier": "^1.18.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-hello-world"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}

///

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.1.0
  npmPackages:
    gatsby: ^2.13.51 => 2.13.51 
    gatsby-background-image: ^0.8.2 => 0.8.2 
    gatsby-image: ^2.2.8 => 2.2.8 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3 
    gatsby-plugin-remote-images: ^1.0.3 => 1.0.3 
    gatsby-plugin-sass: ^2.1.4 => 2.1.4 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9 
    gatsby-source-graphql: ^2.1.3 => 2.1.3 
    gatsby-source-wordpress: ^3.1.13 => 3.1.13 
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5 

///

**Comment by timhagn** [comment]
Hi @Alexcraftish,

as a default of `overflow: 'hidden'` definitely did more harm than good (and was a remnant of `gbi`'s meager beginnings), I removed it for #57 (that's the only thing that changed between `v0.8.2` & `v0.8.3`). Perhaps this quickly "ducked" [StackOverflow question & first answer](https://stackoverflow.com/questions/6721725/overflow-hidden-breaks-border-radius) might shed some light on your "issue". 
You'd have to give me some of your CSS-Styling so I'd be able to perhaps really be able to help you out here...

Best,

Tim.

**Comment by timhagn** [comment]
Hi @Alexcraftish,

any news on this one?

Best,

Tim.

**Comment by Alexcraftish** [comment]
Yes, thanks for checking in! I just had to set the overflow to hidden and
it worked!
Thanks for providing such a great plugin, keep it up!

Greetings,
Max

**Comment by timhagn** [comment]
Hi @Alexcraftish / Max,

great news - am gonna include a notice of the change (perhaps should have escalated to 0.9.0 instead of only a minor version % ) and it's solution with the next update!

And of course, the honors is all yours to close this : ).

Greetings,

Tim.

**Comment by timhagn** [comment]
Closing this now, as it's solved : ).

Greetings,

Tim.

**Comment by arhoy** [comment]
Border Radius NOT working !
Is there a reason why to use this library over gatsby image?

**Comment by timhagn** [comment]
Hi @arhoy,

no need to scream ; ). Have you already tried the workaround with `overflow: "hidden"`, as mentioned [above](https://github.com/timhagn/gatsby-background-image/issues/59#issuecomment-518362624)?

And on your question about why to use this component "over" `gatsby-image`: rather ask, when to use it. As `gbi` comes to shine when one wants easily implemented or multiple stacked **background images**, whereas `gatsby-image` is the way to go when one wants to display pure images, as both their names state ; ).

Best,

Tim.

**Comment by arhoy** [comment]
@timhagn thanks for your reply, I am not screaming just putting emphasis that it is not working.
I am not sure what you mean by multi stack background image, Seems pretty simple to do in css?
https://www.w3schools.com/css/css3_backgrounds.asp

I have tried both libraries, and I pretty much always fall back to Gatsby Image for my requirements, including background images, so that is why I ask.

**Comment by timhagn** [comment]
Hi @arhoy,

don't want to tread on your feet, but might I suspect that you haven't tried the mentioned workaround (or read to `gbi`'s README ; )?
As at my place it's working just fine with the aforementioned `overflow: 'hidden'`:
![image](https://user-images.githubusercontent.com/12220779/77857909-a8749300-7200-11ea-90d8-96301816d305.png)
```jsx
<StyledStackedBackgrounds
      Tag="div"
      fluid={firefoxExampleFluidImageStack}
      id="imagestack"
      role="img"
      aria-label="A GBI background stack with the firefox example"
      style={{
        backgroundColor: 'white',
        backgroundRepeat: 'no-repeat, no-repeat, no-repeat',
        backgroundPosition: 'bottom right, left, right',
        backgroundSize: '',
        borderRadius: '50%',
        overflow: 'hidden',
      }}
    />
```
(the styled-components part here is just: `width: 600px; height: 400px;`).

Perhaps you might want to give `gbi` another spin with the just released `v1.0.0` - just head over to the also updated [`gbitest`](https://github.com/timhagn/gbitest).

(And why `gbi` might be better than a "simple CSS" solution is also mentioned in its README...)

Alas, the decision of using it or not is entirely up to you.

Best,

Tim.

**Comment by carrigan223** [comment]
hey tim,

the hidden: overflow worked when i put it in` style={{}}` is there a way to do it in my styled component of BackgroundImage using emotion, it wasn't working until i inserted directly into the style property, more for curiousity sake i was wondering if you knew of a way to keep with the rest of my styles in the styled component.

`const ImageBackground = styled(BackgroundImage)`
  background-position: bottom 34% center;
  background-size: cover;
  height: 60vh;
  max-width: 100vw;
  + * {
    margin-top: 0;
  }
`;
`

`                <ImageBackground
                  style={{
                    borderRadius: "50%",
                    overflow: "hidden",
                  }}
                  Tag="section"
                  fluid={flag.sharp.fluid}
                  fadeIn="soft"
                >
`

**Comment by timhagn** [comment]
Hey @carrigan223,

don't know if you got it yourself in the meantime, but like with most styling issues you have to target:

```css
...
  &:before,
  &:after {
    border-radius: 50%;
    overflow: hidden;
  }
...
```

in your styled-component / classes : ). Should probably state this clearer in the README...

Best,

Tim.
