### ISSUE TITLE
Background Attachment Fixed

### ISSUE THREAD

**Issue by ArcadeRenegade** [timhagn/gatsby-background-image#62]
Hello again, I have set the css background-attachment property to the ::before and ::after elements to fixed so that I get a cool parallax effect.

This works great on desktop, however, the background-attachment: fixed style seems to be ignored on Chrome Mobile as the background image scrolls with the body. This one isn't a big deal.

However, on iOS Safari, the background-attachment: fixed background I extremely zoomed in. To the point that it isn't usable.

Any ideas why this would happen?

You can see what I'm talking about on my website in development. I set background-attachment: fixed on a couple of <BackgroundImage>'s including the banner.

https://dev.roselium.com/

**Comment by ArcadeRenegade** [comment]
Never mind. Mobile devices don't support background-attachment fixed so I just unset it for iOS using a CSS hack:

```
    @supports (-webkit-overflow-scrolling: touch) {
        background-attachment: initial !important;

        &::before,
        &::after {
            background-attachment: initial !important;
        }
    }
```

**Comment by timhagn** [comment]
Hi Ryan / @ArcadeRenegade,

thanks for the CSS hack, didn't know about that one : )! 
Great you found it (and it wasn't an issue with `gbi` ; ).

Best,

Tim.
