### ISSUE TITLE
Transparent PNG Shadows

### ISSUE THREAD

**Issue by Sicria** [timhagn/gatsby-background-image#63]
## Description
When using this package with a transparent png it seems that it adds a ``:before`` and ``:after`` which both have the same background image. This is fine for images which don't have gradients or shadows but when they do it doubles them up and makes them much darker.

Is it possible to hide the unused images once the blur-up has completed?

**Comment by timhagn** [comment]
Hi @Sicria,

might you wanna elaborate a bit more? Or at least provide an example and `gatsby info` as asked for. 
As at the end, one of the pseudo elements gets hidden by the other. But you could target the hidden one in an `onLoad()` callback. If you would provide an example, I could have a look into this.

Best,

Tim.

**Comment by Sicria** [comment]
Can't seem to replicate this consistently, it does not happen every time, only on some page loads. Not a big deal so I'll close the issue. Appreciate the great package, thank you.

**Comment by timhagn** [comment]
Hi @Sicria,

though I'm glad it's "no big deal", I'm definitely intrigued! Hope my last comment didn't come over as harsh, that's far from what I wanted : ). Should you run into any more trouble with this, feel free to reopen this issue (or a new one).

Best,

Tim.
