### ISSUE TITLE
TypeScript index.d.ts error when esModuleInterop is false

### ISSUE THREAD

**Issue by awwit** [timhagn/gatsby-background-image#66]
## Description

In your `index.d.ts` there a is mistake:

https://github.com/timhagn/gatsby-background-image/blob/f0a85f8e01/packages/gatsby-background-image/index.d.ts#L1

### Steps to reproduce

If you use a `typescript` with the `esModuleInterop` option, then an error occurs during compilation:

```
Module '"/media/projects/work/bitgoals/PoolTickets/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

import React from 'react'
```

### Expected result

Must be:

```ts
import * as React from 'react'
```

### Actual result

```ts
import React from 'react'
```

Please, fix it =)

**Comment by timhagn** [comment]
Hi @awwit!

Thus Issues I very much like, having the solution included : )!
Am normally not using TS, so this didn't raise a flag (though the newest IntelliJ did now "complain", though only _after_ I opened `index.d.ts` % ), but I just rectified it and published `v0.8.6`.

Best,

Tim.

**Comment by awwit** [comment]
@timhagn Great!
My project is now going as it should (without including special flags).
Thanks! =)

**Comment by timhagn** [comment]
@awwit Great news : ). Definitely gonna have to look little bit more into TypeScript, especially since I'm stemming from strongly typed languages like Pascal and C++... Just the `<` within JS seems so wrong without a Math context ^^.

Best,

Tim.
