### ISSUE TITLE
Low Quality (pixelated) image background on IE11

### ISSUE THREAD

**Issue by Jsalvat** [timhagn/gatsby-background-image#69]
Hello, 

We're using gatsby-image-background for our website, it works correctly on all tested browsers but in IE11 for some reason it's not working properly.

We tried gatsby-image-background-es5 last version but it's not working either. I mean, it's working, but the resolution of the image it's not correct. 

IDK if I'm doing something wrong, I checked if someone more have this problem and I didnt see anything about it.

We're using gatsby-image-sharp and our grapqhl it's something like this:

localImage {
          childImageSharp {
            fluid(quality: 100 ) {
              ...GatsbyImageSharpFluid
            }
          }
        } 

System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.0
  npmPackages:
    gatsby: ^2.1.18 => 2.4.2
    gatsby-background-image: 0.6.2 => 0.6.2
    gatsby-background-image-es5: ^0.8.9 => 0.8.9
    gatsby-image: ^2.0.33 => 2.0.41
    gatsby-plugin-canonical-urls: ^2.0.12 => 2.0.12
    gatsby-plugin-google-tagmanager: ^2.0.13 => 2.0.13
    gatsby-plugin-manifest: ^2.0.24 => 2.1.1
    gatsby-plugin-material-ui: ^1.2.4 => 1.2.5
    gatsby-plugin-no-sourcemaps: ^2.0.2 => 2.0.2
    gatsby-plugin-offline: ^2.0.24 => 2.1.0
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.12
    gatsby-plugin-react-helmet-canonical-urls: ^1.2.0 => 1.2.0
    gatsby-plugin-remote-images: git+https://github.com/graysonhicks/gatsby-plugin-remote-images.git#53b590a0d21e7fdfa5946e76bf081f3d9102b1c7 => 1.0.2
    gatsby-plugin-remove-trailing-slashes: ^2.0.10 => 2.0.11
    gatsby-plugin-sass: ^2.0.10 => 2.0.11
    gatsby-plugin-sharp: ^2.0.22 => 2.0.36
    gatsby-plugin-sitemap: ^2.2.4 => 2.2.4
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.0.23 => 2.0.33
    gatsby-transformer-sharp: ^2.1.14 => 2.1.19
  npmGlobalPackages:
    gatsby-cli: 2.7.20

**Comment by Jsalvat** [comment]
nvm I found my error. I wasn't using maxHeight and maxWidth  and was taking 800x800 as a default resolution.

**Comment by timhagn** [comment]
Hi @Jsalvat,

sry I didn't get around earlier to reply - but great to hear you could solve it yourself : )!
Such Issues I like the most, those that solve themselves ^^.

Would have pointed you in the direction of `gatsby-plugin-sharp` anyhow, as `gbi(-es5)` does nothing to your pictures generated through it, except (trying % ) to display them ; ).

But again, great you could solve this on your own!

Best,

Tim.
