### ISSUE TITLE
How to dynamically style background?

### ISSUE THREAD

**Issue by auto200** [timhagn/gatsby-background-image#74]
Here's my styled component 
```
const StyledBackground = styled(BackgroundImage)`
   &::before,
   &::after {
    filter: brightness(${({ isDarken }) => (isDarken ? "50%" : "80%")});
  }
`;
```
When passing `isDarken` prop like this:
```
<StyledBackground
        fluid={bgSrc}
        fadeIn={false}
        isDarken={true}
      >
      {//content}
</StyledBackground>
```
An error occures:

> Warning: React does not recognize the `isDarken` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdarken` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     in div (created by BackgroundImage)
>     in BackgroundImage (created by Context.Consumer)
> ...

So i tried the other way around:
```
const StyledBackground = styled(BackgroundImage)`
   &.normal {
    ::after,
    ::before {
      filter: brightness(80%);
    }
  }
  &.darken {
    ::after,
    ::before {
      filter: brightness(50%);
    }
  }
`;
```
and passing the className:
```
<StyledBackground
        fluid={bgSrc}
        fadeIn={false}
        className={isDarken ? "darken" : "normal"}
      >
      {//content}
</StyledBackground>
```
this time class never gets updated, always stays as the initial one. Regardless of chaning the state of `isDarken`

**Comment by timhagn** [comment]
Hi @auto200,

gonna have a look at your first approach, as soon as I'm able too (am at a Gig, only a short break ; ).
But AFAIK, the only props `styled-components` listens to are coming from outside.

The second approach won't work like this, cause the `StyledBackground` get's created by `styled-components` beforehand. A workaround here for the moment would be to create a `StyledWrapper` (ya, I know % ) with two aditional classes and changing the pseudo elements' styling there - afterwards you can switch which `className` to add.

Best,

Tim.

**Comment by auto200** [comment]
Thanks @timhagn for the quick reply event though you'r on a break. Have a good time :)

**Comment by timhagn** [comment]
Btw. I'm not \_on a break\_, I had a quick break in the office, at a Freelance Gig I'm at atm. ^^

**Comment by timhagn** [comment]
Hi @auto200,

just checked if the Prop Filtering of `styled-components` would work as in the article, but sadly it only seems to do so with native `HTMLElement`s (or I'd gonna have to add `styled-components` as a dependency, which I wanna refrain from : /). Gonna investigate further.

Best,

Tim.

**Comment by timhagn** [comment]
Hi  @auto200,

Just published `v0.8.14` with an added [`filter-invalid-dom-props`](https://www.npmjs.com/package/filter-invalid-dom-props) dependency to filter the `remainingProps` before spreading them into the component. At least at my place it `gbi` now works with `styled-components` props. 
Would you be so kind to test it in your project? And should it rectify your issue, you may of course have the honor of closing it : ).

Best,

Tim.

**Comment by timhagn** [comment]
Hi @auto200, still interested...?

**Comment by auto200** [comment]
Sorry for being active for a long time but i've been very busy lately, sadly programming is not the thing i do for a living... So back to the thread, done some testing:
```
const StyledBackground = styled(BackgroundImage)`
  width: 100%;
  height: 100%;
  &::before,
  &::after {
    filter: brightness(
      ${props => {
        console.log(props);
        return props.isDarken ? "70%" : "80%";
      }}
    );
  }
`;
```
i really get the isDarken prop and its current state. What does not happens is the actual change in the browser (initial state forever).
Intresting thing that i noticed is that if i manually change some property like width, change doesn't auto apply i need to hit f5 to see results. IDK if i misunderstood something, please correct me.

**Comment by timhagn** [comment]
Hi @auto200,

now it was my turn to keep you waiting ; ). But I had a look at the behavior and, alas, it seems that `styled-components` only adds the changes to one of their `classnames`, so they sadly don't reach `gbi` atm. I only tested if the props now reached the styled component % ).
Gonna try experimenting with it this weekend - but no promises.

Best,

Tim.

**Comment by auto200** [comment]
Hey @timhagn 
no worries, I made my peace with it not working as i wanted but I still think that would be a cool feature :) Have a nice weekend :)

**Comment by timhagn** [comment]
Hey @auto200,

just looked at it a little more and searched the web - and how could I miss this:
As only the `props` change, but not the components `state`, React won't rerender `<BackgroundImage />` (or any other component). But we can work around this behavior
by adding a `key` to it, which changes with the prop like thus for example:

```js
.
.
.
isDarken={isDarken}
key={isDarken ? `dark` : `light`}
.
.
.
```

When the key changes, React will render the component again and the style change from `StyledBackground` is applied : ). Added a workaround explanation to the [README ](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#passed-props-for-styled-components-and-suchlike).
Hope this solves this issue % ).

Best,

Tim.

**Comment by auto200** [comment]
Thank You for your time and commitment. Tested and works like a charm :)

Best

**Comment by timhagn** [comment]
That's great news : )!

Best,

Tim.
