### ISSUE TITLE
Google Fonts not loading properly when using global css

### ISSUE THREAD

**Issue by ikey2244** [timhagn/gatsby-background-image#75]
## Description
Google Fonts are not loading properly when you add a className to child element of BackgroundImage component and referencing that class in my global.css. The font does not look like the Google Font that I want. For example I have this code . I have tested this by using google fonts outside of the BackgroundImage component and everything is working as intended.

`<BackgroundImage
          Tag="section"
          className='cover'
          fluid={imageData}
        >
        <h1 className="date" >May 23rd 2020</h1>
      </BackgroundImage>`

### Steps to reproduce
* use BackgroundImage component
* add a child element
* give child element a class
* reference class in global.css
* add a font family from google fonts

### Expected result
Google fonts should be loaded properly and look as intended.

### Actual result
Font looks completely different then Google Font

### Environment
 System:
    OS: macOS High Sierra 10.13.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.9.4 - /usr/local/bin/node
    npm: 6.8.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 61.0.1
    Safari: 11.0.2
  npmPackages:
    gatsby: ^2.13.57 => 2.13.57 
    gatsby-background-image: ^0.8.9 => 0.8.9 
    gatsby-image: ^2.2.8 => 2.2.8 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5 
    gatsby-plugin-offline: ^2.2.5 => 2.2.5 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3 
    gatsby-plugin-sharp: ^2.2.11 => 2.2.11 
    gatsby-source-filesystem: ^2.1.9 => 2.1.9 
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
    gatsby: 1.2.0

**Comment by timhagn** [comment]
Hi again @ikey2244,

btw., have you already seen @KyleAMathews's [typefaces](https://github.com/KyleAMathews/typefaces) package? Used them in some projects - and that's why I mightn't have seen the behavior you described (have to be quite GDPR conscious here in Austria and Google Fonts are a grey area ; ).

But gonna look into it anyhow : ).

Best,

Tim.

**Comment by ikey2244** [comment]
Hey @timhagn sorry about the late response! I started to use gatsby-plugin-web-font-loader plugin and that seemed to fix my problems

**Comment by timhagn** [comment]
No Prob, @ikey2244, glad that solved it
(seemingly ; ). AFAIK the web-font plugin loads the fonts down in advance, too, so I'd rather guess your issue started someway during the build steps...
(And I didn't come round looking into it during the weekend % ).
