### ISSUE TITLE
Weird outline artifact when backgroundColor property not set

### ISSUE THREAD

**Issue by Faustvii** [timhagn/gatsby-background-image#76]
## Description
When not setting the `backgroundColor` property on `BackgroundImage` a weird "outline" comes around the picture shown here https://i.imgur.com/CRNjEIv.png where one would expect it to look like this https://i.imgur.com/u2mCcY1.png which it does when the `backgroundColor` is set.

If you navigate around to a different page of the application then the image will look correct, for instance going to page-2 of the gbitest application. It looks correct on both page-2 and the homepage after navigation, but a refresh will make it have the "outline" again until another navigation happens.

### Steps to reproduce
I've made a fork of gbitest https://github.com/Faustvii/gbitest where I've changed the image to the happy-snowman(To make it easier to see the effect happening) then changed the graphql query a little bit and then commented out the `backgroundColor` in `index.js` line 45.
Commenting the `backgroundColor` on line 45 in `index.js` in or out will show you the desired "outline" issue after a refresh of the page, it does not happen on a hot reload.
I see the issue in Edge, Chrome and Firefox.

### Expected result
I would've expected the background image to look like this https://i.imgur.com/u2mCcY1.png

### Actual result
But the background image actually looks like this https://i.imgur.com/CRNjEIv.png

### Environment
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  Binaries:
    Node: 12.10.0 - C:\Users\Mike\scoop\apps\nodejs\current\node.EXE
    npm: 6.10.3 - C:\Users\Mike\scoop\apps\nodejs\current\npm.CMD
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    gatsby: 2.15.1 => 2.15.1 
    gatsby-background-image: ^0.8.7 => 0.8.7 
    gatsby-image: ^2.2.15 => 2.2.15 
    gatsby-plugin-manifest: 2.2.12 => 2.2.12 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: 3.1.5 => 3.1.5 
    gatsby-plugin-sharp: 2.2.18 => 2.2.18 
    gatsby-plugin-styled-components: ^3.1.3 => 3.1.3 
    gatsby-source-filesystem: ^2.1.18 => 2.1.18 
    gatsby-transformer-sharp: ^2.2.12 => 2.2.12 
```

**Comment by timhagn** [comment]
Hi again @Faustvii,

I now added a `finalImage` switch to add an `opacity: 0;` to the `after` pseudo-element when the main image(s) have loaded and - testing it with your `gbitest` (many thanks again for providing a repo!) - the behavior you mentioned is now rectified with the just published `v0.8.11` : )! 

Would you be so kind and test it yourself? Should it be solved for you, too, you of course may have the honor of closing this issue : ).

Best,

Tim.
