### ISSUE TITLE
Blur image with text overlay

### ISSUE THREAD

**Issue by picolloo** [timhagn/gatsby-background-image#78]
## Summary

I'd like to use gatsby-background-image as a blurred background with text over it.

## Relevant information
I was having trouble to show text over the image so I find out a way that works for me: 

![image](https://user-images.githubusercontent.com/29408363/65103286-29c2b180-d9a4-11e9-97db-04bc15a7dcbe.png)

But now I have inserted blur css effects and the text that is over it gets blurred too, even with the z-index bigger than the image.

width: 100%;
height: 100%;
background-position: bottom center;
background-repeat: no-repeat;
background-site: cover;
filter: blur(2px);

**Comment by timhagn** [comment]
Hi @picolloo,

though this isn't really an issue with `gbi`, as `filter: blur(2px);` gets of course set on all child elements, there are a few hacks to get around it, have a look at this [CSS-Tricks article](https://css-tricks.com/apply-a-filter-to-a-background-image/).

In case of `gbi` you'd be easily able to apply any of the mentioned three (there are a few newer variations like the `backdrop-filter` CSS property - but sadly there's no widespread [support](https://caniuse.com/#feat=css-backdrop-filter) for it...).

You seem to simply want a blurred background, so I'd go with the first approach from CSS-Tricks.
As `gbi` is already using `:before & :after` pseudo-elements, just add:

```css
&:before, &:after {
  filter: blur(2px);
}
```

to your `<BackgroundImageStyled>` `styled-component` CSS (I only guessed that this is what you're using from the context ; ) - and of course remove the filter from the `BackgroundImage`.

Hope this works on first try, else I'd have to take a look at it for myself later (then it would be great, should you be able to provide a quick example-repo) - am just waking up to prepare for a Gig and wrote this from the top of my head % ).

Fingers crossed, best,

Tim.

**Comment by picolloo** [comment]
It works pretty well, thank you so much and sorry for the issue that was not related to the `gbi` itself, I haven't found out that solution and didn't know where else to search.

Thank you again and have a nice day.

**Comment by timhagn** [comment]
No problem, @picollo,

no need to feel sorry, glad I could help. Me rather likes issues, where I only need (and am able) to provide some kind of directions ; ).

Have a nice evening,

best,

Tim.
