### ISSUE TITLE
trouble showing image due to -100 z-index on :after

### ISSUE THREAD

**Issue by EricSSartorius** [timhagn/gatsby-background-image#8]
Hey,
Love this plugin, I have been looking for a solution for bg images for a while.

One thing I noticed when trying to use it is that when wrapping a block of content no images showed up at first. After inspection and some tweaking I got the images to show up by changing the z-index on `.gatsby-background-image:after` from -100 to 0. Then I had to change all content within to z-index 1 to get things to show.

What I did feels a bit hacky but it works now. Just wondering if the way I am using it is wrong and that is why I have to make the changes?

Here is what I have working:
```
export const CoverImage = ({
  children,
  fluid,
  alt,
  backgroundColor,
}) => (
  <BGImage Tag="div" alt={alt} fluid={fluid} backgroundColor={backgroundColor}>
    <Content>
      {children}
    </Content>
  </BGImage>
);

const BGImage = styled(BackgroundImage)`
  &:after {
    z-index: 0 !important;
  }
`;

const Content = styled('div')`
  * {
    z-index: 1;
  }
`;

export default CoverImage;
```

**Comment by timhagn** [comment]
Hi @EricSSartorius!

Thanks for the compliment and joining in. Happy to help, usually no further changes should be necessary, but would you perhaps give me some more info to go from?
A quick `gatsby info` would suffice for the moment.

And have you already tested it with the [example implementation](https://github.com/timhagn/gbitest) (I've updated it on Tuesday) if the same problem occurs there?

**Comment by EricSSartorius** [comment]
@timhagn 
Sure, Here is my Gatsby Info:
```
  System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.9 => 2.1.9 
    gatsby-background-image: ^0.2.4 => 0.2.4 
    gatsby-image: ^2.0.10 => 2.0.13 
    gatsby-plugin-google-analytics: ^2.0.14 => 2.0.14 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-manifest: ^2.0.18 => 2.0.18 
    gatsby-plugin-offline: ^2.0.22 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-robots-txt: ^1.4.0 => 1.4.0 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-source-filesystem: ^2.0.20 => 2.0.20 
    gatsby-source-shopify2: ^2.0.7 => 2.0.7 
    gatsby-source-wordpress: ^3.0.35 => 3.0.36 
    gatsby-transformer-sharp: ^2.1.2 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.11
```

I just downloaded and ran your test repo and don't seem to have any problems. I will try using your BackgroundSection component in my app and see if I get similar results or not. I originally tried with the example in the plugin docs on gatsby.org but it looks like your current example is a bit more in-depth.

**Comment by timhagn** [comment]
Thanks for trying it : )! I'm definitely eager to hear the results - though you already seem to be using the latest version of `gatsby-background-image`... Are you testing it in Safari or Chrome? (Have to confess,
haven't tested it with Safari on macOS % )

**Comment by EricSSartorius** [comment]
Only Chrome so far.
I have to check of course but in my current implementation, I'm currently trying to get a cover-positioned background for a div inside a grid. So the component I've copied above is wrapping a div within a div that has a display of `grid`. It isn't actually being used in layout for the page background. I wonder if that has a connection to the problem I am having.

**Comment by EricSSartorius** [comment]
@timhagn 
Yeah after experimenting trying wrapping different elements, and using a grid and no grid I still fall at the same place, bg image won't show unless it is at z-index: 0 and all the content within is z-index 1 or above. I am passing data from a page-level query not a StaticQuery like your example but I don't think that should affect anything. =/

**Comment by timhagn** [comment]
Might you have some example code as repository or be able to throw some in a gist
(with queries and all)? 
You definitely made me curious - haven't tried it in a grid before % ).

The page-level query vs. StaticQuery shouldn't matter in my experience, though
(as long as they get created by Gatsby ; ).

Gonna look into it, as soon as I can - or feel free to open a PR : )!

**Comment by EricSSartorius** [comment]
So I messed around for the past hour and it just made me more confused.
Using the same components and queries from my personal repo, I put them into your test repo and produced different results.
`BackgroundImage` will show in your repo with any negative z-index on `:after` but will only show in my repo with a positive z-index. I tried stripping everything to the bare minimum on my repo including global values but still wasn't able to see a bg image without a positive z-index (using !important to override).

I threw up a fork of your repo with the code I was testing here: https://github.com/EricSSartorius/gbi-test
as I mentioned though, a negative z-index works here but doesn't in my other repo for some reason (can't share that repo due to NDA unfortunately)

**Comment by timhagn** [comment]
Thanks again for bringing this up! 
Cause while playing around with mine own repo of `gbitest`, it struck me, 
that  - as soon as I commented out the default comparison `gatsby-image` -
the children of `StyledBackgroundImage` seemed to jump around oO.

Here a screenshot from Chromium's "Performance" Tab:
![image](https://user-images.githubusercontent.com/12220779/53590015-1fb89d00-3b91-11e9-9b37-baf7ea273551.png)

Tried your initial "hack" (now obviously not so hacky - kudos by the way for finding it : )
and the jumping around / flickering was gone.
Gonna definitely investigate further and upped the level of this issue with the label Bug...

After cloning your fork and starting develop mode I definitely could confirm your findings,
especially the one about flex / grid being necessary.
But I got an error about:
```
Warning: Failed prop type: Invalid prop `fluid` of type `object` supplied to `CoverImage`, expected `string`.
```
Seemingly the graphql query isn't run initially, but the `BGImage`s show up, nonetheless oO...

But as written before, gonna dig into it, and your help is more than welcome : )!

**Comment by EricSSartorius** [comment]
Didn't mean to open up a can of worms but hopefully this will get figured out. Let me know if you make some progress and if I have some free time again I will try to dig a bit more myself.

**Comment by timhagn** [comment]
Thnx for opening the can, hope it isn't just a tip of an iceberg ; ).
From my findings up until now, it seems I'm gonna have to throw myself into stacking orders with 
flex / grid & pseudo-elements. 
Should you (or any other kind person : ) have any deeper knowledge thereof, I'd be a willing student, cause for the moment the problem eludes me...

Methinks I'm going back at it tomorrow with a pair of fresh eyes...

**Comment by EricSSartorius** [comment]
Shoot me a message if you have any questions on flexbox or grid and I'll see if I can help.

**Comment by timhagn** [comment]
Hi @EricSSartorius, might you confirm? I tried a few values and if I set `&:before, &:after { z-index: auto !important; }` in `StyledBackgroundComponent` and create a styled component to wrap the `{children}`
```
const Content = styled.div`
  * {
    z-index: 1 !important;
  }
```
`BackgroundImage` still works - even without using a flex / grid wrapper. 
Remove the z-index and of course everything breaks, but how it works I wonder...

**Comment by EricSSartorius** [comment]
@timhagn So I was able to get `z-index: auto !important` to work same as `0` but it would only work in flex/grid.

However, I just had a bit of a breakthrough that gives more insight into the problem.

In my layout component, I have the following (this is simplified of course)
```
const Layout = ({ children }) => {
 <>
  <Header />
 <Main>{children}</Main>
</>
}

const Main = styled('main')`
  background: #fff;
`;
```

putting a background color is what has messed everything up and forced me to use a `z-index: 0 auto!`. If I take the background color out everything shows up as it should.
So your current implementation or  `&:after { z-index: auto !important; }` should both work if there is no background color being used in the surrounding div. if a background color is used then display flex/grid is necessary.

I'm not sure the next steps to take with that information but I hope it helps.

**Comment by timhagn** [comment]
Mkay, I'm officially stumped. Just was testing your findings and can confirm, `background-color` or the inbuilt `backgroundColor` _do_ matter. However, why, I ain't able to fathom. I reset everything in the example repo back to normal except commenting out the `gatsby-image`.
Commenting out `backgroundColor` did the trick, no jumping happening, `{children}` visible...
I'm gonna investigate further...

**Comment by EricSSartorius** [comment]
Let me know if you come across anything after further investigation. I will let you know as well if I come across something when I work on my repo again later this week.

**Comment by timhagn** [comment]
Hope to have solved it before then ^^. Definitely thanks again for bringing this up - wouldn't have guessed that we'd uncover a rendering issue in the Chromium engine (FF had no problems either way, at least here on Linux). Let's see where it takes us ; ).

**Comment by EricSSartorius** [comment]
Yeah for sure. Btw, just read this article on stacking order https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

using my example above with the <Main> styled component, if you change it's opacity to 0.99 then everything works fine.

**Comment by timhagn** [comment]
After reading through your link and finally (again) landing at the specs, I can confirm your findings about the "opacity hack". Added it to `v0.2.43`, and at least here in FF and Chrome everything works with or without flex / grid and z-index changes : ). May I close this issue @EricSSartorius?

**Comment by EricSSartorius** [comment]
Great! Yeah I will go ahead and close. Thank you for the help on this!

**Comment by timhagn** [comment]
Nice, another one done : ). Thanks for your contributions, @EricSSartorius, 
would definitely have taken me longer without your help!

**Comment by EricSSartorius** [comment]
@timhagn Glad I could help!

One follow-up on this I just noticed, however:

not sure how big of a deal this is but since updating GBI, now on `gatsby build` when creating static pages I see`Error getting opacity from style prop:  Cannot read property 'opacity' of undefined`
for every page that has GBI on it. The same warning is in my verbose console output pointing at StyleUtils.js as well
(visually no problems though)
