### ISSUE TITLE
Choosing Focus?

### ISSUE THREAD

**Issue by erichodges** [timhagn/gatsby-background-image#81]
Is it possible to choose the focus point of the image when the screen size is smaller?

**Comment by timhagn** [comment]
Are you talking about media queries changing the `background-position`? You'd have to target the pseudo-elements directly, though.
Or am I getting you wrong?

**Comment by erichodges** [comment]
No, for any size screen. I think I tried to set the background-position in the incorrect place. Here's the file, if you have time:
https://github.com/erichodges/bg_image_gatsby/blob/0e1f8c76ed8be7752bec8ec9ee99b2941408b314/src/components/index.js#L33

**Comment by timhagn** [comment]
*\*hmmz\** Usually `createPseudoStyles()` spreads them in correctly, see [`StyleUtils.js#L249`](https://github.com/timhagn/gatsby-background-image/blob/96ef6a9ed03cb0f3a41218d43389097a11ef7a85/packages/gatsby-background-image/src/StyleUtils.js#L249), when you use `backgroundPosition` as a style prop. `objectFit` & Co. won't work, as they are only for [replaced elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element#Using_CSS_with_replaced_elements). 
For the moment, you might wanna try [Styling & Passed Through Styles](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#styling--passed-through-styles) from the Docs. 
But I'm gonna investigate, if neither `backgroundPosition` in the `style` prop nor passing the props through `styled-components` work on your side. Btw. what CSS properties do the final background images have and what browser (and system) are you using (for the latter, a quick `gatsby info` would suffice)?

**Comment by erichodges** [comment]
I'm running OSX 10.14.6, chrome, "gatsby": "^2.0.76", is that the gatsby info you wanted?

```
element.style {
    position: absolute;
    overflow: hidden;
    background-position: 0% 50%;
    background-repeat: no-repeat;
    object-fit: cover;
    min-height: 100vh;
    width: 100vw;
}
```

**Comment by timhagn** [comment]
Hi @erichodges,

I talked about running `gatsby info` in your project, which gives you a nice overview about all installed `gatsby-` packages ; ). But you did just as well.
Btw. it would be `background-size: cover;`, not `object-fit` for background images, but I guess I'm not telling you anything new ^^.

Still couldn't replicate your issue, though : /. Would you perhaps have an example repo clarifying & demonstrating your issue?

Best,

Tim.

**Comment by erichodges** [comment]
Thanks for your reply @timhagn! 

Here's the repo:
[https://github.com/erichodges/bg_image_gatsby]

This repo is not much different from your example repo. I just cloned your repo and changed it a bit.  The image in question is controlled in `components/index`.

Thanks for letting me know about gatsby info.

**Comment by timhagn** [comment]
Hi @erichodges  / Erich,

didn't find the time to have a look at your repo till now, but gonna try doing it on the weekend - no promises, though ; ). Or have you found the cause of your issue yourself in the meantime? 

Best,

Tim.

**Comment by erichodges** [comment]
Tim, no worries! If you get a chance to look at it that would be great. I want to get a handle on how to best do this in gatsby so that I can build cool things. :-)

Cheers,

Eric

**Comment by itwasmattgregg** [comment]
If I'm understanding you correctly I think you can simply use media queries to change `background-position` based on screen size.

**Comment by erichodges** [comment]
@itwasmattgregg Thank you. I've been having an issue getting the css to work, which needs to be fixed first.

**Comment by timhagn** [comment]
Hi @erichodges,

as some time has gone by (am pretty booked at the moment), have you solved this meanwhile? As looking at your repo it seems to be correct now, or do I err? Or were my I still be of help?

Best,

Tim.

**Comment by erichodges** [comment]
Hi @timhagn,

I have not solved this issue, but I'm interested in any ideas that you may come up with if you happen to have any time. :-)

Best,

Eric

**Comment by timhagn** [comment]
Hi @erichodges,

finally found the time to take a look at your repo. First of all, why the heck were you using `gbi` @ `v0.2.1` (pardon my french, but _why_ % )? With the current `v0.8.18` or even way back with `v0.2.8-beta` `gbi` started to spread the `background-*` styles, `v0.2.1` didn't even try to do it ^^.
Secondly, you are using an image which exactly fits the screen, so there's no way CSS could possibly focus anywhere else... I stretched your image to double its size and focusing started working - though I don't know where exactly you want the focus to be ; ). Should you want it to be directly over the sundown you'd need a little more space to the left.

Hope this didn't come over condescending or too rough, I just was shocked about the "antique" version number ; ). Should you need any more help I'm happy to provide it (when I find the time % ).

Else I hope your issue will be solved by **updating** `gbi` and using another image, I'd like to see this issue closed with you happy : ).

Best,

Tim.

**Comment by erichodges** [comment]
Hi @timhagn ,

Thank you for taking the time to look at this! :-). I appreciate your efforts. 

My mistake for not looking at the version. Maybe I used a starter from the Gatsby site? Anyway, I tried to upgrade it and it was giving me errors so I just cloned the latest version from your repo and the focus is working now. 

Best,

Eric

**Comment by timhagn** [comment]
Hi @erichodges,

happy to have helped solving it : ).

Best,

Tim.
