### ISSUE TITLE
Set `IntersectionObserver`'s `rootMargin` through props

### ISSUE THREAD

**Issue by mkaradeniz** [timhagn/gatsby-background-image#86]
## Summary

Would it be possible to make the `IntersectionObserver`'s `rootMargin` option configurable through props? 

### Motivation

I have a lot of background images one after another and would like to start the lazy loading sooner when scrolling through.

**Comment by timhagn** [comment]
Hi @mkaradeniz,

should be an easy one, once was even discussed over at `gatsby-image` - before they switched to native browser lazy-loading (which sadly is still not a thing for background images). Wanna make a PR : )?

Best,

Tim.

**Comment by timhagn** [comment]
Hi @mkaradeniz,

I just published `v0.8.19` with an added `rootMargin` prop (a `string` defaulting to `200px`).
Happy testing, for me it's working fine ; ). Should it work for you, too, you're of course welcome to close this issue : ).

Best,

Tim.

**Comment by mkaradeniz** [comment]
Sorry, I would have tried to do it, but was unable in the last week. That sounds awesome, thank you so much!

l'll let you know if it works.

**Comment by timhagn** [comment]
No need to be sorry, am plastered with work at the moment, too % ). Happy to finally have found the time to get on it, again. And it really wasn't that much a hazzle, so no sweat ; ).

Hope it works for you, too : ).

**Comment by mkaradeniz** [comment]
It doesn't work for my usecase, but I think it is because of https://github.com/w3c/IntersectionObserver/issues/301 

The project I'm working on uses horizontal scrolling throughout and `rootMargin` doesn't seem to work for that at the moment. Sigh.

Thank you though, and I'm closing this for now :)

**Comment by timhagn** [comment]
Oh, too bad, skimmed through it and this really doesn't seem to help : /. Searched MDN, as I was intrigued, and one perhaps can hope on the [future](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/thresholds), if I read it correctly... Or back to `window.onscroll` ; ).

Good luck! Best,

Tim.
