### ISSUE TITLE
Overlay not rendering, only the image

### ISSUE THREAD

**Issue by cwoz117** [timhagn/gatsby-background-image#87]
## Summary
Set up my page index to have a hero image with overlay text, but the index only shows the hero image. No overlay text (not even in inspect/page source)

```javascript
const Index = () => {
  const data = useStaticQuery(graphql`
    //removed for brevity, as the image is rendering
  `)
  return (
    <Layout>
      <BackgroundImage fluid={data.image.childImageSharp.fluid}>
        <h1>My Overlay Text, will contain buttons too!</h1>
      </BackgroundImage>
    </Layout>
  )
}
```

I'm certain this isn't a bug since the issues haven't pulled up anything about children not being rendered, or anything to do with Overlaying text. Further, the internet and google shows really no issue regarding this (admittedly, my google-fu does need work)

What is missing? Does background image need to be in a stand-alone component or is it not allowed within a gatsby page?

**Comment by timhagn** [comment]
Hi @cwoz117,

might you be so kind and give me your `gatsby info`? Or even better, test it again with [gbitest](https://github.com/timhagn/gbitest), as I don't see any issue here oO...
(And nope, it doesn't need to be a standalone component ; ).

Best,

Tim.

**Comment by cwoz117** [comment]
I'm on my work machine now (with the same issue) I'll post the info of this machine, and the home machine will be tonight:

gatsby info:
```
  System:
    OS: Linux 4.18 CentOS Linux 8 (Core)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Firefox: 68.2.0esr
  npmPackages:
    gatsby: ^2.17.6 => 2.17.6
    gatsby-background-image: ^0.8.18 => 0.8.18
    gatsby-image: ^2.2.30 => 2.2.30
    gatsby-plugin-sharp: ^2.2.36 => 2.2.36
    gatsby-source-filesystem: ^2.1.35 => 2.1.35
    gatsby-transformer-sharp: ^2.3.2 => 2.3.2
  npmGlobalPackages:
    gatsby-cli: 2.8.8
```

gbitest shows the gatsby space man on the left (and in page 2) but not on the right, its just the background with no test.

**Comment by timhagn** [comment]
Does it look like the following? Cause that's like `gbitest` should look like - on the right is a plain `gatsby-image` ; ).
![Screenshot from 2019-11-13 20-53-10](https://user-images.githubusercontent.com/12220779/68799111-e446fb80-0657-11ea-8480-6953966f60be.png)

Still can't replicate your issue - care to prepare an example repo?

**Comment by timhagn** [comment]
Hi @cwoz117,

I just bumped all deps of `gbitest` with publishing `v0.8.19`. I still couldn't replicate your issue (even in a Windows VM), it continues to work like in the image above. Would you mind testing it again, or finally provide a reproducible test-repo? Else I'm gonna close this on Sunday, no offense meant, but for me theirs not much else to do...

Best,

Tim.

**Comment by timhagn** [comment]
Mkay, I'm gonna give you a few days more to reply, but I'm gonna close the issue within the week...

**Comment by timhagn** [comment]
I'm gonna have to close this now. Feel free to provide a reproducible repo and I'm of course gonna open it again.

Best,

Tim.
