### ISSUE TITLE
Why does `gatsby-background-image` serve up much larger images than `gatsby-image`?

### ISSUE THREAD

**Issue by jonearley** [timhagn/gatsby-background-image#88]
## Problem

Images that render are much larger when using `gatbsy-background-image` than `gatsby-image`.

## Test results

The demo test site to compare `gatbsy-background-image` to `gatsby-image`: 
https://gatsby-image-test.netlify.com/

The repo and image component file:
https://github.com/jonearley/gatsby-image-test/blob/master/src/components/image.js.

The source images: 
- https://github.com/jonearley/gatsby-image-test/blob/master/src/images/aael-mujos1-sept2019.jpg
- https://github.com/jonearley/gatsby-image-test/blob/master/src/images/shapiro-berts4-apr2019.jpg

### At 1280px wide viewport:
- gatsby-image: 181KB
- gatsby-background-image: 401KB

![Screen Shot 2019-11-25 at 9 32 31 AM](https://user-images.githubusercontent.com/1678665/69549044-8921dc80-0f66-11ea-9e10-f02dedfb2590.png)

### At 2880px wide viewport:
- gatsby-image: 181KB
- gatsby-background-image: **3.2MB**

![Screen Shot 2019-11-25 at 9 47 07 AM](https://user-images.githubusercontent.com/1678665/69550203-9cce4280-0f68-11ea-90b8-798abd994c8d.png)

## Expected result

That image sizes are about the same whether `gatsby-image` or `gatsby-background-image` is used.

## Questions

- Why are the image file sizes so different? Shouldn't they be about the same?
- Am I configuring `gatbsy-background-image` incorrectly?
- What does `maxWidth` do exactly? It seems like images can be wider than this setting.

Thank you for helping me understand this unexpected result!

### Environment

```
  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Firefox: 70.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.18.3 => 2.18.3
    gatsby-background-image: ^0.9.7 => 0.9.7
    gatsby-image: ^2.2.33 => 2.2.33
    gatsby-plugin-manifest: ^2.2.29 => 2.2.29
    gatsby-plugin-offline: ^3.0.23 => 3.0.23
    gatsby-plugin-react-helmet: ^3.1.15 => 3.1.15
    gatsby-plugin-sharp: ^2.3.3 => 2.3.3
    gatsby-source-filesystem: ^2.1.38 => 2.1.38
    gatsby-transformer-sharp: ^2.3.5 => 2.3.5
  npmGlobalPackages:
    gatsby-cli: 2.7.50
    gatsby: 0.12.46
```

**Comment by timhagn** [comment]
Hi @jonearley,

gotta have to find some find to have a closer look at the behavior, but from a first glance & the top of my head:
Have you tried switching the images for both components?
As they seem to differ a great deal that might result in a quite different re-compression through `gatsby-plugin-sharp` & `gatsby-transformer-sharp`, which in reality are the "culprit" when looking at image sizes.
`gatsby-image` & `gatsby-background-image` are just display-components, as you probably already know % ).

Best,

Tim.

**Comment by jonearley** [comment]
Hey @timhagn. Thanks for your ideas and response!

My best idea is it has something to do with the component or browser-client-end-of-things not selecting the right image to render from the image src set, because the image size for `gatsby-background-image` varies greatly at wide viewports when `gatsby-image` is consistent in size after the set `maxWidth`. But. I'm just not sure to be honest.

## Have you tried switching the images for both components?

When switching the images I get a similar unexpected result. The `gatsby-background-image` rendered version is much larger still.

PR with this change:
https://github.com/jonearley/gatsby-image-test/pull/1

Preview build:
https://deploy-preview-1--gatsby-image-test.netlify.com/

### At 1280px wide viewport:
- gatsby-image: 185KB
- gatsby-background-image: 372KB

![Screen Shot 2019-11-25 at 5 46 41 PM](https://user-images.githubusercontent.com/1678665/69584701-de341180-0fab-11ea-9689-54af8ca36b8b.png)

### At 2880px wide viewport:
- gatsby-image: 181KB
- gatsby-background-image: 401KB

![Screen Shot 2019-11-25 at 5 46 30 PM](https://user-images.githubusercontent.com/1678665/69584699-dbd1b780-0fab-11ea-86c2-0ef39c7e65de.png)

---

**Comment by timhagn** [comment]
Hi @jonearley,

mkay, that's a strange behavior oO... Gonna try to have a look at it during the weekend, am next to fully booked during the week at the moment. Thanks for providing so much concise information, greatly appreciated : )!

Best,

Tim.

**Comment by timhagn** [comment]
Hi again, @jonearley!

After a hefty week I finally got to have a look at your repo and could instantly see your issue. But, alas, the fix was an easy one to do: I forgot to add the `sizes` props to the internally used `imageRef` % ). The changes, which should rectify the issue are already in the published `gbi` `v0.9.8`, version `1.0.0` is lurking at the horizon, methinks ; ).
Hope it works fo you as well, would you be so kind to test it? When it does, the honors of closing this issue are of course yours!

Best,

Tim.

**Comment by jonearley** [comment]
@timhagn Excellent! I updated to `v0.9.10` and this issue has been completely resolved. The real page I was working on where I first noticed this was about **65MB**! Now [it's 1.2 MB at a 1280px wide viewport](https://preview.lib.umich.edu/locations-and-hours). Much better!

Thank you for the fix!

**Comment by timhagn** [comment]
Hi @jonearley,

thanks for spotting this! Wouldn't have wanted an explosion in traffic cause of it ; ).
Great it works for you as well!

Best,

Tim.
