### ISSUE TITLE
Blur up doesn't appear to work when sources are art directed

### ISSUE THREAD

**Issue by ardiewen** [timhagn/gatsby-background-image#99]
## Description

I can't seem to get the "blur up" animation of the images to work when I am including art directed sources. Blur up works fine when using a single fixed/fluid image.

### Steps to reproduce

1. `gatsby-starter-default` with `gatsby-background-image`, `gatsby-image`, `gatsby-plugin-sharp`, `gatsby-transformer-sharp`, `gatsby-source-filesystem` dependencies.

2. use a static query to get 2 images from the filesystem

```
  const { mobile, desktop } = useStaticQuery(graphql`
    query GET_IMAGES {
      mobile: file(relativePath: { eq: "thank-you-hero-mobile.jpg" }) {
        childImageSharp {
          fluid {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
      desktop: file(relativePath: { eq: "thank-you-hero.jpg" }) {
        childImageSharp {
          fluid {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
    }
  `)
```

3. combine them to a sources array as described in the documentation:

```
  const sources = [
    mobile.childImageSharp.fluid,
    {
      ...desktop.childImageSharp.fluid,
      media: `(min-width: 800px)`,
    },
  ]
```
4. create a component that uses only one image, testing if blur up works (it does):

```
      <BackgroundImage
        fluid={mobile.childImageSharp.fluid}
        style={{ height: "50vh" }}
      />
```

5. create a component that uses the array of images (art directed) and test if blru up works (it appears to fade in after a short delay, no blurring):

```
      <BackgroundImage fluid={sources} style={{ height: "50vh" }} />
```

Minimal reproduction here: 
https://codesandbox.io/s/tender-bell-oc8pl

### Expected result

Blur up should work on art directed arrays of source images.

### Actual result

A simple "fade in" of the image, usually exposing the background color (if it was set) before the image is fully loaded.

### Environment

See minimum reproduction on codesandbox:
https://codesandbox.io/s/tender-bell-oc8pl

**Comment by as703** [comment]
I have found the same issue. Posted under the ‘Gatsby’ issue section - https://github.com/gatsbyjs/gatsby/issues/21307. Example site with problem here. Be great to hear about a potential solution to this one.

**Comment by timhagn** [comment]
Hi @ardiewen & @as703,


as you have already given a `gatsby info` in your issue over at gatsby (now closed), @as703, might I guess that you both used Safari for your tests on macOS? Correct me if I'm wrong, but at least here with latest FF & Chome versions on Linux everything worked for me with the just published `v0.9.16`. Might you both give it a try?

Thnx & best,

Tim.

**Comment by as703** [comment]
Hi Tim, Thanks for your reply. I used Firefox 73.0 - latest version. No blur up. I tried with Safari as well but it still didn't work.

Do you get blur up when using my test case: https://github.com/as703/gatsby-test.git?

Many thanks.

**Comment by ardiewen** [comment]
Hi @timhagn, thanks for following up. I actually was using Chrome 80 on Mac OS X.

I have updated my codesandbox reproduction to gatsby-background-image v0.9.16 and have made a small screen recording showing the bug on Chrome Version 80.0.3987.87 (Official Build) (64-bit).

Here's the screen recording for reference:
https://imgur.com/a/KSk2hnI

Here's the codesandbox (updated gatsby-background-image v0.9.16), in lieu of gatsby info:
https://codesandbox.io/s/tender-bell-oc8pl

Here's the codesandbox browser link (may not work without the sandbox open):
https://oc8pl.sse.codesandbox.io/

**Comment by timhagn** [comment]
Hi @as703 & @ardiewen,

ah, now I see it - when using it with a full-width browser it appeared to work (which it doesn't -.-).
Could replicate it with the "official" `gbitest` as well (it has a Tab for "Art Direction" now).
Gonna investigate further. 

But I'm really thinking bout a "minor" rewrite for `v1.0.0`, dropping support for `react` < `16.8.0`.
Hooks would make so many things so much easier for me % ).
`gatsby peerDependency` is at `^16.4.2` - don't know when they are gonna upgrade that, although the Docs most example use Hooks *\*hmmz*\* (one may dream ; )...

Best,

Tim.

**Comment by timhagn** [comment]
Hola to you both, @as703 & @ardiewen,

sat down (was too intrigued ; ) & solved it in two hours time % ). At least for me it now works with the just published `v0.9.17` in `gbitest` (the Example Repo), would you mind testing (also with yours)?
![image](https://user-images.githubusercontent.com/12220779/74562364-f132fe00-4f6a-11ea-8954-82a279ff25b9.png)

Best,

Tim.

**Comment by as703** [comment]
Many thanks Tim, it's now working. You are everything that's right with the Internet. I'll leave it to  @ardiewen to close.
Best wishes.

**Comment by timhagn** [comment]
Thanks! 
But, alas, with the production build the first (in my case smallest) Base64 Image shortly flashes for all sizes -.- Gonna look into it, but at least it's bluring up (or using the `tracedSVG`) and uses the correct WebP if existent, so two boxes checked out of three % ).

Best wishes,

Tim.
Tim.

**Comment by timhagn** [comment]
Just tested your codesandbox again (yesterday codesandbox didn't work for me), @ardiewen & yup, in SSR it works ^^:
https://codesandbox.io/s/heuristic-star-rzpbl

Gonna try investigating further to get the build working as well % ).

**Comment by timhagn** [comment]
Hola to you both! 

The just published `v0.9.18` should fix yesterday's flashes : ). Care to try? 
(I already updated the codesandbox as well, @ardiewen ; ).

Hope this may now be seen as fixed : ).

Best & nice weekend,

Tim.

**Comment by timhagn** [comment]
With `v0.10.0` the `noscript` handling is also fixed : ).

**Comment by ardiewen** [comment]
Thanks so much @timhagn, I'm confirming that it's working for me as well and closing the issue.
